source-git-to-srpm.py
Closes #5
@lachmanfrantisek change it as you wish, feel free to completely change structure, functions, names.
Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>
=> initial implementation of source git → dist-git

watch-fedora-ci.py
Finished: I have successfully updated status of https://github.com/TomasTomecek/docker-py-source-git/pull/2
=> implement reflecting downstream check results in source git

onegittorulethemall/services/our_pagure.py, onegittorulethemall/services/pagure.py, sourcegit/sync.py, tests/integration/pagure.py
Do not need to use `PAGURE_USER` variable.
=> Get Pagure username from API if needed

Makefile, README.md, deploy.yaml, onegittorulethemall/services/our_pagure.py, onegittorulethemall/services/pagure.py, sourcegit/cli/watch_fedora_ci.py, sourcegit/cli/watch_sg_pr.py, sourcegit/constants.py, sourcegit/sync.py, sourcegit/transformator.py
Will resolve #17 #13 
I am opening from upstream so the both of us can push to the branch.
Ready for review and merge.
=> containerize syncer, make sync process perfect

deploy.yaml, recipe.yaml, sourcegit/api.py, sourcegit/cli/sourcegit_base.py, sourcegit/cli/watch_fedora_ci.py, sourcegit/cli/watch_sg_pr.py, sourcegit/fed_mes_consume.py, sourcegit/watcher.py
And actually fix processing them: we now listen for more gh pr events.
=> [2] rewrite fedmsg consuming

deploy.yaml, sourcegit-mapping.json, sourcegit/api.py, sourcegit/downstream_checks.py, sourcegit/sync.py, sourcegit/watcher.py
=> [3] reset checks when doing a downstream sync

sourcegit/cli/sourcegit_to_srpm.py
* docs
* remove unused CLI arg
* pass upstream-ref further
=> polish sg2dg a bit

README.md
=> readme: share plans, clean up

recipe.yaml
Containerized packit will have master version of the OGR.
=> Add installation of the master version of OGR

Makefile, deploy.yaml, recipe.yaml
+ recipe: one block with all the dnf deps
Fixes #54
=> fix 54: deploy using buildah rootless store

README.md
=> README: Add greenboot to candidates for early adoption

packit/api.py, packit/cli/packit_base.py, packit/cli/sourcegit_to_dist_git.py, packit/cli/sourcegit_to_srpm.py, packit/cli/update.py, packit/cli/watch_fedora_ci.py, packit/cli/watch_sg_pr.py, packit/config.py, packit/dg_robot.py, packit/local_project.py, packit/sync.py, packit/transformator.py, packit/utils.py, packit/watcher.py
- Packit can download sources from upstream.
@TomasTomecek TODO:
=> WIP: update command

README.md
=> Add local installation and usage

README.md
This pull request updates README with the on_boarding project for using packit.
Please let me know if something is missing. I would be glad.
=> Update README for on_boarding project

Jenkinsfile, Makefile, README.md, deploy.yaml, recipe-tests.yaml
https://ci.centos.org/job/packit-pr/
=> Jenkinsfile && tests in container

docs/how-to-source-git.md
=> add tutorial for source-git

packit/config.py
=> Python 3.6 backward compatibility

README.md
rebase-helper has already requested files in upstream repository https://github.com/rebase-helper/rebase-helper/pull/582
=> Add rebase-helper to candidates

.gitignore, packit/api.py, packit/cli/sourcegit_to_dist_git.py, packit/cli/sourcegit_to_srpm.py, packit/config.py, packit/distgit.py, packit/upstream.py, tests/unit/test_config.py
Also some UX goodies which make problems easier to investigate.
=> Nicer `packit propose-update`

packit/cli/update.py, packit/distgit.py
In case upload failed with Kerberos reason, do not continue.
=> Fixes #80 improve message in case new_sources fails

docs/update.md, packit/distgit.py, packit/upstream.py
also better docs and rainbows
Fixes #101
=> fail when a file to be synced is not present

Jenkinsfile, docs/configuration.md, docs/update.md, packit/api.py, packit/bot_api.py, packit/cli/update.py, packit/cli/watch_upstream_release.py, packit/config.py, packit/constants.py, packit/distgit.py, packit/fed_mes_consume.py, packit/local_project.py, packit/upstream.py, recipe-tests.yaml, tests/integration/test_update.py, tox.ini
TODO:
Got a little deeper than I wanted:
* write a test for `watch-releases <msg_id>`
* let prop-updt accept paths to dg and sg
* refactor
* fixes
=> \o/ GREEN CI \o/

packit/cli/update.py
since nobody has responded to my https://github.com/packit-service/packit/pull/93#discussion_r262595073
=> Let user know what happened also when debug is not on

packit/cli/packit_base.py, packit/cli/update.py, packit/cli/watch_upstream_release.py, packit/distgit.py, packit/utils.py, tests/integration/test_pagure.py, tests/integration/test_update.py, tests/spellbook.py
=> Code changes to land by 0.1.0

packit/cli/watch_sg_pr.py, packit/cli/watch_upstream_release.py
=> Remove shebangs where not needed

CHANGELOG.md, README.md, docs/01.md, docs/update.md, packit/api.py, packit/cli/update.py, packit/distgit.py, packit/local_project.py, tests/__init__.py, tests/integration/test_update.py
=> 0.1.0 release

packit/api.py, packit/cli/build.py, packit/cli/packit_base.py, packit/distgit.py, packit/utils.py, tests/conftest.py, tests/integration/test_build.py, tests/integration/test_update.py, tests/spellbook.py
I made this build with the command:
https://koji.fedoraproject.org/koji/taskinfo?taskID=33359322
TODO:
=> add build command

packit/api.py, packit/config.py, packit/distgit.py, packit/upstream.py, packit/utils.py, tests/conftest.py
Result of my `propose-update` experiments.
=> Miscellaneous

packit.spec
We need to wait for the PyPI release since we are using PyPI tarballs.
TODO:
=> Add packit specfile

packit/api.py, packit/upstream.py, packit/utils.py, tests/integration/test_upstream.py, tests/unit/test_cli.py
please merge right away if you like this
* upstream: break down get_upstream_version
* run_command: log stderr output if there is some
TODO
=> Generic changes before sending the `srpm` command

.packit.yaml, packit.spec
- Bump version in specfile.
- Add packit config.
=> Add packit config and bump version in specfile

packit/cli/create_update.py, packit/distgit.py
- Catch the Bodhi exception.
- Mention NVR in create-update.
=> Bodhi fixes

.packit.yaml, README.md, docs/build.md, docs/configuration.md, docs/create_bodhi_update.md, docs/propose_update.md, docs/source-git.md, docs/srpm.md
* slim readme, move s-g pitch to docs/s-g
* docs for all the code we already have
* `build`
* `create-update`
* `srpm`
* updates
=> We ♡ docs!

packit/distgit.py, setup.cfg, tests/integration/test_create_update.py
- Add correct bodhi response in create-update tests.
- Fix missing caveats in bodhi response.
=> Fix bodhi tests

packit/distgit.py, tests/conftest.py, tests/integration/test_distgit.py
=> Better err message when committing in a clean repo

packit/distgit.py
=> Better error when push to fork fails.

packit/config.py, recipe.yaml, setup.cfg, tests/unit/test_config.py
=> Drop anymarkup, yaml.safe_load() is all we need

packit/distgit.py, packit/upstream.py, tests/integration/test_update.py
https://github.com/rebase-helper/rebase-helper/issues/597
=> rebase-helper: use get_version instead of get_full_version

docs/configuration.md, packit/config.py, packit/distgit.py, packit/service/web_hook.py, tests/unit/test_config.py
* a test case for get_user_config
* document user config
* config: annotate properties, more logging
* drop pagure_package_token value: we're not using it
* document mandatory config values
Fixes #150
=> user config: docs and test

packit/api.py, packit/cli/packit_base.py, packit/cli/status.py, packit/status.py, setup.cfg
Checklist:
I don't know what is the problem with checkout to dist-git branches.
Output after running inside `packit` directory itself:
```
$ packit status
Cloning repo: https://src.fedoraproject.org/rpms/packit.git -> /tmp/tmpqs91dr48
Downstream PRs: No open PRs.
Dist-git versions:
Branch f29 doesn't exists.
Branch f30 doesn't exists.
master: 0.2.0
GitHub upstream releases:
0.2.0
0.1.0
0.0.1
Latest builds:
f29:
- packit-0.1.0-1.fc29
f30: No builds.
Latest bodhi updates:
Update                 Stable karma    Unstable karma  status
-------------------  --------------  ----------------  --------
packit-0.2.0-1.fc29               3                -3  testing
packit-0.2.0-1.fc30               3                -3  testing
packit-0.1.0-1.fc29               3                -3  stable
```
=> WIP: Status command

packit/upstream.py, setup.cfg, tests/integration/test_upstream.py
Fixes: https://github.com/packit-service/packit/issues/190
=> Pick latest version when not specified (URM vs. spec)

packit/api.py, packit/config.py, packit/distgit.py, packit/fedpkg.py, packit/upstream.py, packit/utils.py, tests/conftest.py, tests/unit/test_config.py
- Remove unused utils function.
- Move fedpkg to other file.
------
=> WIP: configurable actions and sourcegit support

packit.spec, packit/cli/packit_base.py
=> [spec] generate man pages with click-man

.gitignore, CONTRIBUTING.md, Makefile, files/passwd, packit/service/web_hook.py, recipe.yaml, setup.cfg, tests/functional/test_webhook.py
Kudos to @dhodovsk for starting this.
This PR completes the openshift work for packit service and also adds a decent local development experience.
TODO:
=> All hail packit service!

README.md
Signed-off-by: Clement Verna <cverna@tutanota.com>
=> Add OSBS to the early adoption candidate

packit/local_project.py, tests/unit/test_local_project.py
=> support of ssh url

packit/api.py, packit/status.py, tests/integration/bodhi_latest_builds.py, tests/integration/test_status.py
This pull request covers Status test, especially `get_builds` https://github.com/packit-service/packit/blob/master/packit/status.py#L111
=> test covers Status.get_builds

packit.spec
https://src.fedoraproject.org/rpms/packit/pull-request/9
=> [spec] Generating man pages during build needs all requirements

packit/cli/packit_base.py
Also fixing in click_man: https://github.com/click-contrib/click-man/pull/31
=> Fix generation of man pages

docs/configuration.md, packit/api.py, packit/bot_api.py, packit/config.py, packit/exceptions.py, packit/jobs.py, packit/schema.py, packit/service/web_hook.py, packit/status.py, packit/utils.py, tests/data/upstream_git/.packit.json, tests/unit/test_config.py, tests/unit/test_steve.py
=> Implement jobs

packit/service/web_hook.py
https://developer.github.com/webhooks/#ping-event
=> /webhooks/github/release reacts to ping event

.packit.yaml, fedora-tests/simple.py, fedora-tests/tests.yml, fedora-tests/upstream.sh
Downstream commit: e45f51fd481039a8f527451944a2feb4816ccebc
=> Update from downstream branch 'master'

.pre-commit-config.yaml, files/packit.wsgi, files/passwd, recipe.yaml
This pull request adds two packages for packit-service.
Will is if `packit/service/web_hook.py` should be slightly modified or not.
=> Add httpd and mod_wsgi for packit-service

CONTRIBUTING.md, Dockerfile, Makefile, recipe.yaml
=> Building using `docker build`

docs/configuration.md, packit/cli/packit_base.py, packit/config.py, packit/distgit.py, packit/jobs.py, packit/ogr_services.py, packit/schema.py, packit/upstream.py
replaces https://github.com/packit-service/packit/pull/228
because was not able to rebase easily
=> implement dry run option to packit

packit/api.py, packit/status.py, packit/upstream.py, tests/unit/test_base_git.py
=> fix bug with no GithubProject instance

Dockerfile, Makefile, docs/configuration.md, files/httpd-copy.sh, files/install-rpm-packages.yaml, files/passwd, packit/api.py, packit/base_git.py, packit/config.py, packit/jobs.py, packit/local_project.py, packit/ogr_services.py, packit/schema.py, packit/service/web_hook.py, packit/upstream.py, packit/utils.py, recipe.yaml, tests/conftest.py, tests/integration/test_build.py, tests/integration/test_copr.py, tests/integration/test_create_update.py, tests/integration/test_source_git.py, tests/integration/test_sync_files.py, tests/integration/test_update.py, tests/unit/test_base_git.py, tests/utils.py
A giant pile of fixes needed to achieve https://github.com/packit-service/systemd-source-git/pull/1#issuecomment-487289094
=> Let's get ready to rumble

packit/api.py, packit/jobs.py, tests/integration/test_copr.py
This is just a first iteration so we have at least some reporting, but feel free to wait with the merge for a better version that is in progress:
- report on PR using CI status - if possible
- use commit status instead of commit comment
- use fedmsg/copr webhooks for obtaining results
=> watch copr build

packit/utils.py
- Fix debug of command in run_command.
=> Fix run_command debug

docs/actions.md, packit/api.py
- Add post_upstream_clone to srpm.
- Split actions in doc per command.
Fixes #292
=> SRPM actions

.packit.yaml, .pre-commit-config.yaml, packit/jobs.py, packit/service/web_hook.py
And also:
* properly process timeout from the config
* pre-commit: do black first - so that flake8 doesn't yell about things which black will change
=> webhooks: run Steve in a separate thread, sorry Steve

packit/service/web_hook.py, tests/unit/test_web_hook.py
=>  Don't let signature validation stop us

.packit.yaml, tests/integration/test_copr.py
Packit is not reporting status of the copr build and I don't know why.
=> Pull two commits out of #300

packit/ogr_services.py, packit/status.py, tests/integration/test_source_git.py
cherry picked from https://github.com/packit-service/packit/pull/303
=> help test mocking

packit/api.py, packit/cli/status.py
The issue solves a problem if libpagure fails with json.decode.JSONDecodeError traceback.
=> Status continue even if libpagure fails with JSON error.

packit/api.py
https://pagure.io/libpagure/blob/master/f/libpagure/libpagure.py#_97
Fixes #305
=> Libpagure raises general Exception when API call response can't be decoded

Makefile, Vagrantfile
This brings packit support in Vagrant environment.
=> Support for Vagrant

README.md
=> Typo in the contact

packit/sync.py
=> [sync_files()] rmtree dest if exists before copytree

packit/sync.py
Should have checked this in #331, sry
=> Fix a debug message.

packit/api.py, packit/cli/generate.py, packit/cli/packit_base.py, packit/constants.py, tests/conftest.py, tests/integration/test_generate.py
This is initial work on #217.
TODO:
=> Packit init a.k.a `packit generate`

packit/distgit.py
- Fix path of the downloaded source archive.
=> Fix source archive path

packit/api.py, packit/cli/sync_from_downstream.py, packit/sync.py
- Add exclude to sync-from-downstream CLI.
- Fix syncing from downstream.
=> Fix sync from downstream and add exclude to cli

README.md
This is an elevator pitch for packit.
Let's use it in PR
=> Elevator pitch

docs/configuration.md
\+ update info about service launch
=> docs,conf: make synced_files section more clear

packit/ogr_services.py
=> PersistentObjectStorage: use new arg

packit/cli/utils.py
Better exception when the token is not supplied.
Fixes #339
=> better exception - issue 339

files/install-requirements.yaml, packit/api.py, packit/base_git.py, packit/command_runner.py, packit/config.py, packit/upstream.py, tests/integration/test_base_git.py, tests/unit/test_base_git.py, tests/unit/test_cli_utils.py
This pull request adds the possibility to execute actions in CLI or in Openshift.
=> Command runner with implemented classes

packit/command_handler.py
since we don't have ReadWriteMany in our prod openshift cluster
Requires: https://github.com/packit-service/sandcastle/pull/18
=> sandcastle: use MappedDir instead

packit/api.py, packit/constants.py, packit/sync.py, tests/integration/test_update.py
=> README during propose-update created

packit/base_git.py, packit/config.py
... I need better matroš or something; how could I miss this?
=> fix sandbox command runner

docs/configuration.md, packit/api.py, packit/command_handler.py, packit/upstream.py
I removed parts which are not verified to be working well.
=> prep config docs for the launch

.packit.yaml, packit/command_handler.py, packit/upstream.py, tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_builds_github.yaml, tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_distgen_versions_github.yaml, tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_dowstream_pr_github.yaml, tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_status_github.yaml, tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_up_releases_github.yaml, tests/integration/test_data/test_status/tests.integration.test_status.TestStatus.test_updates_github.yaml, tests/integration/testbase.py
Requires packit-service/sandcastle#21
=> utilize new sandcastle api and revert the workaround

packit/ogr_services.py
See https://github.com/packit-service/ogr/pull/84/commits/c50d79534b003821f64e62b7cf5dd0d7d408d2a2 from https://github.com/packit-service/ogr/pull/84
=> PersistentObjectStorage.__init__() no longer accepts write_mode

packit/api.py, packit/base_git.py, packit/command_handler.py, packit/upstream.py, packit/utils.py, tests/data/dist_git/beer.spec, tests/integration/test_source_git.py, tests/integration/test_update.py
Fixes #298
~~also carries #394 so wait for it to get merged first~~
=> preserve %changelog and bump spec when updating in fedora

packit/api.py, packit/cli/sync_from_downstream.py, packit/cli/update.py, tests/conftest.py, tests/integration/test_update.py
=> Dirrect push to distgit

packit/cli/types.py, packit/cli/utils.py, packit/constants.py, packit/distgit.py, packit/local_project.py, packit/upstream.py, packit/utils.py, tests/conftest.py, tests/integration/test_build.py, tests/integration/test_create_update.py, tests/integration/test_update.py, tests/integration/test_upstream.py, tests/unit/test_local_project.py, tests/unit/test_utils.py
`78 insertions(+), 143 deletions(-)`, I'm proud of myself. (I removed tests which are no longer relevant)
\+ cli: path_or_url should overwrite default: cwd
Fixes #192
=> exterminate path_or_url

tests/unit/test_base_git.py
=> skip test if sandcastle is not installed

packit/config.py, tests/unit/test_config.py
since we can't create PRs in src.fp.o, still
=> set create_pr to False

files/install-requirements.yaml, packit.spec, packit/distgit.py, packit/fedpkg.py, setup.cfg, tests/conftest.py
b/c pygit doesn't work with the fedora setup
Fixes #421
TODO:
=> clone dist-git repos with fedpkg-clone

packit/api.py, packit/base_git.py, packit/cli/sync_from_downstream.py, packit/cli/update.py
=> don't discard changes if the repo is dirty

packit/cli/utils.py, packit/config.py, packit/distgit.py, tests/conftest.py, tests/integration/test_build.py, tests/integration/test_create_update.py, tests/integration/test_update.py
Fixes #422
Will conflict with #423, so merge that one first, please
=> have a dedicated var in packageconfig for local dg clone

Dockerfile, files/install-requirements.yaml, files/zuul-tests.yaml, packit/distgit.py, packit/upstream.py, tests/data/cockpit-ostree/Makefile, tests/data/cockpit-ostree/cockpit-ostree.spec.in, tests/data/cockpit-ostree/packit.yaml, tests/integration/test_using_cockpit.py, tests/integration/testbase.py, tests/spellbook.py
#426
This time I also wrote an integration test using cockpit-ostree to make sure we do really fix the bug.
=> cd to dg when pulling sources w/ rebase-helper

packit/config.py
Job types
- `tests` - job in `.packit.yaml` (trigger is `pull_request`)
- `report_test_results` - job when we receive `POST` request from testing farm
Job triggers
- `testing_farm_results` - the trigger for reporting results to GitHub PR
Related to https://github.com/packit-service/packit-service/pull/73
=> add testing farm jobs and trigger

packit/schema.py
=> update config schema with a new job

packit/api.py, packit/upstream.py, tests/data/empty_changelog/.packit.json, tests/data/empty_changelog/beer.spec, tests/data/upstream_git/beer.spec, tests/functional/test_srpm.py, tests/integration/test_source_git.py, tests/integration/test_upstream.py, tests/spellbook.py
=> srpm: clearly distinguish b/w s-g and upstream use cases

files/install-requirements.yaml, files/zuul-install-requirements-rpms.yaml, packit/status.py, setup.cfg
=> [CLI status] get Koji builds from Koji, not Bodhi

packit/constants.py
=> [packit/constants.py] Improve comments in generated .packit.yaml

README.md
=> [README.md] Zuul badge

packit/api.py
=> sync_from_downstream changed: not creating a branch when no_pr

packit/api.py
=> [PackitAPI.run_copr_build] return web frontend url instead of repo_url

packit/api.py, tests/integration/test_api.py, tests/unit/test_api.py
=> Fix a bug in PackitAPI._copr_web_build_url()

packit/status.py, tests/integration/test_status.py
=> packit status: get_updates changed

Dockerfile
=> [Dockerfile] really define WORKDIR this time

packit.spec
=> spec: explicitly require python3-koji

packit/config.py, packit/distgit.py, packit/schema.py, pytest.ini, tests/integration/testbase.py, tests/spellbook.py, tests/unit/test_config.py
=> remove pagure_fork_token

packit/api.py
=> packit status: skip section if exc

packit/api.py, packit/cli/copr_build.py
=> copr_build: description, instructions arguments added

tests/testsuite_basic/integration/test_base_git.py
See `/tmp/package-test.sh` output in
https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-f30-pr-pipeline/detail/fedora-f30-pr-pipeline/162/pipeline/
=> Skip test if sandcastle can't be imported

packit.spec, packit/upstream.py, tests/testsuite_basic/integration/test_upstream.py
Fixes: https://github.com/packit-service/hello-world/issues/19
=> fix-spec: raise when upstream_project_name is not set

packit/api.py, packit/cli/packit_base.py, packit/constants.py, packit/utils.py, tests/testsuite_basic/unit/test_utils.py
=> version info added

packit/cli/packit_base.py, packit/utils.py
=> Move setting of the logging level in packit_base.py

packit/distgit.py
https://github.com/packit-service/packit/pull/534#issuecomment-537469894
=> upload_to_lookaside_cache() improve misleading exception message

packit/local_project.py
=> Make the logging in LocalProject better

packit/api.py, packit/config.py, packit/schema.py, tests/testsuite_basic/integration/test_update.py
=> Add upstream_tag_template to packit.yaml

CHANGELOG.md
sorry, can't help it, changelogs are my thing
=> polish 0.7.0 changelog a bit m0ar

tests/testsuite_recording/integration/test_api.py, tests/testsuite_recording/integration/test_status.py
Fixes https://github.com/packit-service/packit/issues/558
Fixes https://github.com/packit-service/packit/issues/561
=> recording test data: remove git repos

packit/distgit.py
=> Add missing f in python fstring

tests/testsuite_basic/data/cockpit-ostree/Makefile, tests/testsuite_basic/integration/test_using_cockpit.py
test long lines in create-archive
Related #577
=> Tests for #577

packit/api.py
=> Catch an error when SRPM runs in a repo with detached head

packit/api.py, packit/base_git.py, packit/helper.py, packit/specfile.py, packit/upstream.py, packit/utils.py, tests/testsuite_basic/conftest.py, tests/testsuite_basic/integration/test_source_git.py, tests/testsuite_basic/integration/test_update.py, tests/testsuite_basic/integration/test_upstream.py, tests/testsuite_basic/spellbook.py, tests/testsuite_basic/utils.py
=> Move rebase-helper code to a subclass

packit/specfile.py, packit/upstream.py, tests/testsuite_basic/integration/test_spec.py, tests/testsuite_basic/spellbook.py
=> Support both version methods to write spec content

packit/upstream.py
Signed-off-by: Martin Styk <mastyk@redhat.com>
=> Fix parameter name in function

packit/utils.py
=> Get realtime output from process

packit/api.py, packit/config/package_config.py, tests/unit/test_config.py
=> Propose-update - sync config file and spec file by default

packit/upstream.py, tests/unit/test_upstream.py
#604 
I didnt created any tests. Need to dig little bit more into integration to fully understand how it works. Wanted to add unit tests, but i am facing import issues
> ImportError while loading conftest '/home/saki/PycharmProjects/packit/tests/conftest.py'.
> ../conftest.py:9: in <module>
>...
> E   pkg_resources.DistributionNotFound: The 'packitos' distribution was not found and is required by the application
Is it possible to avoid this imports. My idea is to mock everything and test only "isolated"  method/function code.
If you are using different approach please give me some hints, so i can follow project style.
=> update Upstream.create_pull() according ogr update

Makefile
=> [make check_in_container] Don't pass TESTS_TARGET

packit/api.py, packit/config/package_config.py, tests/unit/test_config.py
- Creating of the pagure pull-requests are turned-on by default.
=> create-pr defaults to True

packit/config/aliases.py, tests/unit/test_config_aliases.py
Copr does not support f32 chroot.
=> Remove f32 from aliases

packit/api.py, packit/base_git.py
- Refresh specfile after each run of the propose-update.
- Fixes #629
=> Fix duplicated entries in specfile

packit/config/__init__.py, packit/config/base_config.py, packit/config/config.py, packit/config/job_config.py, packit/config/package_config.py, packit/config/sync_files_config.py, packit/schema.py, setup.cfg, tests/unit/test_config.py
Reverts packit-service/packit#620 until we have a PR for changing [ServiceConfig](https://github.com/packit-service/packit-service/blob/master/packit_service/config.py#L49) as well.
=> Revert "Marshmallow schema implementation"

packit/upstream.py
- Do not skip version update in fix_spec step on prep update error.
- Fixes: #641
=> Fix version update on srpm build

tests/integration/test_spec.py
test_spec was crying in the corner, alone in the darkness - let's move it to the other integration tests so they can play together and be happy
=> tidy tests

packit/api.py, tests/conftest.py, tests/data/upstream_git_with_multiple_sources/.packit.json, tests/data/upstream_git_with_multiple_sources/beer.spec, tests/functional/test_srpm.py, tests/spellbook.py
- Download URL sources before srpm build.
Fixes: #615
=> Multiple sources

packit/exceptions.py, packit/upstream.py, tests/integration/test_upstream.py
- Better exception messages for the SRPM. (We are using the messages in the service in the error comments.)
=> Better SRPM exception messages

packit/config/config.py, packit/schema.py
moved self.services initialization from cls.from_dict() to self.__init__()
=> authentication fixed

.packit.yaml
- Use aliases in the config file and do not test on rawhide because of the new marshmallow.
=> No testingfarm on rawhide because of the marshmallow

packit/base_git.py, tests/unit/test_upstream.py
- Allow list syntax for commands.
- Currently all these three usecases are possible:
```
I)
action_name: "one cmd"
II)
action_name:
- "one cmd""
III)
action_name:
- ["one", "cmd"]
```
=> Allow list in action commands

packit/api.py, packit/base_git.py, packit/cli/build.py, packit/exceptions.py, packit/fedpkg.py, packit/upstream.py, packit/utils.py, tests/data/upstream_git_with_multiple_sources/beer.spec, tests/integration/conftest.py, tests/integration/test_build.py, tests/integration/test_source_git.py, tests/integration/test_update.py, tests/unit/test_utils.py
TODO:
* ~~[ ] build from dist-git~~ we don't really need this
sample builds:
* https://koji.fedoraproject.org/koji/taskinfo?taskID=40372149
* https://koji.fedoraproject.org/koji/taskinfo?taskID=40372384
* sourcegit systemd https://koji.fedoraproject.org/koji/taskinfo?taskID=40610580
use like this:
```
$ PYTHONPATH=$PWD python3 -m packit.cli.packit_base build --from-upstream --scratch --nowait --koji-target=rawhide
```
=> build in koji from srpm

packit/upstream.py
~~Carries https://github.com/packit-service/packit/pull/658~~
~~so let's wait for it to get merged, then work on this~~
https://sentry.io/organizations/red-hat-0p/issues/1450362049/
=> srpm,p-s: _srcdir = spec dir

tests/unit/test_config.py
Related https://github.com/packit-service/packit-service/pull/342
=> add tests for package_config.job.job

files/bash-completion/packit, packit.spec, setup.cfg
=> Add bash completion script

packit/config/job_config.py, tests/unit/test_config.py
Fixes: https://sentry.io/organizations/red-hat-0p/issues/1458585589/?project=1767823
=> Use lists for default job targets

packit/fedpkg.py
=> [packit build] Catch an excpetion when failure on fedpkg side

packit/config/config.py
Signed-off-by: Michal Konečný <mkonecny@redhat.com>
=> Use instance url from configuration

packit/api.py, packit/cli/local_build.py, packit/cli/packit_base.py, packit/exceptions.py, packit/upstream.py, tests/functional/test_local_build.py
=> Add a new command for local build

packit/security.py, tests/unit/test_security.py
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/message/COEYWJBQDAWRSYNQW7Y7TD2EKEGBWOAY/
=> keys.fedoraproject.org -> keys.openpgp.org + packit/security.py rewrite

.packit.yaml
@lbarcziova do I understand it correctly that these values are no longer needed to be specified?
@lbarcziova we need to update [docs](https://packit.dev/docs/configuration/#top-level-keys) to describe the current status - will you do that?
=> [.packit.yaml] Remove no longer needed values

packit/config/package_config.py
I was seeing:
```
13:07:51.363 package_config.py DEBUG  The local config file '/home/jpopelka/git/source-git/HTTPretty/.packit.yaml' not found.
13:07:51.363 package_config.py DEBUG  The local config file '/home/jpopelka/git/source-git/HTTPretty/.packit.yml' not found.
13:07:51.363 package_config.py DEBUG  The local config file '/home/jpopelka/git/source-git/HTTPretty/.packit.json' not found.
13:07:51.363 package_config.py DEBUG  The local config file '/home/jpopelka/git/source-git/HTTPretty/packit.yaml' not found.
13:07:51.363 package_config.py DEBUG  The local config file '/home/jpopelka/git/source-git/HTTPretty/packit.yml' not found.
13:07:51.363 package_config.py DEBUG  The local config file '/home/jpopelka/git/source-git/HTTPretty/packit.json' not found.
13:07:51.363 package_config.py …
```
=> [get_local_package_config()] Don't duplicate entries in 'directories'

packit/api.py, packit/cli/copr_build.py
to support copr build from source-git
=> [cli] add --upstream-ref to copr-build

README.md, packit/config/config.py
=> Add links to docs about user configuration

packit/base_git.py, packit/upstream.py
=> [Upstream.create_patches()] Use format-patch's --output-directory

packit/base_git.py, packit/specfile.py, tests/integration/test_spec.py
per https://github.com/packit-service/packit/pull/730#discussion_r384967235
=> [Specfile.ensure_pnum] Re-use SpecFile (parent) methods

packit/config/package_config.py
=> [get_specfile_path_from_repo()] better regex

packit/config/package_config.py, packit/schema.py, tests/unit/test_config.py
related packit-service/packit-service#168
=> introduce package config commenting config

packit/cli/init.py, packit/cli/packit_base.py
#701 I have done the changes, please check if this is what you meant.
=> Rename packit generate to packit init

packit/schema.py
The "Path to spec file is not set." (seen in #465) is a bit confusing.
=> [PackageConfigSchema.specfile_path_pre()] better log messages

packit/distgit.py
previously:
About to force push changes to branch 0.11.0-f32-update of a fork fork of the dist-git repo
now:
About to force push changes to branch '0.11.0-f32-update' of a fork 'fork' of the dist-git repo.
=> fork fork -> fork 'fork'

packit/api.py, packit/distgit.py
in order to put the PR url in service generated issue comment, example:
https://github.com/packit-service/ogr/issues/348#issuecomment-596541601
=> PackitAPI.sync_release() returns new PullRequest

packit/config/package_config.py
=> Supply ref to get_specfile_path_from_repo()

packit/api.py, packit/base_git.py, packit/distgit.py, tests/integration/test_update.py
=> propose-update: create downstream spec if it's not there

tests/data/dg-ogr/.packit.yaml, tests/data/dg-ogr/python-ogr.spec
...to reflect recent changes in ogr packaging
I have also updated stuff in rawhide.
=> tests: update ogr's .packit.yaml and spec

CHANGELOG.md
#805 has already been auto-merged
=> [CHANGELOG.md] Update 0.10.1 description

fedora-tests/upstream.sh, files/packit-testing-farm-prepare.yaml
=> Configure Git in Testing Farm and Fedora

packit/upstream.py
Related: https://github.com/packit-service/packit-service/issues/507
=> upstream,get_version: log info about the git repo

packit/patches.py, packit/upstream.py
* drop dupe log 'SRPM is ...'
* source-git: log when commits are contained
=> 2 log lines change

files/install-build-deps.yaml
- Install master version of OGR to the image.
=> Use master ogr

packit/api.py, packit/base_git.py, packit/cli/srpm.py, packit/command_handler.py, packit/config/config.py, packit/config/job_config.py, packit/config/package_config.py, packit/config/sync_files_config.py, packit/copr_helper.py, packit/distgit.py, packit/downstream_checks.py, packit/fedpkg.py, packit/local_project.py, packit/patches.py, packit/schema.py, packit/security.py, packit/specfile.py, packit/status.py, packit/sync.py, packit/upstream.py, packit/utils.py
=> Make the format of logs more consistent

packit/api.py, packit/distgit.py, tests/integration/test_build.py, tests/integration/test_create_update.py, tests/integration/test_get_api.py, tests/integration/test_update.py
- Initialize kerberos for all distgit-related api methods.
- Fixes https://github.com/packit-service/packit/issues/837
=> Fix kerberos init

packit/config/job_config.py
needed in https://github.com/packit-service/packit-service/pull/634
=> New JobType.create_bugzilla

packit/config/job_config.py, packit/config/package_config.py, packit/schema.py, tests/unit/test_package_config.py
Needed for https://github.com/packit-service/packit-service/issues/418
[p-s PR](https://github.com/packit-service/packit-service/pull/640)
=> enable overriding package config per job

packit/copr_helper.py
- Add type annotations for CoprHelper.
=> Add type annotations to copr code

packit/schema.py, tests/unit/test_package_config.py
This PR enables dumping of the package config, which can be used in the packit-service when passing info into task
=> Allow dumping of the package config

tests_recording/__init__.py, tests_recording/test_api.py, tests_recording/test_status.py, tests_recording/testbase.py
this change is dependent on https://github.com/packit-service/requre/pull/100,
so please do not merge it now, Until requre will satisfy reverse dep testing.
=> fix the tests according to new version of requre

packit/upstream.py, tests/integration/test_upstream.py
Updated MR: https://github.com/packit-service/packit/pull/816/files
=> Copr build naming improvement

tests/conftest.py, tests/functional/test_srpm.py, tests/integration/conftest.py, tests/integration/test_get_api.py, tests/integration/test_pagure.py, tests/integration/test_upstream.py, tests/integration/test_using_cockpit.py, tests/integration/test_using_examples.py, tests/unit/test_config.py, tests/unit/test_unicodez.py
=> [tests] utilize tmp_path instead of tmpdir

packit/api.py, packit/copr_helper.py, packit/distgit.py, packit/fedpkg.py, packit/local_project.py, packit/upstream.py
=> Add missing __repr__()s

.packit.yaml
=> [.packit.yaml] remove 'sh -c' from create-archive

packit/api.py
this will help us resolve kerberos issues
=> print debug logs from kerberos to stdout

.packit.yaml, packit/api.py, packit/base_git.py, packit/command_handler.py, packit/utils.py, tests/data/dg-ogr/.packit.yaml, tests/unit/test_base_git.py, tests/unit/test_utils.py
This reverts commit c87aa49fdb53e258c4c33647e1bab9551ab657ce.
also:
```
Revert "[.packit.yaml] remove 'sh -c' from create-archive"
This reverts commit b2f9d54a057b0ead84824585ea3fb619723872e4.
```
Sorry about the problems, this seems to be much harder to implement than I
originally thought.
=> Revert "invoke all commands in shell"

fedora-tests/tests.yml, fedora-tests/upstream.sh
to required_packages
Fixes #909
=> [fedora-tests] Add python3-devel, python3-setuptools_scm_git_archive

packit/copr_helper.py, tests/integration/test_copr_build.py
- Allow edit of only those attributes that can we get from Copr API.
- Fixes: https://github.com/packit/packit/issues/925
=> Edit copr settings only for accessible attributes

packit/local_project.py, tests/integration/test_local_project.py, tests/unit/test_local_project.py
Adding support to checkout merge requests in Gitlab.
=> Support gitlab on checkout_pr

packit/api.py, packit/copr_helper.py
Related: https://github.com/packit/packit/issues/941
=> m0ar logging for some copr operations

packit/copr_helper.py, tests/integration/test_copr_build.py
- Append new copr chroots, do not remove existing ones.
- Related to this issue: https://github.com/packit/packit-service/issues/755
=> Append copr chroots

packit/command_handler.py, tests/unit/test_base_git.py
I got confused b/c in actions we put them in a list.
https://stg.packit.dev/srpm-build/1093/logs
=> fixup sandcastle logging: exec returns str, not List[str]

.pre-commit-config.yaml, packit/config/aliases.py, tests/integration/test_source_git.py
https://github.com/asottile/pyupgrade
=> Add pyupgrade to pre-commit

packit/api.py, packit/config/common_package_config.py, packit/patches.py, packit/upstream.py, packit/utils/repo.py, tests/integration/test_source_git.py
=> Support globbing pattern for tags in upstream_ref

packit/cli/copr_build.py, tests/integration/test_copr_build.py, tests/spellbook.py
- Fix picking correct COPR project name for CLI.
- Fixes: https://github.com/packit/packit/issues/941
=> Fix copr project name for CLI

packit/api.py, tests/data/cockpit-ostree/packit.yaml, tests/data/sourcegit/source_git/.packit.yaml, tests/integration/test_update.py
TODO: fix the tests (blocked by #962 )
Fixes #924
=> Don't leave distgit repository dirty after exc

packit/config/package_config.py, packit/schema.py, tests/unit/test_package_config.py
=> Add sync_changelog config option to missing places

packit/config/job_config.py, tests/unit/test_config.py
=> Add build to default jobs

ci.fmf
[works with new TF](http://artifacts.dev.testing-farm.io/ac8f7ac4-61af-42e8-8c43-3613f68923e9/work-full5aC5Qy/ci/test/build/full/execute/data/script-00/out.log)
=> [ci.fmf] there's no git-source/ in 'new' Testing Farm

Dockerfile, Dockerfile.tests
=> [Dockerfile(s)] FROM fedora:31 -> usercont/base

tests/data/dist_git/beer.spec, tests/data/sourcegit/source_git/fedora/beer.spec, tests/integration/test_upstream.py
=> Test suite fixes for EPEL 8

tests/unit/test_copr_helper.py
=> Add tests for copr_settings_url after #1043

README.md
I fixed what it needed to be fixed.
I chose to include in `installation` parts both :
- `bash` command
- link to docs
Tell me if some points need to be removed or updated.
Fixes #1045
=> update on readme.md

packit/utils/repo.py, tests/conftest.py, tests/data/upstream_git_with_multiple_sources/beer.spec, tests/integration/conftest.py, tests/integration/test_build.py, tests/integration/test_copr_build.py, tests/integration/test_local_project.py, tests/integration/test_source_git.py, tests/integration/test_source_git_generator.py, tests/integration/test_update.py, tests/integration/test_upstream.py, tests/integration/test_using_cockpit.py, tests/spellbook.py
After removal of `master` branch from dist-git, the tests are trying to
pull non-existing branch.
Fixes #1097
=> Fix branches in dist-git in tests

packit/cli/build.py
Packit build command will use aliases for koji-target.
Resolves #840
=> Implement koji-target aliases for build command

packit/config/config.py, packit/config/job_config.py, packit/config/package_config.py, packit/config/sync_files_config.py, packit/schema.py, tests/unit/test_config.py, tests/unit/test_package_config.py
=> Remove marshmallow 2 support

.packit.yaml
Requires ogr in epel-8 (similar PR in OGR: https://github.com/packit/ogr/pull/503)
=> Enable epel8 and re-enable testing-farm for rawhide

packit/config/aliases.py
=> Update the hardcoded alias dictionary

packit/cli/create_update.py
=> Add password prompt to create-update

files/tasks/rpm-test-deps.yaml, tests/functional/test_local_build.py
=> [files/tasks/rpm-test-deps.yaml] install rpmautospec-rpm-macros on Fedora only

packit/api.py, packit/config/common_package_config.py
Needed for packit/packit-service#1023
=> [sync_from_downstream] add option to sync only specfile

.github/workflows/build-and-push.yml
https://github.com/packit/packit/pull/1159#issue-591796833
=> Actions/workflow: don't build & push packit-tests image

packit/cli/init.py, packit/cli/utils.py, packit/constants.py, packit/exceptions.py, packit/source_git.py, packit/utils/repo.py, tests/integration/test_source_git_generator.py, tests/unit/test_source_git_generator.py
8: dist-git is in git.centos.org
9: dist-git is in gitlab.com/redhat/centos-stream
Fixes https://github.com/packit/packit/issues/1174
This contains more UX improvements.
~~Currently blocked on: https://github.com/rebase-helper/rebase-helper/issues/848~~
=> init: enable using Stream 9 dist-git as a source

packit/cli/packit_base.py, packit/config/config.py, packit/schema.py, tests_recording/testbase.py
dry_run is set in many places, but never tested.
Signed-off-by: Ben Crocker <bcrocker@redhat.com>
=> Remove dry-run

packit/config/aliases.py, tests/unit/test_config_aliases.py
Resolves: packit/packit-service#986
=> Introduce fedora-latest alias

CHANGELOG.md, packit.spec
=> Packit 0.28.0

packit/api.py, tests/integration/test_push_updates.py
=> Response from Bodhi update request is in 'update' key

packit/copr_helper.py, tests/integration/test_copr_build.py
We need to remove the ones that are not needed (=set) anymore.
Fixes: #1091
=> Do not append new chroots to the existing ones for Copr project

packit/constants.py, packit/source_git.py, tests/integration/test_source_git_generator.py
=> Make packit init to define sources in packit.yaml

packit/source_git.py, tests/integration/test_source_git_generator.py
=> init: don't commit dist-git sources which are in the lookaside cache

CHANGELOG.md, README.md, packit/config/common_package_config.py, tests/integration/test_source_git.py, tests/integration/test_update.py, tests/unit/test_cli.py
=> More propose-update -> propose-downstream

.packit.yaml, CHANGELOG.md, packit.spec
=> Release 0.30.0

CHANGELOG.md, packit.spec
=> Release 0.30.1

packit/cli/propose_downstream.py
=> Fix help for propose-downstream

CHANGELOG.md, packit.spec
=> Release 0.31.0

packit/cli/init.py, packit/cli/packit_base.py, packit/cli/source_git.py, packit/cli/source_git_init.py
... to group source-git related commands `init` and `update-dist-git`.
Related to #1250.
=> Create a 'source-git' subcommand

packit/upstream.py, tests/integration/test_upstream.py, tests/unit/test_upstream.py
=> Refactor Upstream class

_packitpatch, files/local-tests-requirements.yaml, files/tasks/centpkg.yaml, packit/api.py, packit/cli/source_git_init.py, packit/distgit.py, packit/pkgtool.py, packit/source_git.py, packit/specfile.py, packit/utils/__init__.py, tests/data/upstream_git/beer.spec, tests/integration/test_source_git_generator.py, tests/integration/test_spec.py
=> Update the source-git format produced by 'source-git init'

packit/schema.py
=> Add use_internal_tf to the schema of JobMetadata

packit/api.py, packit/config/common_package_config.py, tests/unit/test_package_config.py
Fixes https://sentry.io/organizations/red-hat-0p/issues/2466591748/?project=1767823&query=is%3Aunresolved
=> Add from_downstream argument for getting SyncFilesItem for specfile

CHANGELOG.md, packit.spec
Signed-off-by: Ben Crocker <bcrocker@redhat.com>
=> Release 0.33.1

packit/distgit.py, packit/local_project.py, packit/status.py, tests/integration/test_create_update.py, tests/integration/test_push_updates.py
=> Refactor DistGit and remove some unnecessary workarounds

packit/config/aliases.py
=> Update backup aliases

Dockerfile.tests, tests/integration/test_source_git_init.py, tests/integration/test_spec.py
Various fixes to make tests pass on EPEL8.
=> Fix tests on EPEL8

files/tasks/centpkg.yaml, files/tasks/rpm-test-deps.yaml
the new 0.10.5 causes some regressions
=>  tests image: install python3-flexmock-0.10.4

packit/command_handler.py
Related to packit/packit-service#1209
---
N/A
=> Don't init VolumeSpec if given env var isn't set

packit/upstream.py, tests/data/snapd/packaging/fedora/fix-spec, tests/integration/test_using_examples.py
so people can utilize it in the action
requested by https://github.com/oamg/leapp-repository/pull/671
TODO:
=> fix-spec: provide packit's %release content

packit/upstream.py, tests/unit/test_upstream.py
=> Fix regex for RPM files

CHANGELOG.md, packit.spec
=> Prepare release 0.41.0

packit/config/aliases.py
=> Add missing 'f' to a string

packit/config/job_config.py
This is the easiest solution how to do this.
See packit/research#123 for more information.
Related to packit/packit-service#55
Merge before TBD
---
N/A (will be mentioned in service)
=> Add downstream Koji build as new type

packit/constants.py, packit/utils/source_script.py, tests/unit/test_utils.py
=> Copr source script

.packit.yaml
=> Trigger koji build for new dist-git commits

CHANGELOG.md, packit.spec
🎉 🥳 🪅
Changelog was shamefully stolen from @FrNecas in https://github.com/packit/packit.dev/pull/365
=> 0.43.0 release

.pre-commit-config.yaml, setup.cfg
Add flexmock dependency to setup.cfg.
mergeit
=> Add flexmock to testing dependencies

CHANGELOG.md, packit.spec
=> Release 0.44.0

packit/actions.py, packit/api.py, packit/base_git.py, packit/cli/types.py, packit/config/package_config.py, packit/local_project.py, packit/schema.py, packit/source_git.py, packit/specfile.py, packit/sync.py, packit/upstream.py, packit/utils/repo.py, tests/conftest.py, tests/integration/test_patches.py, tests/integration/test_source_git.py, tests/unit/conftest.py, tests_recording/test_status.py
I've used the [Sourcery](https://sourcery.ai/) PyCharm plugin to improve some parts of the code a bit.
Feel free to postpone merging so other's don't need to rebase this.
---
N/A
=> Apply code suggestions by Sourcery

packit/cli/prepare_sources.py, packit/cli/types.py, packit/local_project.py, packit/utils/source_script.py, tests/unit/test_utils.py
Add target_branch argument for prepare-sources command and use it when
merging PR when preparing sources.
---
=> Use target_branch argument for prepare-sources command for merging PR

packit/config/job_config.py
Merge before: packit/packit-service#1332
---
N/A
=> Add a new job type for automatically created Bodhi updates

packit/api.py, packit/config/common_package_config.py, packit/config/job_config.py, packit/config/package_config.py, packit/schema.py, tests/unit/conftest.py, tests/unit/test_api.py, tests/unit/test_package_config.py
=> Disable creating of the sync note file (aka README.packit)

packit/config/aliases.py
=> Update aliases, Fedora Linux 36 was branched

packit/source_git.py, tests/integration/test_source_git_init.py
=> Use the new 'files_to_sync' config key in source-git init

packit/cli/prepare_sources.py, packit/cli/utils.py, packit/utils/source_script.py, tests/unit/test_utils.py
=> [prepare-soures] use index of job config instead of json

.packit.yaml, packit/constants.py, tests/unit/test_utils.py
TODO:
We are now building SRPMs for Packit's own PRs in Copr. For more info see packit/packit#1490 and https://packit.dev/docs/configuration/#srpm_build_deps
=> packit.yaml: build our SRPM in Copr

plans/rpmlint.fmf
Let's run rpmlint on our spec file - we already do this in ogr.
=> new tmt plan: rpmlint packit.spec

packit/config/package_config.py, packit/utils/source_script.py, tests/unit/test_utils.py
=> Multiple fixes to improve using source script

packit/config/job_config.py, packit/config/package_config.py, packit/schema.py
=> Add job identifier to the config schema

CHANGELOG.md, packit.spec
=> Prepare release 0.47.1

packit/distgit.py, packit/utils/bodhi.py
Interactions with Bodhi should be now more reliable when creating Bodhi updates.
=> Make the work with Bodhi more robust

CHANGELOG.md, packit.spec
=> Release 0.48.0

.github/PULL_REQUEST_TEMPLATE.md
Add todo-items, to create or update the tests, adjust doc-strings and
update user docs on packit.dev.
=> Add a todo-items in the PR template for frequent tasks

packit/api.py
=> fix: Specify the return types for PackitAPI properties

packit/distgit.py, tests/integration/test_using_cockpit.py, tests/unit/test_dg.py, tests_recording/test_data/test_api/ProposeUpdate.test_comment_in_spec.yaml
=> fix(dg): check for user when checking existing pr

files/tasks/centpkg.yaml, files/tasks/generic-dnf-requirements.yaml, files/tasks/install-packit-service.yaml, files/tasks/install-packit.yaml, files/tasks/ogr.yaml, files/tasks/packit-service-requirements.yaml, files/tasks/project-dir.yaml, files/tasks/python-compile-deps.yaml, files/tasks/requre.yaml, files/tasks/rpm-test-deps.yaml, files/tasks/sandcastle.yaml, packit/local_project.py
=> Allow to pass --force to LocalProject.fetch()

packit/config/aliases.py
=> Update default aliases as Fedora 34 goes EOL

packit/api.py, packit/base_git.py, packit/distgit.py, tests/integration/conftest.py, tests/integration/test_source_git_synch_push.py, tests/integration/test_using_cockpit.py
It creates a source-git PR when called and
new commits in dist-git are found.
Implements: https://issues.redhat.com/browse/PACKIT-2356
=> Add sync_push

.packit.yaml
Until packit/packit-service#1562 is fixed
TODO: revert back this commit when packit/packit-service#1562 is fixed
=> Skip SRPM builds in rawhide

.zuul.yaml, files/install-requirements-git.yaml, files/install-requirements-pip.yaml, files/tasks/packit-service-requirements.yaml, files/tasks/specfile.yaml
A follow-up to packit/deployment#367.
This fixes reverse dependency tests.
=> Install community.general Ansible collection

packit/utils/upstream_version.py, tests/unit/test_utils.py
This reverts commit 1d50a4a8fd650d90b7aeecd842dc4957b22305db.
=> Revert "Switch to release-monitoring.org API v2"

.github/workflows/prepare-release.yml, scripts/changelog.py, scripts/prepare_release.py, scripts/prepare_release_requirements.txt
Co-authored-by: Laura Barcziová <lbarczio@redhat.com>
Co-authored-by: Nikola Forró <nforro@redhat.com>
Co-authored-by: František Lachman <flachman@redhat.com>
=> Create a workflow to prepare a release

.github/workflows/do_release.yml
Add action to automatically create a release
=> Add action to automatically create a release

packit/config/package_config.py, tests/unit/test_package_config.py
Because the default of 'downstream_package_name' was set in the
configuration dict to the name of the repo _before_ setting the default
for 'specfile_path', the default for the later was always
'{downstream_package_name}.spec', regardless if
'downstream_package_name' was set by the user in 'packit.yaml' or was
set by the code to 'repo_name'.
Change the order of setting these two defaults to fix this issue.
Additionally, use 'setdefault' when appropriate in
'PackageConfig.get_from_dict()'.
Fixes #1757.
TODO:
Merge after #1727.
Fixed an issue due to which the repository was never searched for a specfile if 'specfile_path' was not specified, and 'specfile_path' was always set to '<repo_name>.spec'.
=> Fix setting the default value of 'specfile_path'

packit/distgit.py, packit/status.py, packit/utils/koji_helper.py, tests/unit/test_utils.py
Merge before packit/packit-service#1729
=> Add methods to get build dicts from KojiHelper

files/tasks/generic-dnf-requirements.yaml
=> Install bodhi client v6

packit/cli/builds/copr_build.py, packit/config/aliases.py, packit/copr_helper.py, tests/integration/test_copr_build.py, tests/unit/test_config_aliases.py, tests/unit/test_copr_helper.py
I was naive: the previous implementation couldn't work
please read commit messages for details
TODO:
Fixes #1429
=> fix chroot-specific configuration

tests_recording/test_data/test_api/ProposeUpdate.test_changelog_sync.yaml, tests_recording/test_data/test_api/ProposeUpdate.test_comment_in_spec.yaml, tests_recording/test_data/test_status/TestStatus.test_dowstream_pr.yaml
=> fix(tests,ogr): update the dist-git queries from ogr

.zuul.yaml
until we figure out why they time out on f36 & f37
Related to #1831
=> Temporarily run packit-tests on f35

packit/config/common_package_config.py, packit/schema.py, tests/unit/test_package_config.py
First step towards https://github.com/packit/packit-service/issues/1627
TODO:
=> Add option to pass free-form TF parameters

packit/cli/builds/local_build.py, packit/upstream.py, tests/functional/test_local_build.py
TODO:
Friday issue, so I can test the Bodhi permissions tomorrow :)
Fixes #1661
You can now use `--srpm` option with the `packit build locally` CLI command.
=> feat(cli,build): implement local build from SRPM

packit/utils/changelog_helper.py, tests/integration/test_changelog_helper.py
Fixes #1847
TODO:
Packit now provides `PACKIT_PROJECT_VERSION`  environment variable when running `changelog-entry` action.
=> Provide version env var in changelog-entry action

.github/workflows/build-and-push.yml
Enable manual retriggering of github action.
=> Enable manual retrigger of rebuild and push images

packit/api.py, packit/base_git.py, packit/status.py, tests/unit/conftest.py
TODO:
- [N/A] Update or write new documentation in `packit/packit.dev`.
Fixes: https://red-hat-it.sentry.io/issues/4063561048
=> Use 'git switch' for switching branches in PackitRepositoryBase.switch_branch() 

packit/config/common_package_config.py, packit/config/job_config.py, packit/config/package_config.py, packit/schema.py, tests/unit/test_config/test_config.py
Fix Job identifier after deserialization. 
Related with monorepo packit-service refactoring. 
Merge before packit/packit-service#2014
=> Views serialization

packit/config/package_config.py, tests/unit/test_config/test_config.py
=> Create JobConfigView for every JobConfig in monorepo

Makefile
=> ci: add test coverage to pytest

.pre-commit-config.yaml
Related packit/pre-commit-hooks#37, packit/pre-commit-hooks#38
=> Dogfood our validate-config pre-commit hook

packit/vm_image_build.py, tests/unit/test_image_builder.py, tests_recording/test_image_builder.py
https://github.com/packit/packit/pull/1965 is bugged, I cannot push there, hence created another
Contains:
* image builder: add methods for cloning
* image builder: enable doing launch requests too
* image builder: raise exc when cannot obtain token
TODO:
- the cloning is for Franta so he can share an image with Miro
No user-visible change here.
=> Image Builder improvements (take 2)

packit/config/job_config.py, packit/schema.py, tests/unit/test_config/test_config.py
Adds labels to schema for packit-service triggering subset of jobs by specific label
=> Add labels to schema

.github/workflows/sonarqube.yml, sonar-project.properties
https://sonarqube.corp.redhat.com/dashboard?id=Packit
=> New Action: SonarQube scan

Containerfile, Containerfile.tests, files/install-requirements-rpms.yaml, files/local-tests-requirements.yaml
Related to packit/deployment#410
=> Use CentOS Stream9 as a base image

packit/cli/source_git_init.py, packit/source_git.py
=> Improve messages for missing `%autosetup` case.

packit/command_handler.py, packit/config/config.py, packit/schema.py
Related to packit/sandcastle#190
=> feat(mpp): pass appcode and storage class to Sandcastle

packit/config/config.py
Related to https://github.com/packit/packit-service/issues/1907.
Merge before https://github.com/packit/packit-service/pull/2137.
=> Allow git project to be None if requested

packit/upstream.py, packit/utils/changelog_helper.py
Related to https://github.com/packit/packit-service/issues/1907.
Merge before https://github.com/packit/packit-service/pull/2137.
=> Handle upstream git_project being None in pull_from_upstream workflow

packit/constants.py, packit/distgit.py, tests/unit/test_dg.py
=> fix(dg): do not raise for existing Bodhi updates

packit/api.py, packit/base_git.py, tests/unit/test_base_git.py
Fixes packit/packit-service#1956
Merge before packit/packit-service#2166
=> Make dg repo accessible by an action

pyproject.toml
Without these make check is broken
=> Add missing testing dependencies pytest-cov & pytest-timeout

packit/__init__.py, packit/api.py, packit/cli/packit_base.py, pyproject.toml, tests/unit/test_cli.py, tests/unit/test_utils.py
https://github.com/packit/ogr/issues/798#issuecomment-1706786873
TODO:
=> Replace pkg_resources (setuptools) with importlib

packit/constants.py, tests/unit/test_api.py
=> feat: remind maintainers to run manual checks

packit/api.py, packit/command_handler.py, tests/unit/conftest.py, tests/unit/test_api.py, tests/unit/test_base_git.py
TODO:
Fixes https://github.com/packit/packit-service/issues/1956
Merge after packit/sandcastle#197
Merge before packit/packit.dev#743
=> Fix repos paths inside sandcastle and copy both

.gitattributes, files/tasks/rpm-test-deps.yaml, plans/full.fmf, tests/data/dg-ogr/.packit.yaml, tests/data/dg-ogr/python-ogr.spec, tests/full.fmf
Related to https://github.com/packit/ogr/pull/808.
=> Remove unneeded references to setuptools_scm_git_archive and update ogr test files

packit/base_git.py
Related to packit/packit-service#2181
N/A
=> Log detailed info about sources to download

pyproject.toml
=> Add mypy min  version

packit/cli/utils.py, packit/config/common_package_config.py, packit/constants.py, packit/dist_git_instance.py, tests/integration/test_get_api.py, tests/unit/config/test_package_config.py, tests/unit/utils/test_dist_git_instance.py
(or generally any git-forge that can share upstream/downstream)
TODO:
Fixes #2118
Fixes #2121
We have fixed an issue that prevented you from running the jobs on the GitLab.com due to failing resolution of the upstream/downstream relationship for the cloned project.
=> Resolving the upstream/downstream dilemma on GitLab.com

packit/constants.py, tests/unit/test_api.py
=> Fix dist-git PR instructions

packit/config/aliases.py
Update some aliases defined in ALIASES fallback constant.
TODO:
Fixes
Related to
Packit now supports automatic ordering of ☕ after all checks pass.
=> Update ALIASES in aliases.py

packit/api.py, packit/distgit.py, packit/pkgtool.py, tests/integration/test_build.py
Needed for packit/packit-service#1889
N/A
=> Return stdout from running Koji build command

packit/pkgtool.py, tests/integration/test_build.py
Fixes https://red-hat-it.sentry.io/issues/4609196947/?project=1767823&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=1&utc=true
=> Return output from running Koji build command

packit/distgit.py, tests/unit/test_dg.py
Fixes https://github.com/packit/packit/issues/2129.
=> Ignore invalid sources in upstream_archive_names

packit/base_git.py, packit/constants.py, packit/utils/upstream_version.py, tests/unit/utils/test_upstream_version.py
Fixes https://github.com/packit/packit/issues/2185.
=> Set HTTP request timeouts

packit/api.py, packit/distgit.py
Related to packit/packit-service#1890
N/A
=> Return Bodhi update alias and URL when creating one

packit/api.py, packit/upstream.py, tests/integration/test_upstream.py
Related to https://github.com/packit/packit/issues/2184.
=> Allow to set upstream git ref to identify correct most recent tag

packit/copr_helper.py, tests/unit/test_copr_helper.py
Fixes packit/packit-service#2262
We have fixed a bug in handling chroot-specific configuration once the chroots themselves are updated.
=> Chroot-specific config update fix

packit/config/aliases.py, tests/unit/test_api.py
=> Update fallback ALIASES in aliases.py

packit/config/package_config_validator.py
=> [validate-config] warn about duplicated scratch builds

packit/config/common_package_config.py, packit/schema.py, tests/unit/config/test_package_config.py
TODO:
Related to packit/packit-service#2266
*Release notes should be included in the Packit Service changes.*
=> feat(config): add status_name_template

packit/config/common_package_config.py, packit/schema.py, tests/unit/config/test_config.py
Needed for packit/packit-service#2312
N/A
=> Add allowed_builders to configuration schema

packit/config/aliases.py, packit/utils/decorators.py, packit/utils/monitoring.py
=> Count the number of times fallback values for aliases were used

packit/config/common_package_config.py, packit/schema.py
Related to https://github.com/packit/packit-service/issues/2377.
=> Add sidetag_group config option for koji_build and bodhi_update

packit/actions_handler.py, packit/api.py, packit/base_git.py, packit/distgit.py, packit/upstream.py, packit/utils/changelog_helper.py, tests/integration/test_actions.py, tests/integration/test_base_git.py, tests/integration/test_changelog_helper.py, tests/integration/test_upstream.py, tests/unit/test_base_git.py, tests/unit/test_upstream.py
=> Move actions handling to a separate class

packit/api.py, packit/distgit.py, tests/integration/test_update.py
=> Do not try to upload git-tracked files to lookaside cache

packit/utils/koji_helper.py, plans/full.fmf, plans/session-recording.fmf, tests/unit/utils/test_koji_helper.py
Related to https://github.com/packit/packit-service/issues/2378.
=> Allow to list builds tagged into a Koji tag

packit/cli/dist_git_init.py
Fixes https://github.com/packit/packit/pull/2308
=> Get upstream_git_url from command only when the command is set

packit/cli/scan_in_osh.py
Based on [the review for packit.dev](https://github.com/packit/packit.dev/pull/887#discussion_r1609765473)
=> Update scan-in-osh CLI help message

packit/local_project.py, tests/unit/test_local_project.py
Needed for packit/packit-service#2449
N/A
=> LocalProject and builder improvements

packit/config/common_package_config.py, packit/config/job_config.py, packit/utils/koji_helper.py, tests/unit/utils/test_koji_helper.py
Related to https://github.com/packit/packit-service/issues/2378.
=> Changes needed for triggering Koji builds by Koji tag events

packit/config/common_package_config.py, packit/config/job_config.py, packit/schema.py
Related to https://github.com/packit/packit-service/issues/2378.
=> Move job config options to the proper place

packit/config/common_package_config.py, packit/schema.py
Related to packit/packit-service#2454
N/A
=> Add config flag for running scans after Copr builds

packit/config/common_package_config.py, packit/schema.py
Mention explicitly OSH in the name, as suggested by @siteshwar in https://github.com/packit/packit/pull/2356#discussion_r1684131691
N/A
=> Rename config option for scanning functionality

packit/config/common_package_config.py, packit/schema.py
Related to https://github.com/packit/packit-service/issues/1943.
Merge before https://github.com/packit/packit-service/pull/2470.
=> Add `sync_job_statuses` config option

packit/distgit.py
Related to https://github.com/packit/packit-service/issues/2379.
=> Allow to create Bodhi update from a sidetag

packit/api.py
Related to https://github.com/packit/packit-service/issues/2379.
=> Add missing `sidetag` argument to `create_update()` API

packit/distgit.py, pyproject.toml
=> Drop python fedora import

packit/utils/koji_helper.py, tests/unit/utils/test_koji_helper.py
Related to https://github.com/packit/packit-service/issues/2468.
=> KojiHelper updates

files/tasks/rpm-test-deps.yaml, plans/full.fmf, pyproject.toml
Merge after https://github.com/packit/packit-service/pull/2510
=> Pin down old DeepDiff

tests/integration/test_update.py
Related to https://github.com/packit/packit-service/issues/2461, https://github.com/packit/specfile/pull/397.
=> Capture specfile debug logs in selected tests

packit/base_git.py, packit/config/config.py, packit/schema.py, tests/unit/conftest.py, tests/unit/test_base_git.py
Fixes packit/packit-service#2514
N/A
=> Enable setting default macro definitions for specfile parsing

packit/api.py, tests/unit/test_api.py
Related to https://github.com/packit/packit-service/issues/2537.
=> Warn that merging a dist-git PR may not trigger configured Koji builds

packit/api.py, packit/distgit.py
Related to https://github.com/packit/packit-service/issues/2497.
=> Make it possible to edit existing Bodhi update

packit/api.py, tests/unit/test_api.py
Related to https://github.com/packit/packit-service/issues/2537.
=> Check for configured `koji_build` job on service side

packit/upstream.py
Based on https://github.com/packit/packit/issues/2235#issuecomment-2388976802
N/A
=> Explicitly mention source of upstream version in logs

packit/distgit.py, packit/pkgtool.py, tests/integration/test_distgit.py
Related to packit/packit-service#2503
N/A
=> Implement getting of NVR for dist-git repo

packit/config/package_config_validator.py, packit/constants.py
Fixes #88
TODO:
Fixes #88
`packit validate-config` now checks for the existence of downstream package.
=> Validate existence of downstream package

files/tasks/rpm-test-deps.yaml, packit/utils/koji_helper.py, plans/full.fmf, pyproject.toml
Related to https://github.com/packit/packit-service/issues/2576.
=> Return Koji task ID of a successful tagging request

packit.spec
Sync of downstream change: https://src.fedoraproject.org/rpms/packit/pull-request/1402
=> Remove outdated EPEL 9 workaround

packit/utils/koji_helper.py, tests/integration/test_create_update.py, tests/unit/utils/test_koji_helper.py
Fixes https://github.com/packit/packit-service/issues/2608.
=> If Koji session becomes invalid, open a new one and try again

Containerfile, Containerfile.tests, files/tasks/rpm-test-deps.yaml
Related to https://github.com/packit/deployment/issues/613.
Merge after https://github.com/packit/deployment/pull/622.
=> Use Fedora-41-based base image

packit/api.py, packit/upstream.py, tests/integration/test_update.py, tests/unit/test_api.py
Fixes #2477.
Related to #2519.
=> Reload spec files after all actions that could have changed them

packit/upstream.py, tests/integration/test_upstream.py
Related to https://github.com/packit/packit/pull/2521.
=> Reload upstream spec file after create-archive

packit/copr_helper.py
=> Implement cancelling of Copr builds

files/tasks/rpm-test-deps.yaml, packit/config/aliases.py, tests/conftest.py, tests/full.fmf, tests/integration/test_using_examples.py, tests/spellbook.py, tests/unit/config/test_config_aliases.py, tests/unit/conftest.py, tests/unit/test_propose_downstream.py
Related to https://github.com/packit/packit/issues/2438, https://github.com/rpm-software-management/fedora-distro-aliases/pull/27.
=> Get dist-git branch names from Bodhi release metadata

packit/config/aliases.py
Fixes https://red-hat-it.sentry.io/issues/6363489274/?project=1767823.
=> Return lists from `get_aliases()`, order matters

packit/config/common_package_config.py, packit/schema.py
Related to packit/packit-service#2748
N/A
=> Add use_target_repo_for_fmf_url field to common config options

packit/utils/koji_helper.py, tests/unit/utils/test_koji_helper.py
Merge before https://github.com/packit/packit-service/pull/2760.
=> Implement `KojiHelper.get_branch_from_target_name()`

packit/cli/builds/koji_build.py
Koji builds started by `packit build` are now executed in parallel and watched till completion, except when `--nowait` is provided. This improves efficiency by reducing the overall build time when multiple targets or branches are specified.
Changes:
- Use `ThreadPoolExecutor` to start builds concurrently.
- Ensure that when `--nowait` is passed, the command exits immediately after triggering the builds.
- Improve logging for better visibility of parallel builds.
Fixes #903
Packit CLI now submits Koji builds in parallel.
=> koji: run builds in parallel and respect --nowait flag

.github/workflows/pypi-publish.yml
This reverts commit f4c1b274d09192918042b2f3b0a73c1ca78a724b.
=> Revert "ci(pypi): use ‹fetch-tags› from ‹actions/checkout›"

packit/cli/builds/copr_build.py
Part of #1762
TODO:
Fixes #1762
Related to
=> feat(cli): Add Copr configuration requirement note to CLI help.

plans/full.fmf, plans/main.fmf, plans/rpmlint.fmf, plans/session-recording.fmf, plans/smoke.fmf, tests/smoke.fmf, tests_recording/main.fmf, tests_recording/test_data/test_api/ProposeUpdate.test_changelog_sync.yaml
https://github.com/packit/ogr/commit/0eca98d20d317c2a241e0eb602b4bab8edb07484 made some changes that require additional requests.
=> Update tests_recording data

.github/workflows/prepare-release.yml
In specfile this change fixed the issue: https://github.com/packit/specfile/actions/workflows/prepare-release.yml
=> Use latest version of the create-pull-request action

packit/cli/utils.py
=> Fix typo in error message

packit/schema.py
=> Fix validation of trigger in job configs

packit/api.py
Subtle detail sneaked in with #2589, not all variables that we set are paths, e.g., there are also package names. Trying to make those paths in Sandcastle relative to the current working directory is impossible, duh, they are just names, not actual paths.
Therefore process the paths separately, also factor out in the process, so it cannot be so easily overlooked (for the full list of people that didn't notice, have a look below lol).
As for the specfile path itself, that was a cause for this change, I am not sure what is the expected behavior… Leaving it «as is» for now, docs suggest it should be relative path within the upstream repo, but we're talking about ‹sync-release› actions here, so there's also ‹pull-from-upstream› that doesn't require an actual upstream repo…
We can change it …
=> fix(env): do not treat all env variables as paths
