packit/packit

packit/distgit.py
After installation of latest packit, it tracebacks on this:
```
Traceback (most recent call last):
File "/root/.local/bin/packit", line 11, in <module>
load_entry_point('packitos==0.1.dev240+gbbd7a9d', 'console_scripts', 'packit')()
File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
def create_branch(self, branch_nane: str, base: str = "HEAD"):
File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
return ep.load()
File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
return self.resolve()
File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
module = …
```
=> fix identation

packit/api.py, packit/bot_api.py, packit/cli/packit_base.py, packit/cli/watch_sg_pr.py, packit/distgit.py, packit/local_project.py, packit/upstream.py
- Improve LocalProject.
- Add back methods for patching.
- Fix watch-sg-pr CLI.
- Fix APIs for syncing PRs.
Using the old methods from Transformator, we should look at rebase-helper in the future.
=> Fix watching upstream PRs

README.md, recipe.yaml
Add to README.md required package `fedpkg`.
On clean system, it is not installed by default.
=> Fixes #78 Fix required package

docs/configuration.md, docs/update.md, packit/constants.py
This updates documentation and adds the ability to read also `packit.yaml` file.
=> Fixes #113 Packit is able to read packit.yaml

packit/api.py, packit/cli/create_update.py, packit/cli/packit_base.py, packit/constants.py, packit/distgit.py, setup.cfg, tests/data/dist_git/beer.spec, tests/integration/test_create_update.py, tests/spellbook.py
TODO:
* ~~docs (for both build and update)~~ let's do docs in 0.2.0 release PR
I created this update: https://bodhi.fedoraproject.org/updates/FEDORA-2019-0c53f2476d
by running `packit --debug create-update --dist-git-branch f30`
=> implement create-update command

packit/cli/types.py, packit/cli/utils.py, packit/config.py, packit/local_project.py, tests/unit/test_local_project.py
- Be able to set branch from option in LocalProjectParameter.
- Add offline mode to LocalProject.
- Use PACKIT prefix pro env variables used instead of cli options.
-----
=> Offline LocalProject and some CLI fixes

packit/cli/build.py, packit/cli/create_update.py, packit/cli/update.py, packit/cli/utils.py
- Use get_packit_api in propose-update CLI function.
- Use get_packit_api in create-update CLI function.
- Use get_packit_api in build CLI function.
- Add helper function for loading config and PackitAPI.
---
It first tries to load `package_config` from the local directory:
- it is useful when you would like to use packit without config in the repo. (Newcomers can try packit more easily.)
- Make it rather "the last choice"? (If no config can be found in the repo, try the local one.)
=> Helper function to get PackitAPI in CLI

packit/api.py, packit/cli/sourcegit_to_dist_git.py, packit/cli/sourcegit_to_srpm.py, packit/cli/update.py, packit/cli/utils.py, packit/config.py, packit/upstream.py
- Add local-content option to propose-update. (off by default)
- Allow using local-content in release-update.
- Fix non-branch ref in upstream.
- Correct calls of get_local_package_config.
- Allow *args in get_local_package_config.
----
You can now use following worflow:
```bash
git clone https://my.best/repo.git
cd repo
g checkout 0.1.0
packit propose-update --local-content
```
=> Allow preserving local content on propose-update

packit/api.py, packit/cli/update.py
- Upload new-sources if we have old sources files.
- Add --force-new-sources option to propose-update.
- Add --force-new-sources option to sync_release.
Resolves: #161
=> new-sources fixes

.packit.yaml, Jenkinsfile, packit.spec, packit/api.py, packit/cli/packit_base.py, packit/cli/srpm.py, packit/config.py, packit/upstream.py, tests/conftest.py, tests/data/upstream_git/.packit.json, tests/functional/test_srpm.py, tests/integration/test_api.py, tests/integration/test_upstream.py, tests/spellbook.py, tests/unit/test_cli.py
Built on top of #146 so this one is easier to review.
TODO:
* [tito uses](https://github.com/dgoodwin/tito/blob/master/src/tito/builder/fetch.py#L117) a ton of magic code (regexes, weird ifs) and changes spec on its own, no bumpspec; [here is a code to generate srpm](https://github.com/dgoodwin/tito/blob/master/src/tito/builder/main.py#L200), I'd say our is better
* rebase-helper has a different use case: it knows everything: spec, sources, version, so [it's trivial](https://github.com/rebase-helper/rebase-helper/blob/master/rebasehelper/srpm_build_tools/rpmbuild_tool.py) to construct the srpm for rebase-helper
* [rdopkg uses fedpkg to create a srpm](https://github.com/softwarefactory-project/rdopkg/blob/a6e6497bfcff0ac4940b3dc28592c05d028a04d7/rdopkg/actions/distgit/actions.py#L997)
* …
=> implement srpm command

packit/distgit.py
```
Bodhi update FEDORA-2019-b72add0dcd:
- https://bodhi.fedoraproject.org/updates/FEDORA-2019-b72add0dcd
- autokarma: True
- stable_karma: 3
- unstable_karma: -3
```
```
Munch({'title': 'packit-0.1.0-1.fc30', 'autokarma': True, 'stable_karma': 3, 'unstable_karma': -3, 'requirements': '', 'require_bugs': True, 'require_testcases': True, 'display_name': '', 'notes': 'New upstream release: 0.1.0\n\n----\n\nInitial version: 0.0.1', 'type': 'enhancement', 'status': 'pending', 'request': 'testing', 'severity': 'unspecified', 'suggest': 'unspecified', 'locked': False, 'pushed': False, 'critpath': False, 'close_bugs': True, 'date_submitted': '2019-03-15 09:52:51', 'date_modified': None, 'date_approved': None, 'date_pushed': None, 'date_testing': None, 'date_stable': None, 'alias': …
```
=> Better bodhi output

packit/upstream.py
Fixes: https://github.com/packit-service/ogr/pull/35#issuecomment-473911368
=> srpm: rpmbuild respects locale and translates its output

.gitignore, README.md, docs/sync-from-downstream.md, packit/api.py, packit/cli/packit_base.py, packit/cli/sync_from_downstream.py, packit/local_project.py, packit/upstream.py, packit/utils.py, tests/conftest.py, tests/integration/test_build.py, tests/integration/test_create_update.py, tests/integration/test_update.py, tests/unit/test_local_project.py, tests/unit/test_utils.py
The pull request adds support for syncing `synced_files` from downstream into upstream
=> Sync files from downstream into upstream

packit/distgit.py
This fixes the case when `PagureService` is using default url instead of
url used by `DistGit` object.
=> Give dist-git url to PagureService

packit/local_project.py, tests/unit/test_local_project.py
=> Refactor the LocalProject

Makefile, recipe.yaml
```
PLAY RECAP ******************************************************************************************************************************************************************
packit-20190322-142125055598-cont : ok=12   changed=9    unreachable=0    failed=0
Getting image source signatures
Copying blob sha256:97b94d418dac4ec6da11f188c162831ddf674b08c496d1fd9ebaf5d497f94e08
Copying blob sha256:3f4f2e0cf35341ceb2100eeddb7d14f35cbd3043334048f11d9e18635700c9a4
Copying config sha256:7cdd0871485af8f0b838de92590e05ed0d58965e9764e9c7b5d0251a2fee22ee                                                                                      
Writing manifest to image destination
Storing signatures
7cdd0871485af8f0b838de92590e05ed0d58965e9764e9c7b5d0251a2fee22ee
Image 'packit' was built successfully \o/ …
```
=> recipe: set metadata in the playbook

packit/cli/packit_base.py, packit/config.py
This mostly piggybacks off package config parsing. Token reading from
the environment is kept for backwards compatibility, as well as to allow
overriding.
Closes #138
=>  Implement reading user config from file

packit/api.py, packit/base_git.py, packit/distgit.py, packit/upstream.py, tests/integration/test_distgit.py
The pull request adds a common ancestor for Git (upstream/downstream) repo. Do not use the same functions twice.
=> Fixes #157 Create common ancestor for Gits

docs/configuration.md, packit/api.py, packit/config.py, packit/distgit.py, packit/sync.py, packit/upstream.py, tests/unit/test_config.py, tox.ini
Fixes #171 
PR adds support for copying directories by packit.
Functions `propose-update` and `sync-from-downstream` are affected for now.
What is covered:
=> Support copying of directories

packit/api.py, packit/base_git.py, packit/bot_api.py, packit/cli/srpm.py, packit/cli/sync_from_downstream.py, packit/cli/types.py, packit/cli/update.py, packit/cli/utils.py, packit/config.py, packit/local_project.py, packit/status.py, packit/upstream.py, tests/conftest.py, tests/integration/test_build.py, tests/integration/test_create_update.py, tests/integration/test_update.py, tests/integration/test_upstream.py, tests/unit/test_config.py, tests/unit/test_local_project.py
* sync-from-downstream: improve help descriptions
* propose-update: don't bail if there are only untracked files
* pass upstream_local_project from cli to API
* this way we don't initialize LocalProject twice; I need this when
just to be clear, the thing which failed with pagure.io based projects was that git_url, namespace and repo_name was computed again and packit picked up default remote which did not work; we need #199 badly to support multiple upstream git forges
TODO:
=> onboard pagure.io-based projects

docs/actions.md, docs/configuration.md, packit/actions.py, packit/api.py, packit/base_git.py, packit/config.py, packit/distgit.py, packit/upstream.py, tests/integration/test_base_git.py, tests/unit/test_actions.py, tests/unit/test_base_git.py, tests/unit/test_config.py
Follow-up for #213 
-----
|        | name                  | working directory | when run                                                                          | description                               |
| ------ | --------------------- | ----------------- | --------------------------------------------------------------------------------  | ----------------------------------------- |
| [hook] | `post-upstream-clone` | upstream git repo | after cloning of the upstream-repo (master) and before other operation            |                                           |
| [hook] | `pre-sync`            | upstream git repo | after cloning of the upstream-repo and checkout to the right (release) branch     |                                           |
|        | `prepare-files`       | …
=> sourcegit support (#213 follow up)

docs/how-to-source-git.md, packit/config.py, packit/upstream.py, tests/conftest.py, tests/integration/test_build.py, tests/integration/test_create_update.py, tests/integration/test_update.py, tests/unit/test_config.py, tests/utils.py
Based on top of #231
* ehm, actually use package_config.specfile_path
* git describe: use --match *
I copied the command from the setuptools scm plugin w/o really knowing
what it does. * is better, b/c we don't give a damn if there are dots in
the tag.
=> Random fixes (which we need)

docs/configuration.md, packit/config.py, packit/sync.py, tests/integration/test_sync_files.py, tests/unit/test_config.py, tests/unit/test_sync.py
Allows lists in the sync file source.
(Multiple sources are synced to the same destination.)
```yaml
synced_files:
- packit.yaml
- src:
- fedora/rpm/SPECS/kernel.spec
- fedora/kernel-x86_64-debug.config
- fedora/kernel-x86_64.config
dest: "some-dir"
```
-----
- Current tests for syncing were moved from `unit` to `integration` since they are accessing the filesystem.
- New unit tests were added as well.
=> Support multiple sources in sync files

packit/base_git.py
Otherwise this throws an exc that the branch already exists.
=> create_branch: check out if it exists

Makefile, recipe-tests.yaml, recipe.yaml
and also:
* recipe-tests: attempt a fix
* that NSS wrapper is for sake of openshift: anyuid and rootless are not
compatible
* gcc and rpm-devel are needed for rpm python bindings
* recipe: install more content from RPM
=> containerized tests: comment out and document

Dockerfile, Makefile, files/install-rpm-packages.yaml, recipe.yaml
Fixes #274
~~Still not ideal since a change in recipe.yaml invalidates the cache, we should probably install packages in a dedicated playbook.~~
=> image build: cache packages installation

.pre-commit-config.yaml, Dockerfile, files/httpd-copy.sh, files/install-rpm-packages.yaml, files/packit.wsgi, recipe.yaml
Based on some articles, `packit.wsgi` has to be added into Python path.
See examples here:
- http://flask.pocoo.org/docs/1.0/deploying/mod_wsgi/#creating-a-wsgi-file
- https://www.bogotobogo.com/python/Flask/Python_Flask_HelloWorld_App_with_Apache_WSGI_Ubuntu14.php
- https://www.jakowicz.com/flask-apache-wsgi/
`.pre-commit-config.yaml` was modified because of this flake8 error:
~~~
Flake8...................................................................Failed
hookid: flake8
files/packit.wsgi:5:1: E402 module level import not at top of file
black....................................................................Failed
hookid: black
~~~
=> Add wsgi script into Python path

packit/config.py, packit/jobs.py, tests/unit/test_config.py
I have renamed `get_packit_config_from_repo` into `get_package_config_from_repo`.
-----
Fixes #255
=> Fixes #255 refactor get_package_config_from_repo

packit/api.py, packit/constants.py, packit/jobs.py, packit/local_project.py, packit/service/web_hook.py
Commits:
* skip failing copr tests
* copr: print basic instructions on succ build
* copr: don't tback if copr sends us invalid state
* copr,status: name it packit/rpm-build instead
* copr,state changes: more user friendly
* packit.yaml: build packit only for f29
=> Print basic instructions how to install copr builds

packit/api.py, packit/cli/status.py, packit/status.py
Using asyncio API for getting statuses asynchronously.
After reading API, I have selected https://docs.python.org/3/library/asyncio-task.html#running-tasks-concurrently
If you switch t1-t5 to another order, then you should see similar output.
=> Use asyncio for asynchronous task in status

files/install-rpm-packages.yaml, recipe.yaml
[httpd-2.4.39-3.fc29](https://bodhi.fedoraproject.org/updates/FEDORA-2019-52487848d6) is in stable
=> [install-rpm-packages.yaml] disable testing

packit/api.py
This pull request fixes issues #322 and #272 .
`await asyncio.sleep(0)` gives control into the main loop.
=> Fixes #322 await asyncio.sleep has to be used

packit/service/web_hook.py, tests/unit/test_web_hook.py
After re-adding (it's not displayed so I couldn't simply check value) webhook secret to [prod app](https://github.com/organizations/packit-service/settings/apps/packit-as-a-service) there are no errors in prod service deployment logs.
So I believe it was just a misconfiguration and we can 'protect the gate' again.
=> [web_hook.py:_validate_signature()] return digest_is_valid 

packit/upstream.py, tests/integration/test_upstream.py
Plugins have been refactored, individual runners removed and replaced with plugin manager. The change will be part of 0.17.0 release.
=> Adapt to changes in rebasehelper plugins

CONTRIBUTING.md, README.md, packit/config.py, packit/distgit.py, packit/jobs.py, packit/ogr_services.py
so that we can utilize it easily in tests
also
```
drop the read_only compat workaround
we have ogr already available in fedora
```
=> set up PersistentObjectStorage in get_github_service

tests/conftest.py
OurPagure was removed from `ogr` and tests tracebacks on 
```
PYTHONPATH=/src PYTHONDONTWRITEBYTECODE=1 python3 -m pytest --color=yes --verbose --showlocals --cov=packit --cov-report=term-missing ./tests/
ImportError while loading conftest '/src/tests/conftest.py'.
tests/conftest.py:37: in <module>
from ogr.services.our_pagure import OurPagure
E   ModuleNotFoundError: No module named 'ogr.services.our_pagure'
```
=> Remove OurPagure. Functionality was removed from Ogr

.packit.yaml, packit/api.py
\+ srpm & upstream: use version since upstream_ref is empty
=> work-around a service bug

CHANGELOG.md, README.md, docs/ARCHITECTURE.md, docs/actions.md, docs/build.md, docs/configuration.md, docs/create_bodhi_update.md, docs/how-to-source-git.md, docs/propose_update.md, docs/srpm.md, docs/sync-from-downstream.md, packit/actions.py, packit/constants.py
This pull request changes references from `https://packit.dev/user-docs` to `https://packit.dev/docs`
requires: https://github.com/packit-service/packit.dev/pull/25
=> Move user-docs to docs

packit/constants.py, packit/upstream.py, tests/integration/test_upstream.py
This change will only work if the basename of the archive follows the `name-version.extension` format. I didn't find anything better that would work more consistently (checking for occurence in the whole path using `in` and then getting the extension by using pathlib wouldn't work - parts of the version would be included in the extension). In the worst case scenario, it fallbacks to the previous solution - using `.tar.gz` as the default.
`SpecFile.get_archive()` could be used but currently rebase-helper assumes that Source0 is always the archive (which is incorrect, see https://github.com/rebase-helper/rebase-helper/issues/561 )
Any other ideas?
Resolves: #358
=> Add support for other tarball formats

packit/api.py, packit/cli/build.py, packit/distgit.py, packit/fedpkg.py, tests/conftest.py
Resolves #411
This changes `packit build` to wait for the build by default, since that's also the `fedpkg build`'s default behavior.
=> Allow to (not) wait for dist-git build

.packit.yaml, packit/api.py, packit/config.py, tests/data/upstream_git/.packit.json, tests/unit/test_config.py
This pull request adds functionality to determine if create_pr is allowed from CLI or from `packit.yaml`.
Adds `create_pr` into `packit.yaml` file.
This is needed for `packit-service` if we want to directly push into dist-git.
It also changed `packit` configuration file and adds there `create_pr` to False, so we can push changes directly into dist-git branch.
=> Add support create_pr option into packit.yaml

packit/api.py, packit/cli/copr_build.py, packit/cli/packit_base.py, packit/constants.py
Fixes #366 
If you just run `packit -d copr-build` from my branch you might be wondering why the COPR project name is [packit-cli-packit-cli-copr-build](https://copr.fedorainfracloud.org/coprs/jpopelka/packit-cli-packit-cli-copr-build/builds/)  :-)
It's OK, the default (if not specified with `--project`) project name is `packit-cli-{repo_name}-{branch/commit}`, where in this case `repo_name` is `packit` and `branch` is `cli-copr-build`.
=> support copr builds in CLI

packit/distgit.py
Previously:
```
Downloaded archive: PosixPath('/tmp/packit-dist-gitrha4t6e_/ogr-0.6.0.tar.gz')
```
Now:
```
Downloaded archive: /tmp/packit-dist-gitrha4t6e_/ogr-0.6.0.tar.gz
```
=> repr(Path) -> str(Path)

packit/status.py
Previously:
```
Latest Koji builds:
f29: python-ogr-0.5.0-1.fc29
f30: python-ogr-0.6.0-1.fc30
```
Now:
```
Latest Koji builds:
f29: python-ogr-0.5.0-1.fc29
f30: python-ogr-0.6.0-1.fc30
f31: python-ogr-0.6.0-1.fc31
```
=> [CLI:status] Show also latest rawhide build

packit/api.py, packit/base_git.py, packit/distgit.py, packit/fedpkg.py, packit/local_project.py, packit/upstream.py, packit/utils.py, tests/conftest.py, tests/unit/test_base_git.py
Changes:
* call kinit before doing fedpkg clone - this is needed inside packit service
* push explicitly and show errors if there are some - in packit service, we don't have branch tracking set up implicitly
Fixes #431
=> make fedpkg work in openshift

packit/config.py
This pull request only adds variables for new Job into packit-service.
If the user adds a comment like `/packit copr-build` then JobType `pull_request_action` is called in `packit-service`. JobTrigger is called `comment`
=> Add support for comments

packit/api.py, packit/upstream.py
This should fix a case in the service when the specfile is not in the root of the git repo.
=> pass src_dir as a relative path to up.srpm()

Dockerfile, Makefile, Vagrantfile, files/install-requirements.yaml, files/tasks/build-rpm-deps.yaml, files/tasks/configure-git.yaml, files/tasks/generic-dnf-requirements.yaml, files/tasks/install-packit.yaml, files/tasks/ogr-from-master.yaml, files/tasks/rpm-test-deps.yaml, files/tasks/sandcastle-master.yaml, files/zuul-install-requirements-git-master.yaml, files/zuul-install-requirements-rpms.yaml, files/zuul-tests.yaml, tests/integration/test_upstream.py
- simplify ansible scripts, avoid duplication
- same enviroment for make check in container as zuul check ogr from master
- regenerate ``test_data`` in container to ensure you have clean env
- fix vagrant  according to these changes
- fix dockerfile according to these changes
=> simplier ansible scripts + regeneration target in makefile

packit/cli/packit_base.py, tests/unit/test_cli.py
Fixes: #375 
Do you guys agree with the position in help? I think it makes the most sense to have it next to `--help` option.
=> Replace version command with --version option

packit/utils.py
`dict.get()` also does not report anything.
The reason is that I see a lot of these in the logs and I doubt they have any value
```
[DEBUG/ForkPoolWorker-1] can't obtain action: 'action'
[DEBUG/ForkPoolWorker-1] can't obtain number: 'number'
[DEBUG/ForkPoolWorker-1] can't obtain pull_request: 'pull_request'
[DEBUG/ForkPoolWorker-1] can't obtain release: 'release'
[DEBUG/ForkPoolWorker-1] can't obtain action: 'action'
```
=> [utils.nested_get()] don't report returning default value

Dockerfile.tests, Makefile, files/install-requirements.yaml, files/install-tests-requirements.yaml
This is preparation work for [splitting `packit-service` image](https://github.com/packit-service/packit-service/issues/77).
Previously the `Dockerfile` was used to build an image for tests.
Now:
- there's a `Dockerfile.tests` for tests
- `Dockerfile` will be [used by docker hub](https://cloud.docker.com/u/usercont/repository/registry-1.docker.io/usercont/packit) to create an image which will be used as a base image for `packit-service worker` image. I've created a [stable](https://github.com/packit-service/packit/tree/stable) branch, which will be used by docker hub to create `:stable` packit image.
=> Separate image for packit and for tests

packit/api.py
and delete projects after 6 months.
I'd let them hard-coded for now to keep things simple unless someone explicitly requests otherwise.
=> Don't show Copr projects on homepage

packit/utils.py, tests/unit/test_utils.py
Fixes following issue:
After running:
```
git clone https://github.com/containerbuildsystem/atomic-reactor/
cd atomic-reactor
packit generate
```
the packit.yml was weird
```
specfile_path: .spec
synced_files:
- .spec
- .packit.yaml
upstream_project_name:
downstream_package_name:
```
=> Allow slash in git_url

.packit.yaml, packit/upstream.py
make sure that one of the returned strings contains name of an existing archive
This should have been in c7e320f
=>  [create_archive()] verify create-archive action output

packit/upstream.py, tests/testsuite_basic/data/upstream_git/beer.spec, tests/testsuite_basic/integration/test_upstream.py
Fixes #536
With this change, we default to Source0 and Source, which should improve UX for newcommers if they use Source in their spec files.
Everyone is still able to set their `Source\d` line their config.
=> fix-spec,Source: default to Source0 and Source

packit/api.py, packit/base_git.py, packit/cli/types.py, packit/cli/utils.py, packit/constants.py, packit/distgit.py, packit/local_project.py, packit/upstream.py, packit/utils.py, tests/testsuite_basic/conftest.py, tests/testsuite_basic/data/cockpit-ostree/packit.yaml, tests/testsuite_basic/data/dist_git/.packit.json, tests/testsuite_basic/data/empty_changelog/.packit.json, tests/testsuite_basic/data/osbuild/.packit.yaml, tests/testsuite_basic/data/upstream_git/.packit.json, tests/testsuite_basic/integration/test_build.py, tests/testsuite_basic/integration/test_get_api.py, tests/testsuite_basic/integration/test_update.py, tests/testsuite_basic/unit/test_config.py, tests/testsuite_basic/unit/test_utils.py, tests/testsuite_recording/integration/test_api.py, tests/testsuite_recording/integration/testbase.py
this way, people won't need to specify upstream_project_url
Fixes #553
=> convert `git remote get-url` into HTTPS url and use it

packit/api.py
Related Issue: https://github.com/packit-service/packit/issues/570
In the first call of the `status` API, the global event loop was fetched and later it was closed. The second attempt to get an event loop failed as that had been closed already which resulted in the error.
I considered two ways to fix that:
**Option 1**: Set a new event loop using `asyncio.set_event_loop(asyncio.new_event_loop())` and then use `asyncio.get_event_loop` again.
**Option 2**: Use `asyncio.run()` which essentially [does the same thing as option 1](https://docs.python.org/3/library/asyncio-task.html#asyncio.run), but it's already available in the library for consumption.
_I propose Option 2, as `run` is a high level call providing the exact functionality thereby saving us the trouble of managing event loops …
=> Fixed: 'Event loop is closed' while calling status from API more than once

packit/upstream.py
Fix for situations when actions produce long output.
For example as found in cockpit-ostree:
```
[dhodovsk@shiny cockpit-ostree]$ packit srpm
Packit 0.7.2.dev6+g6b8220c is being used.
Input is a directory: /tmp/cockpit-ostree
WARNING  'upstream_project_name' configuration key was renamed to 'upstream_package_name', please update your configuration file
Input directory is an upstream repository.
Using user-defined script for ActionName.post_upstream_clone: ['make cockpit-ostree.spec']
Using user-defined script for ActionName.create_archive: ['make', 'dist-gzip']
STDERR: npm WARN deprecated angular-bootstrap-npm@0.13.4: angular bootstrap is not being published by original team
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm WARN …
```
=> Split longer action output for create-archive

packit/config.py
so the caller doesn't need to do that (https://github.com/packit-service/packit-service/pull/194)
=> Warn in get_package_config_from_repo() when no config found

packit/upstream.py, packit/utils.py, tests/unit/test_unicodez.py
Fixes problem from https://github.com/packit-service/systemd-rhel8-flock/pull/9#issuecomment-550183552
Locally with `packit srpm`:
```
13:01:53.471 utils.py          DEBUG  b'Wrote: /home/tt/t/systemd-rhel8-flock/systemd-243-2.gc3bfb0bb.fc30.src.rpm'
13:01:53.475 upstream.py       DEBUG  Wrote: /home/tt/t/systemd-rhel8-flock/systemd-243-2.gc3bfb0bb.fc30.src.rpm
SRPM is /home/tt/t/systemd-rhel8-flock/systemd-243-2.gc3bfb0bb.fc30.src.rpm
SRPM: /home/tt/t/systemd-rhel8-flock/systemd-243-2.gc3bfb0bb.fc30.src.rpm
```
=> srcgit: patches can have undecodable chars

packit/api.py, packit/cli/status.py, packit/status.py, tests_recording/test_status.py
=> Packit status - show latest Copr builds

packit/specfile.py
- Copy get_release_number from the old rebasehelper for the compatibility.
=> Bring back get_release_number to rebasehelper SpecFile

packit/cli/build.py, packit/exceptions.py, packit/utils.py
- Catch the failed fedpkg-build.
- Nicer build output.
```
Packit 0.7.2.dev104+g446a9f7.d20191210 is being used.
Input is a URL to a git repo: https://github.com/packit-service/ogr
Input directory is an upstream repository.
Building for the following branches: master, f30, f31
Using 'master' dist-git branch
won't be doing kinit, no credentials provided
won't be doing kinit, no credentials provided
b"Could not execute build: watch_tasks() got an unexpected keyword argument 'ki_handler'"
ERROR    Command ['fedpkg', 'build', '--scratch'] failed
ERROR    Submission of build to koji failed.
Build for branch 'master' failed. 
>>> Building python-ogr-0.9.0-1.fc32 for rawhide
>>> Created task: 39474710
>>> Task info: https://koji.fedoraproject.org/koji/taskinfo?taskID=39474710
!!! Could not …
```
=> Catch the fedpkg build failure

packit/upstream.py
Fixes: https://lgtm.com/projects/g/packit-service/packit/snapshot/5ac926481cc7e67d261a3e96aa6c6291121dfc1e/files/packit/upstream.py#xc5d36b42f61ff553:1
=> Remove else from 'for' when no 'break' present

packit/api.py, packit/local_project.py, packit/upstream.py
- Refactor the preparation of the SRPM build.
- I am preparing the code for some changes related to the multiple sources and pathes.
=> Refactoring of the srpm prepare

packit/api.py, packit/exceptions.py, packit/upstream.py
- Catch errors when creating the SRPM.
- Update exceptions related to the SRPM.
=> Srpm exceptions

packit/api.py, packit/copr_helper.py, tests/integration/test_copr_build.py
- Raise an exception when there is no copr project owner.
- Related to the #647
=> Catch no copr owner

packit/config/package_config.py, packit/schema.py, packit/upstream.py, tests/data/sourcegit/source_git/.packit.yaml, tests/data/sourcegit/source_git/ignored_file.txt, tests/integration/test_source_git.py
we need to control this explicitly since upstream repo can contain paths
which are not present in downstream & release tarball
this patch also accounts for defaults to synced_files - packit.yaml and
the spec file
with this, I got past the %prep phase in https://github.com/packit-service/systemd-rhel8-flock/pull/9
Fixes #639
TODO:
=> new config opt: exclude paths from patching

packit/upstream.py, tests/integration/test_upstream.py
correct:
```
* Mon Jan 20 2020 Jiri Popelka <jpopelka@redhat.com> - 0.8.1-1
- new upstream release 0.8.1
```
incorrect:
```
* Wed Jan 22 2020 Tomas Tomecek <ttomecek@redhat.com> - 0.8.2.dev4+g04baaf0-1
Development snapshot (04baaf00)
```
=> upstream,srpm: prepend dash in the changelog entry

packit/status.py
Fixes #679 
This works for me, it seems that spec file was loaded only for the first branch in the list of branches before.
=> Update spec when getting versions from different branches

packit/config/package_config.py
Seeing this in worker logs:
```
[DEBUG/ForkPoolWorker-1] The config file '.packit.yaml' not found on ref '120438a1201d74c74a085f5c8161e1e737dae55e' of the bkabrda/flexmock repository.FileNotFoundError("File '.packit.yaml' on 120438a1201d74c74a085f5c8161e1e737dae55e not found", UnknownObjectException(404, {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/contents/#get-contents'}))
[DEBUG/ForkPoolWorker-1] Found a config file '.packit.yml' on ref '120438a1201d74c74a085f5c8161e1e737dae55e' of the bkabrda/flexmock repository.
```
Current code goes through `[".packit.yaml", ".packit.yml",  ".packit.json",  "packit.yaml", "packit.yml", "packit.json"]` and spits a warning for every not-found config file.
So if the user named the config `packit.json`, we'd see 5 …
=> [get_package_config_from_repo] Don't print a message for every not-found file.

.zuul.yaml
We [base our image on F31](https://github.com/packit-service/packit/blob/master/Dockerfile#L4) too, so better to test against F31
=> [Zuul] F30 -> F31

packit/upstream.py, tests/unit/test_utils.py
Fixes packit-service/packit-service#344
Tested on the stage in packit-service/hello-world#78
I was trying to use #690 but in packit CLI it was not working with '.' paths and local tests were failing, so I left it in if-else (service-cli).
=> Change the paths in srpm build command

packit/config/job_config.py, tests/unit/test_config.py
- Use test job by default.
- Fixes: https://github.com/packit-service/packit-service/issues/281
=> Test by default

packit/api.py, packit/copr_helper.py
Fixes #688 
The problem was that the `ownername` argument in `create_from_file` method was not set to the config value (was None).
=> Fix the bug in copr-build command

packit/fedpkg.py
After discussion with @TomasTomecek yesterday I changed the init_ticket method - when no keytab is given, kinit is not called.
This should enable #689 to work without kerberos, I tried the fedpkg clone with your config and it works.
=> Remove command for renewing kerberos ticket

packit/config/package_config.py, packit/upstream.py
'spec_source_id', when not defined, will default to "Source0" or
"Source" whichever is found first in the spec file.
Make this double-default more obvious by defining it in PackageConfig.
=> Define defaults for spec_source_id in PackageConfig

packit.spec
It is pulled in as a dependency of something else,
but rather be explicit to avoid surprices.
=> [spec] BuildRequires:  python3-copr

packit/config/package_config.py, packit/upstream.py
This reverts commit 2693daeeae94e5dfb9343cf69178d83173c6b6dd.
=> Revert "Define defaults for spec_source_id in PackageConfig"

packit/upstream.py, tests/data/snapd/.packit.yaml, tests/data/sourcegit/source_git/.packit.yaml, tests/integration/test_source_git.py
`format-patch` adds metadata inside the patch
=> [source-git] Use 'git format-patch' instead of 'git diff' when creating dist-git patches

packit/config/package_config.py, tests/unit/test_config.py, tests/unit/test_package_config.py
I found `DEBUG/ForkPoolWorker-1] Cannot find the spec file: list index out of range` in logs quite confusing, so I rewrote the method and added a unit test.
=> [PackageConfig.get_specfile_path_from_repo()] rewrite & unit test

packit/config/__init__.py, packit/config/job_config.py, packit/schema.py, tests/unit/test_config.py
- Split the JobTriggerType to one related to config and one for actual triggers.
=> Split job and jobconfig (packit)

packit/config/package_config.py, packit/upstream.py, tests/integration/test_upstream.py
Example:
```
packit-0.8.1-1.20200305174322588258.104.g14f3e25.fc31.src.rpm
```
TODO:
Fixes #693
Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>
=> packit, don't touch version, change release

packit/upstream.py
* we now rsplit git-describe output which should help when people use
dashes in tags
* the code is now shorter and more readable
=> fix_spec: make it more reliable and readable

packit/specfile.py, tests/data/dist_git/beer.spec, tests/data/sourcegit/source_git/fedora/beer.spec, tests/integration/test_source_git.py
SourceX might be in a macro and I don't see a better way how to not add the patches inside the macro.
=> More Specfile.add_patches() changes

.zuul.yaml, files/tasks/install-ansible.yaml, files/tasks/install-packit-service.yaml, files/tasks/packit-service-requirements.yaml, files/zuul-reverse-dep-packit-service.yaml
It should work now, here I tried to break the [p-s](https://softwarefactory-project.io/zuul/t/local/build/6cceea5e201c4565bacba19d4f888046) and it failed.
Fixes #742
=> Add reverse-dep tests for packit-service

packit/config/config.py, tests/unit/test_load_authentication.py
#749 I have added a check to the whole else statement! As it only runs if deprecated keys are present in the raw_dict.
=> Warning users only if deprecated keys are present

packit/base_git.py, packit/specfile.py, packit/upstream.py, tests/integration/test_source_git.py, tests/spellbook.py
* order all patches we generate (merge commits were screwing this)
* a merge commit can produce multiple patch files
Fixes: https://stg.packit.dev/copr-build/141/logs
=> source-git: patch generation fixes:

packit/config/package_config.py, tests/unit/test_config.py
This allows packit to discover `spec` files also in subdirectories.
=> get_local_specfile_path() changes

CONTRIBUTING.md, Makefile, packit/copr_helper.py, tests/unit/test_api.py
In Copr, when a namespace belongs to a group, its name starts with '@'.
URLs to builds in the Copr web UI though use the 'g/' token, instead of
'@'.
Take the above into account when generating URLs for the log pages.
Relates to packit-service/packit-service#523.
=> Fix web URLs for Copr builds owned by groups

packit/config/config.py
get_project related arguments updated so additional parameters can be passed to underlying ogr method
e.g.
packit-service.worker.event.AbstractEvent:
```
def get_project(self) -> GitProject:
return ServiceConfig.get_service_config().get_project(url=self.project_url)
```
can call
ogr.factory:
```
def get_project(
url,
service_mapping_update: Dict[str, Type[GitService]] = None,
custom_instances: Iterable[GitService] = None,
**kwargs,
) -> GitProject:
```
with service_mapping_update parameter
=> get_project related arguments updated 

packit/api.py, packit/constants.py, packit/specfile.py, packit/upstream.py, tests/conftest.py, tests/data/dist_git/.packit.json, tests/data/snapd/packaging/fedora/fix-spec, tests/data/snapd/packaging/fedora/pack-source, tests/data/upstream_git_weird_sources/.packit.json, tests/data/upstream_git_weird_sources/beer.spec, tests/functional/test_srpm.py, tests/integration/test_upstream.py, tests/spellbook.py
Fixes #708
1. `self.specfile.set_tag(full_name, archive)` did not do anything to the spec file: hence I implemented it differently by replacing the %package section
2. we were checking extension of the archive in Source - we no longer need to do that since we now change the %setup line - we always create tar.gz now and let %setup process it
=> change the way how packit does archives

packit/constants.py, packit/patches.py, packit/upstream.py, tests/integration/test_source_git.py, tests/spellbook.py
git is not able to create a sequence of patches when git history is too complex:
https://github.com/packit-service/packit/pull/766#issuecomment-602030852
we are also generating patches using one `git format-patch` call
reproducer:
```
$ git clone https://github.com/systemd-ci-incubator/systemd.git
$ cd systemd
$ git fetch origin "+refs/pull/1/head:refs/remotes/origin/pr/1"
$ git checkout pr/1
$ packit --debug srpm
$ mock --rebuild ./*.src.rpm
```
=> create_patches: linearize history if too complex

Makefile
In 30dbc5b I thought it's a good idea to pass all environment variables
from the host in the container where the checks are executed.
It turned out, passing `HOME` causes `git config` to look for
username and email configuration at the wrong place.
In order to keep things under control, be explicit about which
environment variables are passed from the host to the container. So far
this is only `TESTS_TARGET`.
=> Be explicit about the env vars passed in 'make check_in_container'

packit.spec, packit/config/config.py, packit/config/job_config.py, packit/config/package_config.py, packit/config/sync_files_config.py, packit/schema.py, setup.cfg
To be merged together with https://github.com/packit-service/packit-service/pull/538
If you want to test with marshmallow-3, you can use [this rpm](https://jpopelka.fedorapeople.org/python3-marshmallow-3.1.1-2.fc32.noarch.rpm).
I was trying to inherit more of our classes (like `JobConfig`) from the [MM23Schema](https://github.com/packit-service/packit/pull/775/files#diff-bdfa782a63635e6f072bd2bc058a5683R148), but there's some advanced magic, which prevented me from doing that. Since this is a temporary code (until F31 is EOL) I can live with that, can you too?
I'll address #744 and #782 separately.
=> Marshmallow v3 support

Makefile
Instead of requiring to set the CONTAINER_ENGINE environment variable
for 'make' to choose 'podman' instead of 'docker', try to guess it by
first trying 'podman', and defaulting to 'docker' only if that failed.
Seen in the OpenShift docs:
https://docs.openshift.com/container-platform/4.2/openshift_images/create-images.html#testing-locally_create-images
=> Guess CONTAINER_ENGINE when using 'make'

packit/config/job_config.py, packit/schema.py, tests/unit/test_config.py, tests/unit/test_package_config.py
- Add 'branch' attribute to metadata.
- Fixes #795
=> Add 'branch' attribute to job metadata

packit/config/job_config.py, packit/schema.py, tests/unit/test_config.py
- Add 'scratch' attribute to metadata.
- Required by koji build.
=> Add scratch to metadata

.packit.yaml, packit/config/job_config.py, packit/schema.py, tests/unit/test_config.py, tests/unit/test_package_config.py
`dist_git_branch` (and older `dist-git-branch`) are still accepted, but deprecated
We need the key to be able to accept a list of strings (branches), not just one string.
Internally it's (and also `targets` now) stored as `Set[str]`, but it's loaded as `List[str]` from config (yaml doesn't know sets).
=> Rename job metadata dist_git_branch to dist_git_branches 

packit/copr_helper.py, tests/integration/test_copr_build.py, tests/unit/test_api.py
In a [discussion with praiskup] I've learnt, that URLs pointing to Copr
builds don't have to contain the owner and project name. Providing only
a build id is enough, as such links will redirect to the proper owner
and project.
Considering the above this removes owner and project name from the Copr
build URLs, to simplify this code path.
[discussion with praiskup]: https://pagure.io/copr/copr/issue/1332
=> Simplify URLs pointing to Copr builds

files/tasks/rpm-test-deps.yaml
rpmautospec-rpm-macros needs to be installed so that we can process
ogr's spec with %autochangelog correctly
=> let tests pass in TFT

packit/config/package_config.py, tests/unit/test_package_config.py, tests_recording/testbase.py
For centos-stream repositories in packit-service, we can hardcode the spec-path since Pagure does not support listing files.
=> allow avoiding the remote search for specfile

packit/base_git.py, tests/data/upstream_git/beer.spec, tests/integration/test_update.py
- Save the specfile to the file after the content sync
- Fixes: https://github.com/packit-service/packit/issues/828
- We need to force rebase-helper to refresh indices to save version to the correct line when upstream and downstream differs in the line number of the version.
=> Save specfile after content sync

packit/api.py, packit/distgit.py, packit/fedpkg.py, tests/integration/conftest.py, tests/integration/test_using_cockpit.py
- Move initialization of the kerberos ticket to the api.
- Use it also for koji builds for upstream SRPM.
=> Initialize kerberos for upstream koji build

packit/config/aliases.py, tests/unit/test_config_aliases.py
This started as a single change, then ended up also moving Fedora 32 to 'fedora-stable'.
Let me know if you think this is not the right time for any of these changes.
The idea for 'epel-all' came from [this Sentry issue](https://sentry.io/organizations/red-hat-0p/issues/1677826439/?environment=prod&project=1767823&referrer=alert_email).
If/When this get's merged, I'll update docs in packit.dev, too.
=> Introduce 'epel-all' as an alias

files/tasks/packit-service-requirements.yaml
packit-service's tests need them.
See for example [this](https://softwarefactory-project.io/zuul/t/packit-service/build/29a2cf7fab14403396f390d92c0d15d3/log/job-output.txt)
=> [Zuul reverse deps] Install worker dependencies

packit/fedpkg.py
Spaces were missing.
Fixes: #845.
=> Rewrap the "failed to clone" error message

fedora-tests/tests.yml
https://jenkins-continuous-infra.apps.ci.centos.org/job/fedora-rawhide-pr-pipeline/3670/artifact/package-tests/logs/FAIL-str_upstream.log
=> fix tests in Fedora CI by installing setuptools_scm

.packit.yaml, README.md
- Add copr builds for master commits and update installation instructions.
- Why?
- dog-fooding packit-service
- Just that we can..;)
- Someone may want to actually use that.
=> Add copr build for master

packit/copr_helper.py
- Add missing spaces to the installation instructions for the copr repo.
=> Add spaces to copr instructions

packit/config/package_config.py
The override logic is using .get_from_dict which is pretty expensive
given it parses and validates the payload - let's not do all of that if
overrides are empty since it would be just a waste of cycles.
I need this in p-s PR because this is breaking ~50 tests which would
take me ages to fix.
=> pc.set_job_overrides: do heavy lifting only when needed

packit/config/config.py, packit/config/job_config.py, packit/config/package_config.py, packit/config/sync_files_config.py, packit/schema.py, tests/unit/test_config.py, tests/unit/test_package_config.py
In packit-service I need to dump and load only the JobConfig, but the JobConfigSchema did not inherit from MM23Schema, so it was not compatible with Marshmallow 2. When the JobConfigSchema inherits from MM23Schema and it overrides  `dump` and `load` methods with the same names, then when the PackageConfig is loaded, it is not working, because when getting nested JobConfig, our overridden methods are called and in Marshmallow 2 it causes problems.  Therefore I used different names for the `dump` and `load` method (then when getting nested JobConfig, Marshmallow manages dumping and loading itself and does not call our overridden methods).
=> Allow inheriting from MM23Schema for each config schema

packit/cli/build.py, packit/cli/create_update.py, packit/cli/packit_base.py, packit/cli/push_updates.py, packit/cli/status.py, packit/cli/sync_from_downstream.py, packit/cli/types.py, packit/cli/update.py, packit/schema.py
```
logging: turn common statements to debug logs
These log statements are interesting to us, as packit devs, but not to
our users really - they don't care what packit version is being used, or
whether $PWD is a upstream repo. People care about what packit does and
what may be a problem.
Therefore I'm reducing these common statements which were printed all
the time to debug - if users run into problems, they can rerun with
`packit --debug` and give us all the meaningful info.
```
and
```
cli/*: use __name__ to construct a logger
__file__ gives us different logger than 'packit' logger, so let's do the
right thing:
ipdb> logger
<CustomLogger packit (INFO)>
ipdb> logging.getLogger(__file__)
<CustomLogger /home/tt/g/user-cont/packit/packit/cli/packit_base.py (WARNING)>
```
=> logging improvements

packit/api.py, packit/base_git.py, packit/cli/copr_build.py, packit/config/common_package_config.py, packit/config/package_config.py, packit/distgit.py, packit/status.py, packit/upstream.py, tests/integration/test_get_api.py
since we want JobConfig to be as powerful as PackageConfig, we need to
make sure that packit work with it via API
Follow-up to: #858
Needed for packit-service/packit-service#418
Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>
=> accept JobConfig and PackageConfig equally

.github/stale.yml
Use literal style (|) in the YAML string, in order to keep new-lines and
have a better formatting.
Be explicit about the dates.
Be more English (hopefully).
=> Improve the message when marking issues as stale

packit/specfile.py
Currently the representation of the RebaseHelperException is logged,
which results in log lines like:
```
ERROR    Rebase-helper failed to change the spec file: RebaseHelperError()
```
This is not helpful.
By removing `!r`, this log will use str(ex) instead which will print the
error message. See
https://github.com/rebase-helper/rebase-helper/blob/fb79efc2bc5590107ffe7e665ad469c58ce2a302/rebasehelper/exceptions.py#L43
=> Log str(ex) when a RebaseHelperError is encountered

packit.spec, setup.cfg
Marshmallow is used instead for some time now.
=> Remove 'jsonschema' as a dependency

packit/api.py, packit/cli/copr_build.py, packit/config/job_config.py, packit/copr_helper.py, packit/schema.py, tests/unit/test_config.py
- Be able to set listed_on_hp,preserve_project,additional_repos in CLI for copr-build.
- Allow setting/editing of unlisted_on_hp,temporary,additional_repos for copr projects.
- Add new fields for metadata about copr-builds.
- Fixes: https://github.com/packit-service/packit/issues/774
- Users can set also `additional_packages` in config but it's not used yet. (Needs to be set per-chroot and will take more time to make it properly.)
=> [packit] Copr enhancements

packit/api.py, packit/base_git.py, packit/command_handler.py, packit/utils.py, tests/data/dg-ogr/.packit.yaml, tests/unit/test_base_git.py, tests/unit/test_utils.py
Invoke user-defined commands with shell=True, while our commands are running as shell=False
* we already run commands defined by users - it's gonna be more convenient for them
to do `ls *.tar.gz` instead of `bash -c "ls *.tar.gz"`
* and we have the sandbox to minimize the damage
Fixes #692
=> invoke all commands in shell

.packit.yaml, README.md
- Add new copr-project for upstream releases.
- Share the projects with `OGR` (relates to https://github.com/packit-service/ogr/pull/428).
=> Copr-builds for releases and few changes for master builds

packit/config/package_config.py, packit/config/package_config_validator.py, tests/integration/test_validate_config.py, tests/unit/test_package_config.py
Fixes https://github.com/packit-service/packit-service/issues/714
configs are easy, right o_O  
So... Before this change, we first created PackageConfig (and copied all
attribs to all jobs) and then set all the defaults globally to that
PackageConfig instance -- obviously that doesn't work for the jobs, so
they didn't inherit the defaults.
With this change, we set the defaults in the raw_dict before creating
PackageConfig, hence defaults get processed correctly and set to all
jobs.
🍺
=> package_config: set defaults correctly to all jobs

packit/patches.py, tests/integration/test_source_git.py
- Simplify creating of the PatchMetadata instance.
- Add ignore option to patch metadata.
- Follow-up to #875
=> [patch metadata] ignore option and instance creation improvement

packit/upstream.py, tests/integration/test_upstream.py, tests/unit/test_upstream.py
Use git-describe to get latest git tag and then using git-log obtain all
commit messages b/w {last_tag}..HEAD and feed the output to %changelog
* fall back to old behaviour when git-log or git-describe fails
* former tests were too complicated - simplify them or merge into
existing one
Fixes #738
Carries #776
=> upstream git-log inside rpm %changelog

packit/local_project.py, packit/upstream.py, tests/functional/test_validate_config.py, tests/integration/test_upstream.py, tests/unit/test_local_project.py
p-s gives us both, commit hash for a PR and PR ID as well
since we want to have 'pr123' in the release field, let's check out
the PR itself, so if both are specified, PR ID > ref
I deserve a Nobel prize for that test case!
Fixes #890
=> local_project: check out PR over ref

packit.spec, setup.cfg
New dependencies added to packit.spec file to be able to handle
dependencies in packit-service easier.
Pcakage pygithub was removed from setup.cfg,
as it was not used anywhere in code.
=> Update packit.spec and setup.cfg files 

.pre-commit-config.yaml, setup.cfg
This reverts commit 88576b8cd4eb62178626f2ee30b53cb03e5d8765.
In Centos 8 Python 3.6 is the default python3. Having Python 3.6 support
will make life easier there.
=> Revert "Drop python 3.6"

packit.spec, setup.cfg
https://github.com/fedora-infra/bodhi/pull/4081
=> [setup.cfg] bodhi-client can now be installed from PyPI

packit.spec
They were added because of https://github.com/packit-service/packit-service/pull/717 but are not needed anymore (since we use setupcfg2rpm.py).
=> [packit.spec] remove not needed BuildRequires

files/tasks/packit-service-requirements.yaml
Tests were broken because of variable SOURCE_BRANCH introduced in packit
service.
=> Fix reverse-dep tests

packit/upstream.py
*  logging
*  extends symlinking of path to the linked archive
also logs relative path to the linked archive
*  prints both relative and absolute path to the created archive
*  has paths that could resolve problem with linking
Before: `archive_in_specdir` (links to) `created_archive`
Potential solution: `created_archive` is converted to absolute path and then converted to **relative to the** `specdir`
=> [srpm] Extend logging of paths and make path to archive explicit

packit/api.py, packit/cli/copr_build.py, packit/copr_helper.py, packit/exceptions.py, tests/integration/test_copr_build.py
- Ask for `admin` permissions and raise a better exception when we can't update the copr project settings. (The exception contains all fields that need to be changed with old and new values.)
- Will fix https://github.com/packit-service/packit/issues/902 once used in the packit-service.
TODO:
=> copr settings updates

packit/copr_helper.py, tests/integration/test_copr_build.py
- Use `ProjectProxy`, not the copr project object to request permissions.
=> Call the method on right copr object

packit/distgit.py, packit/upstream.py, tests/integration/conftest.py, tests/integration/test_pagure.py, tests/unit/test_upstream.py
'pr_create' is marked as deprecated in ogr.
=> Use 'create_pr' instead of 'pr_create'

packit/base_git.py, packit/patches.py, packit/specfile.py, packit/upstream.py, tests/data/sourcegit/source_git/fedora/beer.spec, tests/integration/conftest.py, tests/integration/test_source_git.py, tests/spellbook.py
```
In the patch e-mail workflow, one can send a patch with multiple
commits, e.g. pacemaker is using this. These are then applied with
git-am. Packit did not understand this since only the HEAD commit of
such a contribution has patch metadata, the rest is `not
patch.present_in_specfile`.
With this change, we detect such situation and behave accordingly.
Example:
* c1 [HEAD] - some.patch, squash_commits: true
* c2 - [no metadata]
* c3 - [no metadata]
* c4 - beer.patch, squash_commits: true
* c5 - other3.patch, squash_commits: true
* c6 - [no metadata]
This should produce 3 patch files:
* some.patch, commits: [c1, c2, c3]
* beer.patch, commits: [c4, c5]
* hops.patch, commits: [c6]
```
TODO:
Needed for https://github.com/packit/dist-git-to-source-git/pull/29
=> merge related commits into a single patch (git-am)

packit/api.py, packit/copr_helper.py, tests/integration/test_copr_build.py
- Add method for getting Copr settings frontend URLs.
- Ignore boolean update of copr settings if the value is None.
- Together with https://github.com/packit/packit-service/pull/776 fixes https://github.com/packit/packit/issues/931
=> Allow ignoring updates for Copr boolean values

packit/base_git.py, packit/specfile.py, tests/data/sourcegit/source_git/fedora/beer.spec, tests/integration/test_source_git.py, tests/integration/test_spec.py
```
it's just too invasive and can't work with %setup + %autopatch
let's rely on people to do proper patching; also with patch metadata
we're covered well
```
needed to achieve https://github.com/packit/dist-git-to-source-git/pull/29#issuecomment-673545142
=> source-git: drop ensure_pnum

packit/api.py, packit/base_git.py, packit/cli/init.py, packit/cli/utils.py, packit/cli/validate_config.py, packit/distgit.py, packit/fedpkg.py, packit/local_project.py, packit/upstream.py, packit/utils/repo.py, tests/integration/conftest.py, tests/integration/test_base_git.py, tests/integration/test_build.py, tests/integration/test_get_api.py, tests/integration/test_local_project.py, tests/integration/test_update.py, tests/integration/test_upstream.py, tests/integration/test_using_cockpit.py, tests/integration/test_using_examples.py, tests/unit/test_local_project.py, tests/unit/test_upstream.py, tests_recording/test_api.py, tests_recording/testbase.py
This is related to already closed #733 
It's far from fixing #733 but this `LocalProject.working_dir` is used a lot so it's a huge part.
And I don't want any big rebases on any side.
I'd suggest reviewing both commits together since the second one reverts some changes done in the first.
=> Make LocalProject.working_dir Path instead of str

packit/base_git.py, packit/command_handler.py, tests/functional/spellbook.py, tests/functional/test_srpm.py, tests/unit/test_base_git.py
sandcastle: log output as INFO, split the long chain per lines
local: use print_live of run_command thus logging things as INFO
we use INFO because user's commands are important and they should see
the output by default
=> improve action output logging

tests/integration/test_upstream.py
Hello, this PR addresses a problem raised in https://github.com/rebase-helper/rebase-helper/issues/819
The test used `%{S: ...}` macro incorrectly - it's supposed to be used with a source number to get its path. Using it with an absolute path (which was the case in the test) is an undefined behaviour which changed in RPM 4.16 (that is now in beta and used in F33 and rawhide). The handling of the macro changed slightly with a bug fix (see https://github.com/rpm-software-management/rpm/commit/94623389ba61a3a93decc726ed63e52cca7b3d39).
=> Fix failing test in F33 and Rawhide

packit/specfile.py
- Start numbering source-git patches after the original patches.
- Fixes problem occurred here: https://stg.packit.dev/srpm-build/1362/logs for this MR: https://gitlab.com/packit-service/src/drpm/-/merge_requests/2
=> Fix patch numbering

packit/upstream.py, tests/integration/test_upstream.py, tests/unit/test_upstream.py
Use package config variable upstream_tag_template to extract version
from git tag.
TODO:
=> Use upstream_tag_template to get version from tag

files/zuul-reverse-dep-packit-service.yaml
It has to be set explicitly since https://github.com/packit/packit-service/pull/800
=> Set REDIS_SERVICE_HOST in reverse-dep-p-s tests

packit/patches.py
we are using this in d2s: https://github.com/packit/dist-git-to-source-git/pull/81
=> PatchMetadata.from_commit: make path optional

packit/upstream.py
Version string generated from packaging.version.Version will have leading zeros
dropped.
```
>>> str(packaging.version.parse("2020.09.20"))
'2020.9.20'
```
We should just use the original version string as it was.
Fixes #973
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>
=> Don't drop zeros in version numbers

packit/cli/local_build.py, packit/cli/packit_base.py, packit/cli/srpm.py, packit/cli/sync_from_downstream.py, packit/cli/types.py, packit/cli/update.py, packit/config/config.py, packit/schema.py, tests/functional/test_local_build.py
Multiple changes here:
* --remote option is now global and available to all the commands via
the magic cli/types.py parsing and global LocalProject instantiation
* sync-from-downstream --remote was renamed to --remote-to-push because
it was semantically different from the other --remote: let's make
this clear to our users
* --remote can now be specified in user's config (via
upstream_git_remote parameter)
Please mention the rename in the release notes.
Fixes #586
=> cli: make --remote global

packit/patches.py, tests/integration/test_source_git.py, tests/spellbook.py
some patches in dist-git are applied with -p0 which implies --no-prefix
option for format-patch
this commit enables that: packit is able generate a patch file with
format-patch without leading a/ and b/ in the patch diff
by default format-patch generates patches for -p1 application
🤦‍♂️
https://github.com/packit/dist-git-to-source-git/issues/85#issuecomment-698827925
=> patches: support git format-patch --no-prefix

packit/api.py, tests/integration/test_source_git.py, tests/integration/test_update.py, tests/integration/test_using_cockpit.py, tests_recording/test_api.py
I was trying to fix the test failures in #934 and found out that the `sync_release` method in tests is called with wrong order of attributes, so `use_local_content="0.1.0"`,  `version=None` :
https://github.com/packit/packit/blob/7bc08fc8ec7cb413e6298d3278768aacfc4dccf6/tests/integration/test_update.py#L67
https://github.com/packit/packit/blob/7bc08fc8ec7cb413e6298d3278768aacfc4dccf6/tests/integration/test_source_git.py#L51
=> Use correct arguments in sync_release() from tests

packit/config/common_package_config.py, packit/config/job_config.py, packit/config/package_config.py, packit/schema.py, packit/upstream.py, tests/integration/conftest.py, tests/integration/test_upstream.py, tests/unit/test_upstream.py
This PR consists of 2 parts:
Note:
In the case of unknown archive and template not provided we will try to use the current approach (`{self.package_config.upstream_package_name}-{version}`)
=> Use archive in Upstream._fix_spec_prep

packit/api.py
Resolving failing tests in #964, example error message:
`stderr: 'fatal: ambiguous argument 'remotes/origin/0.4.0-master-update': unknown revision or path not in the working tree`
(Previously, only the case of `create_pr=False` was tested.)
=> [sync_release] reset the branch correctly

files/zuul-tests-session-recording.yaml, files/zuul-tests.yaml
This should fix currently broken ogr-reverse-dep-packit-tests
=> [files/zuul-tests*.yaml] set default project_dir

packit/upstream.py, tests/functional/test_srpm.py
=> Allow symlinking absolute path to archive

packit/patches.py
with the single-commit source-git repos in 8, this is no longer a
warning - it's normal
=> no patches b/w refs: change logger.warning() to info

packit/api.py, packit/config/common_package_config.py, packit/config/job_config.py, tests/unit/test_package_config.py, tests_recording/test_api.py, tests_recording/test_data/test_api/tests_recording.test_api.ProposeUpdate.test_changelog_sync.yaml, tests_recording/test_data/test_api/tests_recording.test_api.ProposeUpdate.test_changelog_sync.yaml.packit-dist-git_2_1.tar.xz, tests_recording/test_data/test_api/tests_recording.test_api.ProposeUpdate.test_changelog_sync.yaml.static_tmp_1_1.tar.xz, tests_recording/test_data/test_api/tests_recording.test_api.ProposeUpdate.test_comment_in_spec.yaml
- Fixes #883
- Add `sync_changelog` option to the config, defaults to `False` (old behaviour).
- Sync specfile as a full file if `sync_changelog` is True.
- Downstream spec-file is located in the root not like in upstream.
TODO:
=> Add option to sync full content of the spec-file

packit/patches.py, tests/integration/test_source_git.py, tests/spellbook.py
source-git: git-am patches: enable regular patches on top
the use case here is that a contributor can propose a PR and not follow
the git-am patches style and packit would still create a correct SRPM
and the patches would correctly be applied in %prep
this is achieved by:
1) checking that any of the patch commits has squash_commits=True
2) then picking starting commits which don't have squash_commits
and prepending them to the one which has
I was also thinking about supporting an arbitrary patch commit in the
middle, but realized:
1) it's an unrealistic scenario since those commits are covered by d2s
2) would be insanely touch to implement it and make it work reliable
3) not worth the time
Fixes #943
=> source-git: support regular patches on top git-am patches

packit/api.py, packit/config/common_package_config.py, packit/config/job_config.py, packit/config/package_config.py, packit/schema.py, packit/upstream.py, tests/integration/test_source_git.py, tests/integration/test_update.py
Create config option `copy_upstream_release_description` which enables to copy the description of the release seen in Github to `%changelog` in `sync_release`, copy all commit messages between the last and previous upstream tags by default.
Fixes #427 
TODO:
=> Generate proper %changelog in sync_release

packit/config/aliases.py, tests/unit/test_config_aliases.py
Function `get_build_targets` is now called corretly with default as
keyword argument.
=> Fix `packit.config.aliases.get_valid_build_targets`

packit/config/common_package_config.py, packit/upstream.py, tests/integration/test_upstream.py, tests/unit/test_upstream.py
Method `Upstream.get_current_version()` is trying following to get
version:
1. get output from actions
2. use configured `current_version_command (.packit.yaml)
3. extract version from `self.get_last_tag()` using `self.get_version_from_tag()`
fixes #1012
=> Improve logic in get_current_version

packit/cli/utils.py
This line has no use for our users, it's really for us, devs, hence
making it .debug()
And this could be especially confusing to our users if we marked a source-git repo as an upstream repo. Or even a Stream repo as an upstream repo.
=> log "Input dir is a..." as debug, not info

packit/constants.py, packit/specfile.py, packit/upstream.py, tests/integration/test_upstream.py
If the first *Source* tag in a spec file is not indexed, it is always returned, no matter the value of `source_name`.
Fix that by taking advantage of `SpecFile.tags`.
Fixes #1011.
=> Fix SpecFile.get_source()

packit/cli/copr_build.py, packit/copr_helper.py, packit/upstream.py, packit/utils/__init__.py, tests/unit/test_utils.py
we have sentry errors which only tell
Cannot create a new Copr project (owner=packit
project=rhinstaller-anaconda-2997
chroots=['fedora-rawhide-x86_64']): Request wasn't successful, there
is probably a bug in the API code.
not useful at all, this is an attempt to get more info from copr api
This should help us diagnose
https://github.com/packit/packit-service/issues/869
This also fixes a CLI issue:
cli.copr-build: replace / with -
copr doesn't allow / in project names
=> copr, log CoprException.result when creating repo fails

packit/api.py, packit/local_project.py, packit/upstream.py, tests/unit/conftest.py, tests/unit/test_api.py, tests/unit/test_upstream.py
Fixed `api.sync_release` bug, cuased by using version number instead of
git tag name for git checkout.
Added method `upstream.convert_version_to_tag`.
=> Add tag parameter to `api.sync_release` method

packit/copr_helper.py
When owner of the project is group it starts with '@', however, this does not
work when generating URL to this group.
When owner is not group:
``https://copr.fedorainfracloud.org/coprs/{owner}/{project}/``
When owner is group:
``https://copr.fedorainfracloud.org/coprs/g/{owner[1:]}/{project}/``
Example of the broken solution:
https://github.com/jkonecny12/anaconda/commit/f60173824a44bcb6979798eab28ec22fa994ac80
-----------------------------
The code should be fine, however, it's **not tested** because I don't know how to do that when user of this method is service.
=> Fix url for configurations when owner is COPR group

packit/git_utils.py, packit/patches.py, tests/unit/test_api.py, tests/unit/test_upstream.py
Related to issue #278.
* Make packit work with pyyaml < 5.1
* Use `contextlib.suppress` instead of `contextlib.nullcontext`
=> Changes for EPEL 8

packit/config/notifications.py, packit/schema.py, tests/unit/test_package_config.py
Disables congratulations comment by default, if not specified in config
=> Switch default for :champagne: comment to False

packit/config/job_config.py
`JobType` enum should be used just for the values defined by users in the config.
TODO:
Fixes packit/packit-service#879
=> [JobType] Remove values not used by users

.pre-commit-config.yaml, CONTRIBUTING.md, Makefile, files/local-tests-requirements.yaml, tests_recording/README.md, tests_recording/test_api.py, tests_recording/testbase.py
I've been trying to make `make check_in_container_regenerate_data` work for me (because of #1074), but with no luck.
When I try `make check_in_container_regenerate_data` locally I see some problems with tokens so I checked the code and AFAICT we don't use `GITHUB_TOKEN` and `PAGURE_TOKEN` anymore so I changed the Makefile to mount my `~/.config/` into the test container. 
I also see
```
E   subprocess.CalledProcessError: Command 'cd /tmp/packit_tmp/tests_recording.test_api.ProposeUpdate.test_version_change_mocked.yaml/static_tmp_1;git commit -m 'test change' python-requre.spec;git tag -a 0.5.0 -m 'my version 0.5.0'' returned non-zero exit status 128.
------- Captured stderr call -------------
FileNotFoundError: [Errno 2] No such file or directory: …
```
=> Update tests_recording/test_data/ regeneration howto docs

packit/local_project.py, tests/unit/test_local_project.py
LocalProject.checkout_ref() considered ref to be a branch, and created
such a branch if it didn't exist.
This meant though that in a newly cloned repo instead of checking out a
remote branch, it created a local one, usually from the last commit on
the main branch.
In Packit Service this lead to the wrong commit being used for SRPM
builds.
Add a debug log to print the hash of the commit after checkout in order
to make future debugging easier.
=> Don't behave as if 'ref' would be always a branch

packit/api.py, packit/cli/propose_downstream.py, tests/integration/conftest.py, tests/integration/test_source_git.py
Checking out release tag for source-git repos is a mistake since:
* we wouldn't be able to create patches
* and probably wouldn't even have a specfile and downstream packaging
Updates from source-git have to always be made from HEAD since recent
commits are directly related to downstream and that's exactly what
maintainers want to put to downstream. This the most significant
difference between source-git and upstream projects.
Fixes #975
=> source-git & propose-downstream: always --local-content

packit/cli/packit_base.py, packit/cli/propose_downstream.py, tests/unit/test_cli.py
The function implementing the "propose-downstream" command was called
"downstream", which doesn't match expectations, making navigating the
code more difficult. Fix this by making naming consistent.
=> Be consistent in the naming of "propose-downstream"

packit/cli/propose_downstream.py, packit/config/package_config.py, tests/unit/test_package_config.py, tests/unit/test_propose_downstream.py
Previously, `propose-update` command didn't take `dist_git_branches`
option (set in `.packit.yaml`) into account. Now both command-line and
config-file options are respected. Command-line option has priority.
=> Respect requested dist-git branches when propose-update

packit.spec, setup.cfg
- it [requires setuptools >= 40.6.0](https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html#options) (rhel/centos/epel-8 has 39.2.0)
- it installs it into bash_completion/ while we (epel/fedora) need bash-completion/
=> Don't use setuptools option.data_files to install bash-completion

files/zuul-install-requirements-git.yaml, files/zuul-install-requirements-pip.yaml, files/zuul-install-requirements-rpms.yaml
[tasks/requre.yaml installs requre from git](https://github.com/packit/packit/blob/main/files/tasks/requre.yaml) which is IMO not what we want in [zuul-install-requirements-rpms.yaml](https://github.com/packit/packit/blob/main/files/zuul-install-requirements-rpms.yaml) & [zuul-install-requirements-pip.yaml](https://github.com/packit/packit/blob/main/files/zuul-install-requirements-pip.yaml)
=> Install requre from PyPI & rpm instead of git

packit/distgit.py, packit/source_git.py, pytest.ini, tests/data/cronie/.cronie.metadata, tests/data/cronie/.gitignore, tests/data/cronie/SOURCES/cronie-1.5.2-context-role.patch, tests/data/cronie/SOURCES/cronie-1.5.2-restart-on-failure.patch, tests/data/cronie/SOURCES/fix-memory-leaks.patch, tests/data/cronie/SOURCES/fix-unsafe-code.patch, tests/data/cronie/SPECS/cronie.spec, tests/integration/test_source_git_generator.py, tests/spellbook.py, tests/unit/conftest.py, tests/unit/test_source_git_generator.py
```
init: correctly pick up sources from CentOS
though we are not using the official get_sources.sh script (to not add
such a weird dependency to the functionality), instead we download the
archive from the internet - Source0
same drill as the previous commit, except this is for sources
```
```
init: correctly fetch spec from centos dist-git
the former code was a mess, this commit makes it clear:
* there is a spec_dir_name class variable which says in which dir the
spec is stored: fedora = "", centos = "SPECS"
* the variable is now used in dist_git.absolute_spec_path
```
Fixes #1104
=> make `init` command work with CentOS packages

packit/config/aliases.py, tests/unit/test_config_aliases.py
It turns out Bodhi has no concept of "rawhide". Which kinda makes sense,
as "rawhide" is a stream not a release. So Bodhi always display the
Fedora version "rawhide" is going to become in the `/releases` API
endpoint.
For example: before Fedora 34 was branched in dist-git, Bodhi showed
rawhide as Fedora 34 in "Pending releases". After the branching was
done, "Pending releases" had Fedora 34 and Fedora 35 listed.
Tweak the `get_aliases()` code to take this into the consideration.
Fixes packit/packit-service#900.
=> Treat the highest pending version in Bodhi as "rawhide"

packit/utils/logging.py, tests/functional/test_srpm.py
Previously several formats of log messages were used - format of certain log record was determined by its log-level.
To make logs more consistent, only one log format is used now.
In order to improve informative value of logs, date part was added to default log timestamp format.
=> Unify log format for all log levels

packit/distgit.py
When creating update against EPEL, Koji tag is epel*-testing-candidate
as opposed to the f*-updates-candidate for Fedora.
=> Fix Koji tag in create-update for EPEL

packit/config/package_config.py
It was added (7c5770d) when moving from Marshmallow v2 to v3 and it's not needed since we already log raw config.
=> Don't log loaded PackageConfig

packit/upstream.py
An exception was raised here for glibc source-git because upstream glibc
prefixes their git-tags. It wasn't clear what the problem is exactly,
especially for someone new to source-git. With this more descriptive
error message, it should be straightforward how to resolve the issue.
=> %changelog: more descriptive message when ref is 404

packit/base_git.py, packit/config/common_package_config.py, packit/config/job_config.py, packit/config/package_config.py, packit/config/sources.py, packit/distgit.py, packit/schema.py, packit/upstream.py, tests/integration/conftest.py, tests/unit/test_base_git.py, tests/unit/test_package_config.py
Closes #1105 
For `download_remote_sources` I extended [the code](https://github.com/rebase-helper/rebase-helper/blob/0be4d04b195d46f3880107e7f6b7e888733f59c5/rebasehelper/specfile.py#L144) from rebase-helper with getting the URL from config and using it if present.
The issue says that the `path` for sources in config should be relative to the config, but wouldn't be better to have there the path in the sources dir, since we have the `absolute_source_dir` property and also rebase-helper works with it?
=> Support sources in configuration

packit/api.py, packit/base_git.py, packit/command_handler.py, tests/unit/test_base_git.py
https://issues.redhat.com/browse/PACKIT-1133
needs: https://github.com/packit/sandcastle/pull/93
https://blog.tomecek.net/post/automake-in-openshift/
Running actions in separate sandboxes is wasting resources (time,
compute, storage, memory) for no benefit - actually, changes in files
can result into breakages in further actions since absolute paths would
stop working because the "unique" path within the sandbox would no
longer be valid.
This should also result in a speed-up of SRPM builds since we'll no
longer need to re-create the sandbox pods.
Another benefit: less "exceeded timebound quota" errors because we'll be
creating less sandbox pods.
=> command_handler: run all actions in a single sandbox

files/packit-testing-farm-prepare.yaml, tests/unit/test_base_git.py
* install sandcastle
* wrap sandcastle tests with the decorator to run them only when the
module is available
=> make sandcastle-related tests pass

packit/exceptions.py, packit/patches.py, tests/integration/test_source_git.py
The filter-branch command is indeed kind-of experimental since this is
the error from git when the repo is dirty:
Proceeding with filter-branch...
fatal: ambiguous argument '2,3': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Example of the problem:
* https://github.com/OpenSCAP/oscap-anaconda-addon/pull/139
* https://prod.packit.dev/srpm-build/15607/logs
=> patches: dont run linearization if the repo is dirty

packit/base_git.py, packit/local_project.py, packit/patches.py, tests/integration/test_source_git.py
This is the error we got from oscap-anaconda-addon source-git:
fatal: Unable to create '/src/.git/index.lock': Permission denied
It's clear that the linearization commands were run in a wrong path -
this commit fixes that by explicitly setting cwd to the project dir.
Should address problems in https://github.com/OpenSCAP/oscap-anaconda-addon/pull/139
Will verify that in https://github.com/TomasTomecek/oscap-anaconda-addon/pull/1 via stg
=> patches: run linearization commands in the repo

packit/base_git.py, tests/unit/test_base_git.py, tests_recording/test_base_git.py, tests_recording/test_data/test_base_git/tests_recording.test_base_git.ProposeUpdate.test_download_remote_sources_via_spec.yaml
...and only fetch additional remote specfile sources on demand
We are changing the behaviour because some packages define sources as
`Source12: archive.tar.gz` and expect it to be fetched from the
lookaside cache.
My assumption also is that if there are sources defined in packit.yaml,
they should be fetched all the time.
Note: requre does not support fixtures (https://github.com/packit/requre/issues/162) so I decided not to port all the unit tests
=> pc.sources: fetch all by default

.packit.yaml
Hunor is correct, our upstream release description used as a %changelog
violates Fedora guidelines, so let packit assemble %changelog from
git-log.
https://docs.fedoraproject.org/en-US/packaging-guidelines/#changelogs
https://packit.dev/docs/configuration/#copy_upstream_release_description
=> packit.yaml: create downstream %changelog from git-log

.pre-commit-config.yaml, packit/api.py, packit/patches.py, packit/utils/repo.py, tests/data/patches/previous/git-diff.patch, tests/data/patches/previous/missing-diff-line.patch, tests/data/patches/previous/unified-diff.patch, tests/data/patches/previous/weird-identical.patch, tests/data/patches/regenerated/git-diff.patch, tests/data/patches/regenerated/missing-diff-line.patch, tests/data/patches/regenerated/unified-diff.patch, tests/data/patches/regenerated/weird-identical.patch, tests/integration/test_patches.py, tests/integration/test_source_git.py, tests/unit/test_api.py, tests/unit/test_utils.py
The 'propose-downstream' command is using 'git format-patch' to generate
and update the patch files in the dist-git repository. These new patch
files will always be 'git-formatted', while existing patches might use
some different format and this will result an unnecessary update of the
patch-file.
In order to avoid this, attempt to massage the previously present
patch-files in the dist-git repo to a format which can be used with 'git
patch-id --stable', and tell if updating a patch-file can be skipped by
comparing the current and previous patch-id.
The code was tested on the f34 branch of glibc.
=> propose-downstream: Detect identical patches

packit/patches.py, tests/integration/test_source_git.py
First of all, I'm a moron. local_project.create_branch only creates the
branch, and does not check it out. We now have a test case to verify
this - that we end up in the same branch after the SRPM creation when
linearization is triggered.
The second change is that we explicitly check out the former branch
instead of naively doing `git checkout -`.
=> linearization: properly check out the temp branch

packit/api.py
The old one is a bit unclear to me while the new one is more generic and
should tell users what went wrong. If create-archive failed, it will be
in the logs above this one.
=> prepare upstream for srpm: better error message

.packit.yaml
EPEL: I wanted to add it to the d2s container image to contain latest
code
Fedora: it's a good practice to provide bits for rawhide as well
=> packit.yaml: build latest for all Fedora and EPEL

packit/specfile.py, tests/integration/test_source_git.py
It might happen that the last Patch/Source, below which we want to put our patches, is inside unprocessed `%if` `%endif`.
In that case:
- our patches are put inside that unprocessed %if %endif as well
- in each patch iteration we don't see the previously added patch and each patch is then Patch0001
There's no easy way how to realize that we are in such %if %endif section, but we can at least find first empty line after the last Patch/Source and put out patches there, instead of putting them right below it.
Fixes #1153
=>  Specfile:add_patch(): find first empty line after last_source_tag_line

packit/config/job_config.py, packit/schema.py, tests/unit/test_package_config.py
This commit adds 'fmf_url' and 'fmf_ref' to JobMetadataConfig. This can
be later used to store tests in different repository.
Related To: packit/packit-service#968
=> Add test repo reference to package-config

packit/schema.py
These schema methods were kept around for backwards compatibility with
Packit Service.
As Packit Service was updated to use 'load' and 'dump' instead (see
packit/packit-service#1024 and packit/packit-service#1026), these
methods can be removed.
=> Remove 'load_config' and 'dump_config'

packit/cli/copr_build.py, packit/config/aliases.py, packit/schema.py, tests/unit/test_config_aliases.py
Acording to [1], centos-stream target in Copr will be changed to
centos-stream-8. This change reflects it.
centos-stream target is temporarily resolved to centos-stream-8 and
warnings saying that users should update their configuration are
printed.
[1] https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/PJT7PK2TLW7T2Z2WLXUGHUYBWR244SBB/
Related To: packit/packit-service#961
=> Treat centos-stream as centos-stream-8

packit/base_git.py, tests/unit/test_base_git.py
rebase-helper downloads the file again when the archive is on a
web-server which uses compression to transfer data:
file_size = int(r.headers.get('content-length', -1))
if r.headers.get('content-encoding', 'identity') != 'identity':
file_size = -1
Since we literally just downloaded the file, we don't need to do it
again if it's present on the disk.
=> download_remote_sources: dont download a source twice

packit/local_project.py, packit/source_git.py, packit/utils/repo.py
Branch was dependant on temporary locally created git repository, added function to get default branch for new repositories.
=> Rebase patches against HEAD branch, not `master`

.packit.yaml
Merge commits created by Zuul are signed with the GitHub key. Allow only
such commits to be proposed downstream by configuring
`allowed_gpg_keys`. The list can be extended with other keys if needed.
=> Allow only signed commits to be proposed downstream

.pre-commit-config.yaml
Fixes:
```
[WARNING] The 'exclude' field in hook 'prettier' is a regex, not a glob -- matching '/*' probably isn't what you want here
[WARNING] The 'exclude' field in hook 'check-added-large-files' is a regex, not a glob -- matching '/*' probably isn't what you want here
```
=> pre-commit: The 'exclude' field is a regex, not a glob

packit/local_project.py
B/c it's a good idea, in general, but also b/c it will help to
understand what's happening in #1202.
=> Log the head commit hash when checking out a PR

packit/constants.py, tests/integration/test_source_git_generator.py
It seems something changed how rpm invokes multiline macros - now we need
to chain variable definition with '&&'. These variables are being used
to wrap patch commit messages with metadata so packit can utilize them.
Without this commit, there would be no patch metadata and SRPM creation
fails with duplicate Patch IDs.
```
tests/integration/test_source_git_generator.py::test_acl_with_git_git_am[git] PASSED
tests/integration/test_source_git_generator.py::test_acl_with_git_git_am[git_am] PASSED
```
=> init: fix creation with %autosetup -Sgit and git_am

packit/config/package_config.py
Deprecating:
- `current_version_command`
- `create_tarball_command`
Related to #1073, #1075
=> Print warning when using deprecated options

packit/config/aliases.py, tests/unit/test_config_aliases.py
Fixes:
```
Build targets: {'d-x86_64', '--x86_64', 'r-x86_64', 'a-x86_64', '3-x86_64', 'f-x86_64', 'o-x86_64', 'e-x86_64', '4-x86_64'} 
...
Result set: set()
```
=> [get_aliases] create a list for fedora-latest

_packitpatch, packit/patches.py, tests/data/patches/regenerated/git-diff.patch, tests/data/patches/regenerated/missing-diff-line.patch, tests/data/patches/regenerated/unified-diff.patch, tests/data/patches/regenerated/weird-identical.patch
it's not being utilized anywhere and is just confusing what it actually
means - we are planning to replace it with patch_id attribute
=> drop location_in_specfile patch metadata key

packit/cli/types.py
It appears that with latest release of click, the default value ($PWD)
is already converted to `LocalProject`, in case it is a `LocalProject`
object, just return it back from the `convert` method.
Fixes #1237
=> Fix Click's default value for SRPM

packit/fedpkg.py
Without this output we don't get progress, we don't get error
messages about not being authenticated.
=> Print output of 'fedpkg new-sources'

.packit.yaml, plans/full.fmf, plans/git_reference.py, plans/main.fmf, plans/session-recording.fmf, plans/smoke.fmf
It needs to update packit-service image to contain `python3-fmf` package if not already there.
=> Use packit config  as place to  create reference to tests

CONTRIBUTING.md
Neither README.md nor CONTRIBUTING.md describe a way to get
your own changes running in your own packit experience.
This should help contributors get started.
=> CONTRIBUTING.md: Add command to install locally

Makefile
7ff83b1e disabled most of the tests run by default, by mistake.
'check_in_container' should run the unit, integration and functional
tests by default.
=> Re-enable most of the tests in 'check_in_container'

packit/local_project.py, packit/patches.py, packit/source_git.py, packit/specfile.py, tests/integration/test_source_git.py, tests/integration/test_source_git_generator.py
TODO:
The ID represents the index within PatchNNNN definition in the spec.
This is being set in `packit init` when cherry-picking patch commits from
dist-git.
We don't allow tampering the patch order. patch_id needs to be higher
than previous patch.
=> patch metadata: add patch_id

packit/api.py, packit/cli/update_dist_git.py, packit/config/config.py, packit/distgit.py, packit/fedpkg.py, packit/pkgtool.py, packit/schema.py, packit/source_git.py, tests/integration/conftest.py, tests/integration/test_source_git_generator.py, tests/integration/test_using_cockpit.py, tests/unit/test_config.py, tests_recording/test_api.py, tests_recording/test_status.py
Previously `--pkg-tool centpkg` of the `source-git update-dist-git` command ran `fedpkg` tool to upload an archive to the lookaside cache. Now it really uses `centpkg` tool.
Fixes #1232 
`source-git init --centos-package` now reads configuration from `/etc/rpkg/centpkg.conf` instead of from `/etc/rpkg/fedpkg.conf`.
`FedPKG` class has been renamed to `PkgTool` as it now supports both `fedpkg` and `centpkg`.
=> source-git update-dist-git --pkg-tool centpkg

packit/config/config.py
In packit-service, we inherit `ServiceConfig` (`packit-service.yaml`) from `Config` and use it in worker and service and in `stg` `packit-service.yaml` we have
```yaml
pkg_tool: fedpkg-stage
```
but we don't have it installed in the service image (only in worker).
So this can't be an exception, just a warning.
=> Change 'pkg_tool not in path' exception to a warning

packit/patches.py, tests/integration/test_source_git.py, tests/spellbook.py
source-git repo: https://github.com/TomasTomecek/cpython/tree/39-sg
dist-git: git@gitlab.com:redhat/centos-stream/rpms/python3.9.git (c9s)
more details in the commit messages
Edit:
How to test?
1. Clone both repos above
2. drop patch definitions from the dist-git spec file
3. `packit -c ./.distro/source-git.yaml update-dist-git $SOURCE_GIT_PATH $DIST_GIT_PATH`
The issue:
```
$ packit -c ./.distro/source-git.yaml update-dist-git $SOURCE_GIT_PATH $DIST_GIT_PATH
...
2021-05-31 14:37:26.535 specfile.py       DEBUG  There are no patches in the spec.
2021-05-31 14:37:26.536 specfile.py       DEBUG  Adding patch 00353-architecture-names-upstream-downstream.patch to the spec file.
2021-05-31 14:37:26.536 specfile.py       VERBOSE Writing SPEC file '/home/tt/p/c/r/python3.9/python3.9.spec' to the …
```
=> patches,git_am: make patch order consistent + fixes for cpython 3.9 source-git

CONTRIBUTING.md, Makefile
Makefile:
Add prepare-check target for installing
python3-pytest
python3-requre
python3-flexmock
if they are not installed already.
Add prepare-check_in_container for installing podman
if it is not installed already.
CONTRIBUTING.md:
Separate sections for running tests locally and running tests
in a container.  Document packages that may be conditionally
installed:
python3-pytest
python3-requre
python3-flexmock
by prepare-check;
podman
by prepare-check_in_container.
Fixes issue #1219.
Signed-off-by: Ben Crocker <bcrocker@redhat.com>
=> Make 'make check' more consistent, and better documented, across projects

packit/api.py, packit/base_git.py, packit/upstream.py, tests/data/sourcegit/source_git/.distro/beer.spec, tests/data/sourcegit/source_git/.packit.yaml, tests/data/upstream_git/beer.spec, tests/integration/test_source_git.py, tests/unit/test_base_git.py
TODO:
This PR fixes passing %changelog to dist-git when sync_changelog=True for propose-downstream and update-dist-git.
=> fix passing changelog from source-git repo to dist-git

packit.spec, setup.cfg
We call [git](https://github.com/packit/packit/blob/389fa266e9aac6e8acac16e42f7b90a64c5c475e/packit/patches.py#L296) and [rpmbuild](https://github.com/packit/packit/blob/389fa266e9aac6e8acac16e42f7b90a64c5c475e/packit/source_git.py#L372) directly.
Fixes #1193
=> Explicitly require git & rpm-build 

packit/config/job_config.py
When used, a project needs to be enabled in the service configuration
to be able to use the internal Testing Farm instance.
=> Add `use_internal_tf` to the `JobMetadata`

files/install-requirements-rpms.yaml, files/local-tests-requirements.yaml, files/tasks/project-dir.yaml, files/zuul-reverse-dep-packit-service.yaml, files/zuul-tests-session-recording.yaml, files/zuul-tests.yaml
Previously it was a var, redefined in the base job, but this no longer works (?)
=> Set project_dir as a fact

packit/__init__.py
The package/distribution is 'packitos', while `__name__` is 'packit'.
=> Make __version__ work

packit/constants.py, packit/source_git.py, tests/integration/test_source_git.py, tests/integration/test_source_git_init.py, tests/unit/test_package_config.py
so you don't have to add '-c path-to-sg-repo/.distro/source-git.yaml' each time you use 'packit source-git update-dist-git' or 'packit srpm' in a "new" source-git repo.
Also, have constants for '.distro' & 'source-git.yaml'.
=> Add .distro/source-git.yaml to CONFIG_FILE_NAMES

packit.spec, setup.cfg
[rhbz#1968618](https://bugzilla.redhat.com/show_bug.cgi?id=1968618) has been fixed in fedora, i.e. the `python3-koji` RPM package now provides egg-info, so we can have `koji` as a requirement in `setup.cfg` and don't have to explicitly require it in the spec file.
It however hasn't been fixed in epel-8, so we need to have a workaround in the spec for that case.
=> Uncomment koji requires in setup.cfg

packit/command_handler.py, packit/config/config.py, packit/schema.py
To be able to support repository-cache in the sandcastle (so e.g. `git archive` works -- [example error output](https://dashboard.stg.packit.dev/results/srpm-builds/5048)), we need to have repository cache in the sandboxed pod as well.
This PR adds the possibility to configure persistent volumes and forward this info to sandcastle.
=> Volume mounts for sandcastle

packit/distgit.py, packit/pkgtool.py, packit/utils/repo.py
One just has to add `pkg_tool: fedpkg-stage` to the packit config.
This PR/commit moves `packit.utils.clone_fedora_package()` to `DistGit.clone_package()` and rewrites it so that it uses configured `PkgTool`.
Initially, I was about to remove the `DistGit.clone()` and `clone_fedora_package()` as they are unused (I think they should have been removed in 5fe352684), when I spotted #1282 where @Zlopez initially [tried to use the `DistGit.clone()`](https://github.com/packit/packit/issues/1282#issuecomment-878198105), but ended up using `clone_fedora_package()` because [one can't clone from staging dist-git with DistGit.clone()](https://github.com/packit/packit/issues/1282#issuecomment-878851226).
=> Make it possible to clone from staging dist-git with DistGit.clone()

.gitignore, packit/patches.py, tests/data/patches/src/hello/README.md, tests/integration/test_patches.py
Instead of relying on a dedicated commit metadata field
(squash_commits), squash adjacent patch files if they have the same
name.
Keep the 'squash_commits' mechanism around for backwards compatibility.
Fixes #1271.
=> source-git: Squash patches by patch name

packit/cli/init.py, packit/config/package_config.py, packit/constants.py, tests/integration/test_init.py
According to #1028 
- User gets warning when specfile path is not specified in config file.
- `packit init` looks up the specfile path (recursively if needed) and sets it in `.packit.yaml` 
note: I am not sure if my changes are backwards compatible.
=> Specfile path in config file

packit/patches.py
It was added in fe5dbeb1 and causes `source-git update-dist-git` to fail because the patches already exist in the dist-git repo.
=> Don't raise when patch to be renamed to already exists

packit/api.py
This just cover the `create_srpm` with:
```python
try:
finally:
self.clean()
```
Fixes: https://github.com/packit/packit-service/issues/1047
=> Do the cleanup after the `create_srpm`

packit/specfile.py
This string method got introduced only in Python 3.9. Not all
installations have this version.
=> Don't use str.removeprefix()

packit/api.py
so it can be tuned a bit more.
I need to
- set a specific `title` and `description` for the to-be-created commit & MR
- set `sync_default_files` to `False` as the [`source-git update-dist-git` does](https://github.com/packit/packit/blob/ed4a100ec01fc0387236a7eab2581673fbf97041/packit/cli/update_dist_git.py#L134)
=> Add more params to api.sync_release()

packit/upstream.py
Instead of logging an error...
This should be the better thing to do, especially b/c the code doesn't
treat this case as a real error. It just won't update the %prep section.
This change should get rid of the events in Sentry raised when packages
use %forgesetup in their %prep section.
=> Log a warning when %prep is not using (auto)setup

packit/api.py, packit/distgit.py, tests/unit/test_dg.py
otherwise, it's hard to tell from logs why the changes were not pushed and no PR has been created.
---
N/A
=> api.sync_release: Log when the PR already exists

packit/sync.py
So that lists of SyncFilesItems can be sorted in tests.
Ref packit/packit-service#1190
=> Add 'less-than' comparison method for SyncFilesItem

packit/api.py
If a user/service want's to create more updates/PRs (at one time) of the same version for the same dist-git branch, they have to create them from separate branches.
So we need to have a way how to create a unique (or following some pattern) name of each branch.
---
N/A (this is for hardly)
=> Add local_pr_branch_suffix param to api.sync_release

packit/api.py, packit/base_git.py
It uses `click.echo` instead of `logger` and logging level changed to
debug to write less confusing input for user.
Closes #1172
=> Rework `packit status` output to be less confusing for users

packit/config/package_config_validator.py
All right, here is the new PR from #1340 to make things a bit cleaner, a log warning is raised if the specfile specified by the user in the config doesn't exist under the given path :)
=> Issue #1332: Add log warning when specfile not present

tests/integration/test_spec.py
The version numbers of 'rpm' are not always just numbers. A 'beta' might
show up here and there, for example, which will make the int conversion
fail.
In order to fix this, use simple string comparison to tell if the
current installed version of 'rpm' is lower than '4.16'.
=> tests: Fix checking the version of 'rpm'

packit/exceptions.py, packit/local_project.py, packit/utils/repo.py, tests/integration/test_local_project.py
TODO:
checked on stage, works OK
**«On the other hand, GitHub shows merge conflict too, so failed SRPM status without being specific about merge conflict could be fine, I guess»**
```
Wrote: ./hello-0.74-1.20210819144656138822.pr442.base.9.g3138a8b.fc34.src.rpm
```
1. We probably want to get rid of the `base` part, could be done by renaming the branches that are created (changes from PR and the base where the PR is merged)
**Done**
2. The hash is taken from the „merge commit“, not sure if we want to move to rebasing instead of merging…
Not going to get into it, since there is a pretty strange issue regarding rebasing.¹
¹ This [merge request](https://gitlab.com/packit-service/ogr-tests/-/merge_requests/77) can be merged, but I cannot seem to rebase it. My guess is that rebase detects …
=> Merge into base branch when checking out PRs

packit/local_project.py
Logging merge fails with error results in Sentry catching it as an issue. Since
it is a user-facing error, do not log it as an error.
=> Do not log failed merges with error

packit/base_git.py, packit/specfile.py, tests/unit/test_base_git.py
TODO:
---
Fixes #1335
Related to #1299
---
Fixed a bug that caused purging or syncing upstream changelog (when not configured) from specfile when running `propose-downstream`. New behavior preserves downstream changelog and in case there are either no entries or no `%changelog` section present, it is created with a new entry.
=> Add entry to specfiles with empty %changelog + don't purge downstream changelog

packit/command_handler.py, packit/utils/repo.py, tests_recording/test_repository_cache.py
We track the usage of repository-cache to be able to know if we need to mount the repository-cache volume to the sandcastle pods.
Fixes packit/packit-service#1181
---
N/A
=> Do not mount repositorycache when not used

plans/session-recording.fmf
Because 'centos-stream-8 > centos-8', the EPEL tests using recordings
did not have the Copr repo for Requre enabled and so installation of
Requre [failed](http://artifacts.dev.testing-farm.io/2db23bb0-be08-418b-8740-8929d74a5b6a/).
Fix this and also simplify enabling the Copr repo as recommended by
@psss. Docs: https://tmt.readthedocs.io/en/latest/spec/plans.html#install .
=> fmf tests: correctly detect a host running CentOS Stream 8

packit/config/package_config_validator.py, tests/integration/test_validate_config.py, tests/integration/test_validate_synced_files.py
Hi all, 
I started working on issue #1333.
I have some doubts:
1. I checked upstream file existance looking for local files; I believe there is a local cache of the upstream repo, but I am not sure at all.
2. If there is any config schema error then the upstream file existence is not checked. I am not sure this is enough; maybe do you want them checked even if the schema errors are not related with the synced_files field?
3. In the integration tests I created, maybe, there is too much copy&paste.
Let me know how I can improve it.
Should fix #1333
=> validate command: check that files to be synced are present

packit/patches.py, tests/unit/test_patches.py
Fixes #1371
---
Fix reading of a commit message from a patch to support non-utf-8 content.
=> Read a patch as bytes as it can contain non utf-8 stuff

packit/cli/source_git_init.py, packit/source_git.py
The commit fixes unhandled exception when SOURCE_GIT is not a clone
of existing upstream repository.
Hello all,
I've picked up this open issue and tried to fix it up to prove you I should become a valuable member of Packit team :). Hopefully it satisfies all the requirements for the contribution.
Fixes #1360 
Related to
---
=> Fix unhandled exception for packit source-git init command

packit/copr_helper.py, tests/integration/test_copr_build.py
Fixes #1373
---
To fulfill requests regarding updating targets on Copr repositories, Packit Service will sync targets for the projects created by Packit Service (e.g. pull requests, or non-set Copr repository for releases and branch builds) and for Copr repositories **not owned by Packit** will try to extend the list if necessary.
=> Copr builds for specific chroots

packit/api.py
This is not a warning since in the CI workflow kinit is not needed, only
when interacting with the Fedora infra.
#1378
---
Packit no longer prints a warning when a FAS username is not supplied for sake of getting a Kerberos ticket.
=> logging: warn -> debug when not doing kinit

tests/integration/conftest.py, tests/integration/test_pagure.py
I've found just these 2 required changes in packit, the rest of the deprecated methods don't seem to be used anywhere.
Fixes
Related to https://github.com/packit/ogr/pull/652
---
N/A
=> Reflect ogr changes in integration tests

packit/config/aliases.py
Fedora 35 has been released.
---
Backup alias definitions now reflect the official release of Fedora 35.
=> Update backup ALIASES

packit/patches.py, tests/data/patches/previous/unified-diff.patch
When calculating the patch ID of the patches stored in dist-git, it
might happen, that these patch files are not UTF-8 encoded and this
might rise UnicodeEncodingErrors.
Writing this kind of string with the 'surrogateescape' error handler
solves the issue.
This issue was seen in when running the 'source-git update-dist-git'
command to transform a source-git repo for glibc to the CentOS Stream 9
dist-git repo.
---
Fixed an issue, which raised a `UnicodeEncodingError`, when working with dist-git patch files with an encoding other than UTF-8.
=> Handle patch content which has unknown encoding

packit/config/job_config.py, packit/schema.py, tests/unit/test_config.py
It can still be a `list[str]` to be backward compatible.
But because we need to be able to enrich the targets with some attributes it can now be a `dict` {'targets': {'more info': Any} as well.
The `JobMetadataConfig.targets` is now a property returning a set of target names for backward compatibility.
The dictionary of targets with attributes is stored in `_targets` and you can get it also with `targets_dict` property.
The `_` prefixed `_targets` in `JobMetadataConfig.__init__()` looks strange, but it's needed because of the schema validation.
Related to: packit/packit-service#1230
packit-service tests are expected to fail because of the `targets` -> `_targets` change in `JobMetadataConfig.__init__()`
They will be fixed in packit/packit-service#1269 after merging this.
---
N/A (it's just …
=> Allow job metadata targets to be specified as dict as well

tests/integration/test_patches.py, tests/integration/test_source_git_init.py, tests/integration/test_spec.py, tests/unit/test_patches.py
Support for plain 'import flexmock' was removed in [flexmock 0.11.0].
Get ready for this.
[flexmock 0.11.0]: https://flexmock.readthedocs.io/en/latest/changelog/#release-0110
=> Fix flexmock imports

packit/api.py, tests/integration/test_update.py
The specfile may be generated during post_upstream_clone. This means
that getting the version from the spec could fail, hence we always need
to do post_upstream_clone first.
Signed-off-by: František Nečas <fnecas@redhat.com>
@jkonecny12 Would you mind giving this a quick spin? Your reproducer seems to work for me now locally.
Fixes #1413
=> Run post_upstream_clone immediately when updating

packit/config/job_config.py, packit/schema.py, tests/unit/test_package_config.py
Related to https://github.com/packit/packit-service/issues/1217
---
New config option `env` has been added for specifying environment variables.
=> Add environment config option

packit/exceptions.py
This is to differentiate between missing config file and bad config file in packit-service more easily.
Related to [packit-service#1296](https://github.com/packit/packit-service/pull/1296)
=> Introduce PackitMissingConfigException class

packit/api.py, packit/cli/packit_base.py, packit/cli/prepare_sources.py, packit/cli/types.py, packit/cli/utils.py, packit/local_project.py, tests/functional/test_prepare_sources.py, tests/unit/test_prepare_sources.py
TODO:
```
packit prepare-sources --help
Usage: packit prepare-sources [OPTIONS] [PATH_OR_URL]
Prepare sources for a new SRPM build using content of the upstream
repository. Determine version, create an archive or download upstream and
create patches for sourcegit, fix/update the specfile to use the right
archive, download the remote sources. Behaviour can be customized by
specifying actions (post-upstream-clone, get-current-version, create-
archive, create-patches, fix-spec-file) in the configuration.
PATH_OR_URL argument is a local path or a URL to the upstream git
repository, it defaults to the current working directory
Options:
--result-dir DIR            Copy the sources into DIR. By default,
`prepare_sources_result` directory in the
current working directory is created. …
```
=> Prepare sources

packit/utils/repo.py
This information is especially helpful for bigger repositories.
State without this fix is that the user will run propose-downstream command and
waiting without any feedback. User could be easily confused that the application
is frozen.
Closes https://github.com/packit/packit/issues/1412 .
=> Tell user that git repository is cloning

packit/constants.py, packit/schema.py, tests/integration/test_validate_config.py
Check for invalid chars in .packit.yaml upstream_package_name
Since `upstream_package_name` is used as a filename, it may not
have characters illegal in filenames: The slash char, and null char.
Check for these and throw a `ValidationError` when used.
Change comment suggesting '/' in `.packit.yaml` `upstream_package_name`
This comment suggests people use a package name containing a project/repo
syntax with a slash in it. In fact using a slash in the name causes
packit to fail.
Fixes #1432
=> Prevent use of slashes in upstream_package_name

packit/utils/changelog_helper.py, tests/integration/test_changelog_helper.py, tests/integration/test_update.py
This allows finding the correct release even when users don't use the version as a release name.
Example of the problematic release: https://github.com/varlink/libvarlink/releases/tag/23
Fixes: https://sentry.io/share/issue/16a68c95929547ccb5eeaabc83d502d2/
---
Packit now correctly finds the release event if you don't use the version as a release title.
=> Use upstream_git_tag when searching for a release

packit/__init__.py, packit/cli/local_build.py, packit/cli/validate_config.py, packit/config/notifications.py, packit/config/package_config_validator.py, packit/status.py, setup.py, tests/functional/test_local_build.py, tests/integration/test_copr_build.py, tests/integration/test_security.py, tests/unit/test_load_authentication.py, tests/unit/test_propose_downstream.py
There aren't too many left, so let's get rid of them.
=> Update all old-style license headers

packit/local_project.py, tests_recording/test_data/test_local_project/ProposeUpdate.test_checkout_pr.yaml, tests_recording/test_data/test_local_project/ProposeUpdate.test_checkout_pr_no_merge.yaml, tests_recording/test_local_project.py
...instead of `pr-changes/{pr_id}` which is inconsistent with the original
behaviour
This commit makes the local PR checkout naming consistent with
merge/no-merge scenarios.
Fixes #1443
---
Packit now names local branch `pr/{pr_id}` when checking out a PR, even when it's not being merged with the target branch. This results into NVR of the build containing `pr{pr_id}` instead of `pr.changes{pr_id}`.
=> lp,no-merge-pr: check out to pr/{pr_id}

packit/constants.py, packit/local_project.py, tests/integration/test_local_project.py, tests_recording/test_local_project.py
merge PRs: rename to pr/{pr_id} after merging
There are many ways to implement this behavior and this commit is the
least intrusive way.
I tried other ways as well but there was always some problem. The
presented solution seems the least prone to errors since it doesn't
change the merging process (except using original target_branch name
instead of pr/{pr_id}) and only renames the target_branch to pr/{pr_id}
after the merge is done.
This change is needed to keep the consistency in NVRs (they show up as
pr{pr_id} in the %release field).
Related to #1443 #1445
---
Release notes are in #1445
=> merging PRs: PR into target, rename after

packit/upstream.py, packit/utils/changelog_helper.py
Fixes #1451
---
Bug in Packit while creating SRPMs when the `--no-bump` and `--release-suffix` options are ignored for source-git repositories has been fixed. Packit also doesn't touch `Release` field in specfile unless it needs to be changed (the macros are not expanded that way when not necessary).
=> Do not ignore --no-bump and --release-suffix for src-git repos

tests_recording/test_local_project.py
Make sure that the locally checked out PR has the same HEAD commit title
as the commit from main
We could also set up git-recording but this commit is a simpler fix.
Related to CI failures in https://github.com/packit/packit/pull/1454
---
N/A, tests fix
=> tests: check that merged PR matches main's HEAD

packit/utils/repo.py
When working with the worktree feature of git (`git worktree`), the
extra working trees don't get a .git directory, but rather a normal
file, with a single line that looks like
gitdir: /path/to/main/repo/.git/worktrees/abc
We're a bit too strict in our check requiring the current directory to
contain a file called ".git" and for it to be a directory: relax that
check to merely checking if ".git" exists, regardless of type.
=> Allow git trees with .git gitdir reference files

tests/integration/test_changelog_helper.py, tests/unit/test_specfile.py
Older versions of rpm raise an error if %changelog entries don't start
with a '*'. Any test which relies on the presence %autochangelog will
fail on this. Let's skip these tests if rpm < 4.16.
This should make the epel 8 tests pass.
---
None.
=> Skip %autochangelog tests if rpm < 4.16

packit/api.py, packit/cli/source_git.py, packit/cli/update_source_git.py, packit/local_project.py, tests/integration/test_source_git_update_source_git.py, tests/unit/test_local_project.py
Just a few notes about the problems I ran into while working on this and which directly influence the current state of the command:
- the check for patch changes is very simple, just an extension check for now. Taking the current dist-git spec file and using its patches for the checks is not sufficient as the patches may have been removed by a commit. If we wanted to be really precise with this check, we would have to check-out to each commit in the revision range and parse the spec file and its patches there, though I am not sure if that's what we want, seems a bit too complicated. Moreover, changing checkout on the provided local dist-git doesn't seem like very user-friendly IMO.
- GitPython manipulation with diffs is quite inconvenient, there is no way how to reconstruct the patch that …
=> Implement update-source-git command

setup.cfg
So that this is also correctly displayed on PyPI.
---
N/A
=> Update classifiers to mark support for Python 3.9 and 3.10

packit/cli/update_dist_git.py
The command is under 'source-git' now and does not require to explicitly
specify the package configuration.
---
n/a
=> Update the examples in the 'update-dist-git' help text

packit/constants.py, tests/unit/test_utils.py
For some commands used in prepare-sources, git user needs to be configured.
Tested with this change here: https://download.copr.fedorainfracloud.org/results/lbarczio/test-custom-source/srpm-builds/03265822/builder-live.log.gz
---
N/A
=> Configure git user and mail in the source script

packit/api.py, packit/cli/source_git_init.py, packit/source_git.py, tests/integration/test_source_git_init.py
Introduce a new command option for packit source-git init --no-require-autosetup.
If used, command will try to initialize the source git repository even if the
%autosetup is not used, which was previously not supported.
I am not sure from the issue description, whether something else needs to be done here or not.
Fixes #1425 
---
TBD
=> Introduce option for not requiring %autosetup for source-git init command

packit/patches.py, tests/unit/test_patches.py
I noticed that `source-git update-dist-git` didn't create a description of one patch from a source-git commit even it was correctly stated in the `Patch-status` git trailer. The cause was a colon in the description.
The previous code didn't expect a colon in a trailer value, which can easily happen either in the `Patch-status` or in `Patch-name` or in some future trailer that would accept a dictionary (we claim the values are YAMLs).
Initially, I wanted to use parsing/unfolding via `git interpret-trailers --parse`, because it'd simplify the parsing and because the YAML block scalars are a bit different from how git-interpret-trailers parses the multiline values per RFC 822, but eventually, I chose a less invasive solution.
---
Packit now correctly handles colons in git trailer values in …
=> Handle colon in git trailer values

.github/PULL_REQUEST_TEMPLATE.md
so we can easily parse them; zuul or github strip the dash separator from the merge commit
=> PR template: clearly mark release notes

packit/api.py, packit/config/common_package_config.py, packit/config/job_config.py, packit/config/package_config.py, packit/config/package_config_validator.py, packit/constants.py, packit/schema.py, tests/unit/test_package_config.py
Fixes #1357
---
Spec file and configuration file are no more automatically added to the list of files to sync when the new ```files_to_sync``` option is used. The old ```synced_files``` option is deprecated.
=> Syncing of default files can be disabled

packit/config/common_package_config.py, packit/config/job_config.py, packit/config/package_config.py, packit/schema.py, tests/unit/test_package_config.py
This will be used in packit-service for configuring dependencies for SRPM built in Copr.
Initially, I wanted to add the key into the `actions` section, but when looking into the config and schema validation, I think actions should really include only actions with predefined names, so I added it as a top-level key.
=> Add 'srpm_build_deps' configuration key for package config

packit/api.py, packit/base_git.py, packit/cli/source_git_init.py, packit/cli/update_dist_git.py, packit/cli/update_source_git.py, packit/constants.py, packit/source_git.py, tests/integration/test_source_git.py, tests/integration/test_source_git_init.py, tests/integration/test_source_git_update_source_git.py
Fixes #1472.
---
All `source-git`-commands were updated to append a `From-source-git-commit` or `From-dist-git-commit` Git-trailer to the commit messages they create in dist-git or source-git, in order to save the hash of the commits from which these commits were created. This information is going to be used to tell whether a source-git repository is in sync with the corresponding dist-git repository.
=> Update `source-git` commands to mark commit origin

packit/api.py, packit/cli/copr_build.py, packit/config/job_config.py, packit/schema.py, tests/integration/test_copr_build.py
- Add `enable_net` to configuration
- Add `--enable-net/--disable-net` to Copr build CLI
- Extend API to allow disabling of network during Copr build
Fixes #1386
We have added a new configuration option for Copr builds `enable_net` that allows you to disable network access during Copr builds. It is also complemented by `--enable-net/--disable-net` CLI options if you use Packit locally.
=> feat(copr): allow disabling of network for Copr builds

packit/config/common_package_config.py, packit/config/job_config.py
It will be used to differentiate the results of two similar jobs.
So you can e.g. build two packages from one repository (aka monorepo)
and the commit statuses will not collide.
Required for packit/packit-service#1385
Do you have a better name for the config option?
N/A
=> Add a new job config option for identifying the job

.pre-commit-config.yaml, files/install-requirements-pip.yaml, packit.spec, packit/config/aliases.py, packit/copr_helper.py, setup.cfg
When using LRU cache in service, we can encounter situations such as
deprecation of chroots and dist-git branches or their introduction
before release. In these cases it is required to redeploy the service,
since the targets/branches are cached. Switch to TTL cache with 12-hour
long expiration, so that the targets and branches are fetched once in 12
hours.
TODO:
Fixes #1303
We have switched the cache for dist-git branches and Copr targets to TTL cache that gets discarded once in 12 hours, in case there is a change in targets, the changes shall propagate to both of our deployments without the need to redeploy within 12 hours.
=> feat(aliases,copr): switch to TTL cache

packit/config/aliases.py
When reacting to event, we want to react even to branch that are under
alias, e.g. `rawhide` and `main`.
Related to packit/packit-service#1356
Merge before packit/packit-service#1393
N/A
=> feat(aliases): expand git aliases for events

packit/api.py, packit/config/aliases.py, packit/config/config.py, packit/distgit.py, packit/schema.py, packit/status.py, packit/utils/bodhi.py, tests/integration/test_create_update.py, tests/unit/test_config_aliases.py
Fixes: #1516 
When using Packit CLI for creating Bodhi updates, you can now set `fas_username` and `fas_password` in your Packit user config to not be asked about that when the command is executed.
=> FAS authentication for Bodhi

.packit.yaml
=> With the new `files_to_sync` key, the spec-file and Packit config needs to be set

packit/config/common_package_config.py, packit/config/job_config.py, packit/config/package_config.py, packit/schema.py
This will allow users to specify packit instances (=deployments) that will work on the service jobs.
(No release notes are needed. The feature will be documented in the service repo.)
N/A
=> Support for packit instances

files/tasks/rpm-test-deps.yaml
In the test image python3-flexmock was pinned to 0.10.4, "due to 0.10.5
causing some regression".
Being unable to tell what that regression was, let's try if things work
with the latest version (0.10.10).
Do this, b/c version 0.10.4 is no longer available from the Fedora
repositories.
=> fix(tests): Try the latest python3-flexmock

packit/copr_helper.py, tests/integration/test_copr_build.py
When creating a Copr repository, if necessary, check for already created
repository when creation fails. Should prevent premature failing due to
a race condition.
Fixes packit/packit-service#1403
Packit will no longer error out when trying to create a new Copr repository when it is already present (caused by a race condition).
=> fix(copr): do not error out for already created repo

packit/config/__init__.py, packit/config/common_package_config.py, packit/schema.py, tests/unit/test_package_config.py
B/c CommonPackageConfig.files_to_sync is a derived value, the meaning of
the original configuration can be re-established only by checking the
'_files_to_sync_used' attribute, and removing the 'files_to_sync' field
from the serialized data if it's False.
Fixes #1525.
=> Fix the files_to_sync field in the serialized object

.packit.yaml
And use the production instance for downstream jobs until
the staging one does not work.
N/A
=> Use both production and staging instance of Packit

.packit.yaml
Rawhide updates are created automatically,
but not for not-released branched versions.
We can use `fedora-latest` alias which is the latest non-rawhide branch.
It is not an issue if `fedora-latest` is covered also by `fedora-stable`,
Packit converts all the values to a set
so we don't need to worry about duplicates.
N/A
=> Create Bodhi updates for branched development version as well

packit/api.py, tests/integration/test_update.py, tests/unit/test_api.py, tests_recording/test_api.py
We want to run the actions after we have the correct state of the repository.
To make this work, we can't use the cloned revision of the spec-file as a source
for the version and need to use just a value from Anytia/UpstreamReleaseMonitoring.
If it is not found, the user needs to set the value manually.
In service, we know the tag so the version is not needed for checkout.
Relates to  #1413 / #1421
When using `post_upstream_clone` to generate your spec-file,
Packit now correctly checkout the release before the action is run.
=> Run `post_upstream_clone` action after the tag checkout

packit/local_project.py
Since we want to remove git-wrappers which are sometimes mocked (e.g.
LocalProject.reset() in packit-service), we need to provide an easy
mocking alternative. Mocking a method/property is more convenient than
having to force in an instance attribute.
I've tried adjusting `test_steve` inside p-s from
```python
flexmock(LocalProject).should_receive("reset").with_args("HEAD")
```
to
```python
head = flexmock()
head.should_receive("reset").with_args("HEAD", index=True, working_tree=True)
flexmock(LocalProject).should_receive("git_repo").and_return(
flexmock(head=head, git=flexmock(clear_cache=lambda: None))
)
```
and it seems to work.
Related to #343 
None
=> Add a property for git.Repo to LocalProject

.packit.yaml
Use upstream for creating issues about downstream Packit failures
See https://packit.dev/docs/configuration/#issue_repository
=> Use upstream for creating issues about downstream Packit failures

packit/config/aliases.py, tests/unit/test_config_aliases.py
Add a new alias, 'fedora-latest-stable', in order to be able to
reference the latest stable Fedora Linux release.
Add a new alias, 'fedora-branched', in order to be able to reference all
Fedora Linux releases, except 'rawhide'.
Fixes #1510.
Introduced two new build and test target aliases: 'fedora-latest-stable' resolves to the latest stable Fedora Linux release, while 'fedora-branched' resolves to all branched releases (all Fedora Linux release, except 'rawhide').
=> feat: Add new 'fedora-*' aliases

packit/copr_helper.py, tests/integration/test_copr_build.py
Fixes packit/packit-service#1425
We have reverted functionality of Packit that allowed you to have set «only» specific targets for Copr repositories. This functionality was introduced a while ago and was found to be not very beneficial in case of differently configured Copr jobs building in parallel in the same Copr repository.
=> fix(copr): do not overwrite chroots

packit/api.py, packit/base_git.py, packit/local_project.py, tests/integration/test_base_git.py
These were mostly unused aside from a few mocks so no point in keeping these oneline wrappers.
Related to #343
=> Remove the usage of git wrappers

packit/cli/utils.py
This was causing not overriding the config for the first job (index 0) defined in the config.
=> Fix condition for job_config_index in get_packit_api function

packit/api.py, packit/cli/propose_downstream.py, tests/integration/conftest.py, tests/unit/conftest.py, tests/unit/test_api.py
TODO:
From the security perspective, we have to decided to disable the `create_pr` option for our service, from now on Packit will unconditionally create PRs when running `propose-downstream`.
We have also updated the `propose-downstream` CLI such that it is possible to use `create_pr` from configuration **or** override it via `--pr/--no-pr` options.
=> feat: remove ‹create_pr› for service

packit/config/common_package_config.py, packit/config/job_config.py, packit/config/package_config.py, packit/schema.py, packit/upstream.py, packit/utils/source_script.py, tests/unit/test_upstream.py
When submitting SRPM build to Copr, we should be able to disable bumping
of the version and release field.
TODO:
Related to #1181
Merge before packit/packit-service#1478
Packit now supports `release_suffix` configuration option that allows you to override the long release string provided by Packit that is used to ensure correct ordering and uniqueness of RPMs built in Copr.
=> feat(copr): add bump-version to script generator

_packitpatch, packit/source_git.py, packit/utils/__init__.py, packit/utils/repo.py, tests/data/rpms/hello/from-git.patch, tests/integration/conftest.py, tests/integration/test_source_git_init.py
TODO:
When initializing source-git repos, the author of downstream commits created from patch files which are not in a git-am format is set to the original author of the patch-file in dist-git, instead of using the locally configured Git author.
=> source-git-init: Guess the author of non-git-am patches

_packitpatch, packit/base_git.py, packit/source_git.py, packit/utils/__init__.py, packit/utils/repo.py, tests/data/rpms/hello/from-git.patch, tests/integration/test_source_git_init.py, tests/integration/test_source_git_update_source_git.py
TODO:
Fixes #1491.
`packit source-git` commands learnt to replace [Git-trailers in commit messages](https://packit.dev/source-git/work-with-source-git/control-patch-generation/) if they already exist.
=> De-duplicate Git-trailers

tests/integration/test_upstream.py, tests_recording/test_api.py, tests_recording/testbase.py
RPM 4.18.0-alpha1 and above checks for the source archive to be found on
disk only during build time, instead of parse time. This though also
changed the error message when the source archive is missing when
building an SRPM: "Bad source" becomes "Bad file". See
https://github.com/rpm-software-management/rpm/commit/cd5d667e99f931504a512b591fcde7ed92cee344
Instead of chasing the change in wording, check for the part of the
error message which seems more future proof: "No such file or
directory".
This fixes the failing Testing Farm tests in Rawhide.
=> Adjust the expected error message for missing source archives

packit/specfile.py, tests/integration/test_spec.py
We need to keep track of the stretch with patch + its associated
comments correctly. Previously, the stretch was added to the new section
content when a blank line was hit, however this does not work when the
patches are not separated by blank lines in the preamble. Add the stretch
when a non-patch and non-comment line is found.
TODO:
The example given in the original issue still does not work correctly but this is caused by an unrelated rebase-helper bug. The rpm.spec is not parsed correctly and does not contain the patch application, hence a `KeyError` occurs in packit. However, the parsing works correctly with then new specfile library so I am not sure if it's worth fixing. Anyway, I will take a look in rebase-helper and try to find the root cause there if it is simple enough.
Fixes …
=> Fix removal of specfile patches

packit/config/common_package_config.py, packit/config/job_config.py, packit/config/package_config.py, packit/schema.py, tests/unit/test_config.py, tests/unit/test_package_config.py, tests/unit/test_prepare_sources.py, tests/unit/test_propose_downstream.py
Remove JobMetadataConfig from the code.
This PR removes also the support for the old osolete key dist-git-brach.
Usage of metadata key in the yaml files is still supported.
Mixing job->metadata->keys and job->keys it is not allowed.
Fixes packit#1515
Merge before packit/packit-service#1488
Metadata dictionary is no longer required when specifying a job.
Keys which used to belong to the yaml metadata dictionary are now keys of the job dictionary itself.
=> Remove JobMetadataConfig class

CHANGELOG.md, packit.spec
=> 0.51.0 upstream release

packit/config/package_config.py
When we cannot fetch the config file, because the GitHub App is not
installed on the repository, do not error out, just silently fail.
Fixes packit/packit-service#1462
Merge after packit/ogr#706
=> fix: do not error out when app is not installed

packit/api.py
If 'preserve_symlinks' is true, symlinks will be copied as symlinks.
Otherwise (the default), the destination of the symlink will be copied,
and it will raise an exception if the symlink is dangling.
Fixes packit/packit#1560
Packit will no raise Exceptions anymore when creating a SRPM with dangling symlinks. 
=> Do not raise an exception if symlink is broken

packit/config/job_config.py
The 'metadata' key was marked as deprecated in #1569.
=> Remove 'metadata' from the default jobs

packit/api.py, packit/config/package_config_validator.py, tests/integration/test_validate_config.py, tests/integration/test_validate_synced_files.py
When checking if the paths referenced in a package configuration file
(path of the specfile, paths of the files to be synced), make these
paths relative to the path of the project.
This fixes an issue, where
packit validate-config src/systemd
was reporting the specfile and the files to be synced as missing,
although all of them were to be found in 'src/systemd/.distro'.
TODO:
=> Check the paths in the package config relative to the project path

.packit.yaml
The key is deprecated and can be removed.
=> Remove 'metadata' from .packit.yaml

packit/local_project.py
When checking out PR during preparation of sources (in Sandcastle or Copr),
we use `git_service` to correctly determine remote git reference. When
running in Copr, we have neither git project or git service, therefore in
such case, fall back to the ogr's parsing of git URL to acquire expected
service class.
TODO:
=> fix(local_project): check forge against project

packit/config/package_config.py, packit/schema.py, tests/integration/test_validate_config.py
This was causing the 'targets' and 'dist_git_branches' fields to be
considered invalid if their values were strings instead of lists.
Fixes #1605.
Fixed a regression where string values for the 'targets' and 'dist_git_branches' configuration keys was not accepted.
=> Fix checking for dict type during validation

packit/constants.py, packit/distgit.py, packit/status.py, tests/integration/test_create_update.py
Fixes packit#1475
Creation of a Bodhi update will no more timeout.
=> Use Koji instead of Bodhi to get the tag latest build

.packit.yaml
We run propose-downstream for both prod and stg, so this way we can merge any of the created PRs.
N/A
=> Add packit to allowed_pr_authors for Koji builds

packit/config/common_package_config.py, packit/config/job_config.py, packit/schema.py, tests/unit/test_package_config.py, tests/unit/test_prepare_sources.py
Adding some extra parameters to the JobConfig to be submitted to the TF API.
The parameters are:
* tmt_plan_regex: Specify a regex to run only a specific set of tests.
* tf_post_install_script: Specify bash commands to run in TF after
installation.
Fixes #1600 
Signed-off-by: Rodolfo Olivieri <rolivier@redhat.com>
TODO:
I changed the way the json is represented in one of the unit_tests, let me know if it's okay to be in that way (looks nicer now). If not, I can change it back!
=> Add extra parameters to the JobConfig

packit/upstream.py, tests/integration/test_upstream.py
TODO:
`Path.relative_to` can raise `ValueError` when `specfile_dir` is in a
subdir and archive path is in the project's root. This commit uses
`os.path.relpath` instead that supports having the source path in a
subdir. It's a different implementation than `.relative_to`.
Fixes: https://github.com/packit/packit/issues/1621
Packit now correctly handles creation of custom archives in root while a specfile is in a subdirectory.
=> allow having custom archives in root while specfile is in a subdirectory

packit.spec, packit/api.py, setup.cfg, tests/integration/test_using_cockpit.py
This makes the implementation consistent with the docstring meaning that
a PR is returned if create_pr=True. The usage of such implementation is
easier in a sense that if create_pr is set to True and no exception was
raised, the caller can expect a valid PR to be returned which was not
the case previously and lead to surprising tracebacks.
Also make the typing stricter by using overloads for the literal
create_pr values.
Signed-off-by: František Nečas <fnecas@redhat.com>
TODO:
Fixes https://github.com/packit/packit-service/issues/1504
(lets see if github can close issues in another repo)
=> Return existing PR from sync_release

setup.cfg
This makes sense as it's only used when Python < 3.8.
=> Require typing-extensions only when Python < 3.8

.packit.yaml
if any of the targets fail to build, the whole build fails
packit-stable is used in our SRPM build env
=> packit-stable: use fedora-stable instead of fedora-all

packit.spec, setup.cfg
`bodhi-client` no longer depends on `python-fedora`, so it is necessary to declare the dependency explicitly.
=> Add missing python-fedora dependency

packit/api.py, packit/base_git.py
This is a simle UX change.
Helps with https://github.com/packit/packit/issues/1625
```
This also adds an info log line when Packit checks out the original
branch on which the user ran the command. If something wrong happens,
this should be the last log and could help the user diagnose the
problem.
```
Git ref name that Packit works with during `propose-downstream` is now made more obvious in logs.
=> provide ref name when specfile cannot be found

packit/distgit.py, packit/utils/bodhi.py, tests/integration/test_create_update.py
The problem is the code path for creating bodhi updates before this
commit would not go through the Kerberos route which meant it would
prompt in terminal - that doesn't work in a worker:
https://sentry.io/organizations/red-hat-0p/issues/3422419746/?referrer=github_integration
With this change, once we init the bodhi_client before creating updates, we
also make sure the auth is obtained using Kerberos.
Fixes #1650
Packit can now correctly create bodhi updates using the new Bodhi 6 client.
=> bodhi: initialize auth before creating updates

README.md
I think making logo smaller and aligned to center makes README look better.
Preview:
=> Format logo in README

packit/api.py, packit/cli/build.py, packit/cli/builds/__init__.py, packit/cli/builds/copr_build.py, packit/cli/builds/koji_build.py, packit/cli/builds/local_build.py, packit/cli/packit_base.py, tests/functional/test_local_build.py, tests/integration/test_copr_build.py
TODO:
RPM build commands of Packit CLI have been merged into one `build` subcommand, for more information see the updated documentation at https://packit.dev/docs/cli/build/. We have also introduced a new `--srpm` option to the new `build` subcommand that can be used to trigger local, Copr or Koji build from an already built SRPM rather than implicitly created one by Packit.
=> Build refactor

packit/config/common_package_config.py, packit/config/job_config.py, packit/distgit.py, packit/schema.py, tests/unit/test_package_config.py
context: https://github.com/packit/research/tree/main/image-builder
TODO:
- ~~Update or write new documentation in `packit/packit.dev`.~~ no need to document
Also not adding any release notes since this cannot be used by our users.
one small fix:
```
change LoginRequiredError to BodhiClientException
that's what bodhi_client now throws:
https://github.com/fedora-infra/bodhi/blob/3437e506509ea3d4ad06035931a7cd0a9e9eba2f/bodhi-client/bodhi/client/bindings.py#L228-L232
```
=> add vm-image-build job

packit/schema.py
These two options were missing from the Job schema, hence an error was
thrown when it was used in a config.
Fixes: https://github.com/teemtee/upgrade/pull/3#issuecomment-1191339590
Packit now correctly supports `tmt_plan` and `tf_post_install_script` in the configuration.
=> Add tmt_plan and tf_post_install_script to schema

packit/distgit.py
Fixes: https://github.com/packit/packit-service/issues/1587
Real issue: https://github.com/fedora-infra/bodhi/issues/4660
Luckily we don't need to change versions in requirements:
* In service we explicitly install bodhi 5: https://github.com/packit/packit-service/pull/1590
* For CLI users: Packit CLI can work with both Bodhi client versions, users need to downgrade manually
Packit now provides a more helpful error message when it hits a known issue while creating a Bodhi update: https://github.com/fedora-infra/bodhi/issues/4660
=> Provide a better error message for bodhi#4660

files/tasks/generic-dnf-requirements.yaml
```
Here's the dependency stack:
reverse-dep-packit-service-tests zuul job
⮩ packit-tests-pip-deps zuul job
⮩ install-requirements-pip.yaml playbook
⮩ generic-dnf-requirements.yaml playbook
```
Hence the bodhi client is installed much sooner than in the actual
playbook for the rev-dep test. This is not obvious from the Zuul
interface.
=> CI: force installation of bodhi 5 client

packit/upstream.py
When building RPMs in mock, the final RPM packages are present in the
result dir. Change the current implementation that prints out only the
names of the RPMs to printing whole paths to the RPMs.
=> fix(mock): print whole path of built RPMs

files/zuul-reverse-dep-packit-service.yaml, packit/config/package_config.py, packit/config/package_config_validator.py, packit/schema.py, tests/unit/test_package_config.py
Previously the repo (local or the forge) was recursively searched for
the specfile _before_ calling PackageConfig.get_from_dict(), and any
specfile found was passed on to the method.
This works, if there is a single package and specfile in the repo.
Introducing monorepo support though requires the ability to tell which
paths of the repo to search for the specfile. These paths won't be
available only after the configuration is parsed.
In order to avoid exposing parsing the config outside of PackageConfig,
call the search functions in PackageConfig.get_from_dict(), which should
enable implementing monorepo support.
This also introduces a BREAKING CHANGE, and aligns detecting
'specfile_path', according to the documentation:
1. Use specfile_path, if defined.
2. Use …
=> refactor!: search the repo for the specfile in PackageConfig

packit/upstream.py, packit/utils/upstream_version.py, tests/unit/test_utils.py
This is another step towards removing `rebasehelper` dependency.
=> Get upstream versions using release-monitoring.org API

packit/utils/decorators.py
=> Correctly catch Exception subclasses not instances

packit/upstream.py, tests/integration/test_upstream.py, tests/unit/test_upstream.py
TODO:
fix_spec can change a specfile and if it's no reloaded the changes are
discarded
Example: https://dashboard.packit.dev/results/srpm-builds/81313
Action `fix_spec_file` can change a spec file - Packit now preserves that change.
=> reload specfile after running fix_spec action

packit.spec, packit/base_git.py, packit/distgit.py, packit/exceptions.py, packit/source_git.py, packit/utils/lookaside.py, setup.cfg, tests/integration/conftest.py, tests/unit/test_base_git.py, tests/unit/test_utils.py
Packit now uses (py)rpkg instead of rebasehelper to parse "sources" files in dist-git repos and to interact with lookaside cache.
=> Use (py)rpkg to interact with lookaside cache

packit/utils/upstream_version.py, tests/unit/test_utils.py
It turns out my assumption about rate limiting on v2 API was incorrect, @Zlopez confirmed there is no rate limiting in place and I haven't been able to reproduce the test failures since, so it was most likely some sort of a temporary network hiccup.
=> Switch to release-monitoring.org API v2

packit/copr_helper.py, tests/integration/test_copr_build.py
When editing Copr projects, we have been catching CoprRequestException
and based on that handling the situation when Packit has lack of permissions
to update a Copr project. Copr API now raises CoprAuthException for this case,
therefore the exception we catch is changed here to CoprAuthException.
Fixes packit/packit-service#1613
We have fixed the handling of the situation when Packit lacks permission to update a Copr project.
=> Update the Copr exception we catch when editing Copr project

packit/api.py, packit/cli/prepare_sources.py, packit/upstream.py, packit/utils/source_script.py, tests/integration/test_upstream.py, tests/unit/test_utils.py
TODO:
Fixes #1637 
Packit `prepare-sources` command now has the `--create-symlinks/--no-create-symlinks` option, which enables copying the archive instead of symlinking. This will be used in the Copr environment, where symlinking the archive previously caused issues.
=> Prepare sources symlinks

packit/api.py, packit/cli/utils.py, packit/config/common_package_config.py, packit/distgit.py, tests/integration/conftest.py
'dist_git_clone_path' is a context dependent value, so instead of
storing and passing around in the package configuration, turn it into an
argument.
TODO:
Related to #1616.
=> Remove 'dist_git_clone_path' from CommonPackageConfig

.packit.yaml, packit/api.py, packit/cli/build.py, packit/cli/builds/copr_build.py, packit/cli/builds/in_image_builder.py, packit/cli/builds/koji_build.py, packit/cli/utils.py, packit/config/common_package_config.py, packit/config/config.py, packit/copr_helper.py, packit/schema.py, packit/vm_image_build.py, tests/integration/test_copr_build.py, tests/unit/test_image_builder.py, tests/unit/test_package_config.py, tests_recording/test_data/test_image_builder/TestLocalProject.test_get_token.yaml, tests_recording/test_data/test_image_builder/TestLocalProject.test_token_auto_refresh.yaml, tests_recording/test_image_builder.py
TODO:
```
$ packit build in-image-builder --help
Usage: packit build in-image-builder [OPTIONS] IMAGE_NAME [PATH_OR_URL]
Create a VM image in Image Builder.
Packit loads image build configuration from your packit.yaml file.
When `--job-config-index` is not specified, the job configuration is loaded
from your .packit.yaml and the first matching vm_image_build job is used.
IMAGE_NAME is the name of the image to be created. Please pick something
unique so it's easy to identify for you in the Image Builder interface and
can be well associated with the image content.
[PATH_OR_URL] argument is a local path or a URL to the upstream git
repository, it defaults to the current working directory
Options:
--job-config-index INTEGER  Use N-th job definition to load configuration
for the image build. …
```
=> implement `packit build in-image-builder`

packit/api.py
While in a propose downstream task, sources in repo can be changed by user actions.
After task is completed, force switch to the main repo branch.
Fixes packit/packit-service#1580
No more annoying issues will be created after a successfull propose downstream.
=> Force clean workdir after propose downstream

packit/distgit.py
instead of previous
```
2022-08-25 11:39:52.881 api.py            INFO   Using 'rawhide' dist-git branch.
100%[=============================>]    42.37K  eta 00:00:00
2022-08-25 11:40:00.760 utils.py          ERROR  Upstream archive was not downloaded. Something is wrong.
```
it now prints
```
2022-08-25 11:39:52.881 api.py            INFO   Using 'rawhide' dist-git branch.
100%[=============================>]    42.37K  eta 00:00:00
2022-08-25 11:40:00.593 distgit.py        INFO   Downloading archive: fedora-license-data-1.2.tar.gz
2022-08-25 11:40:00.760 utils.py          ERROR  Upstream archive was not downloaded. Check that fedora-license-data-1.2.tar.gz exists in dist-git.
```
packit propose-downstream is now more informative when sources cannot be downloaded. …
=> more descriptive log in download_upstream_archive()

.github/workflows/opened-issues-to-the-board.yml
So we try it is not an issue when trying to find it. (https://github.com/packit/packit/runs/8208141368?check_suite_focus=true)
=> Remove the spaces from a Kanban board name

packit/api.py, packit/config/aliases.py, packit/status.py, tests/integration/test_push_updates.py, tests/unit/conftest.py, tests/unit/test_status.py
Results of Bodhi API queries can be paginated, in such case it is necessary to retrieve all pages.
Fixes: packit/packit-service#1642
=> Account for pagination in Bodhi API

packit/config/job_config.py, tests/integration/test_get_api.py, tests/unit/test_config.py, tests/unit/test_package_config.py
Deprecate also the `build` alias since it's too generic.
Related to: #1658
Merge before: packit/packit-service#1656
... no release notes here, will be covered in the service PR
=> Deprecate `production_build` in favour of `upstream_koji_build`

packit/distgit.py
see the first point in [this comment](https://github.com/packit/packit-service/pull/1654#issuecomment-1248236973)
Related to [packit-service#1654](https://github.com/packit/packit-service/pull/1654)
=> Fix(distgit): make method get_latest_build_in_tag to be static

packit/api.py, packit/base_git.py, tests/integration/test_using_cockpit.py, tests_recording/README.md, tests_recording/test_api.py, tests_recording/test_data/test_image_builder/TestLocalProject.test_get_token.yaml, tests_recording/test_data/test_image_builder/TestLocalProject.test_token_auto_refresh.yaml
Previously, when [doing propose downstream](https://github.com/packit/packit/blob/41a74aefaa6a7d07f2559513c0d454d082b1efdd/packit/api.py#L690), we checked for an already existing PR, and only if there was none, we pushed changes to a fork and created a new PR. Initially, the checking for already existing PR had been added in #994 in order to prevent creating multiple PRs if more propose-downstream jobs are triggered (packit/packit-service#785).
This prevents us from updating an already existing PR (packit/hardly#76), so with this change, we first push to a fork, which might update an already existing PR, and then we check whether we actually need to create a new PR or if there already is one.
In https://github.com/packit/packit/pull/994#discussion_r508371788 @lachmanfrantisek thought that …
=> Push to fork before checking for existing PR

packit/copr_helper.py
Add method that returns set of chroots configured on the given Copr
project.
TODO:
Related to packit/packit-service#1499
Merge before packit/packit-service#1530
=> feat(copr): add method for getting chroots

packit/copr_helper.py
Related to packit/packit-service#1684.
=> Correctly chain PackitCoprProjectException when creating Copr project

.github/workflows/pypi-publish.yml
When `python -m build` is invoked with `--sdist` and/or `--wheel` args, both artifacts get created from source. This is bad because it differs from what pip does when it needs to build a package from the source distribution before installation.
Without said args, the `build` tool will first create an sdist from your Git checkout and then, it'll create a wheel out of that tarball, just like pip does. This helps catch cases when the contents of sdist is not enough to produce a working binary distribution, or when the resulting artifact differs a lot from the result of a build derived from a Git checkout.
This patch addresses the above issue per the best practices.
=> Smoke-test wheel creation from sdist

packit/api.py, packit/cli/create_update.py, packit/distgit.py, packit/utils/bodhi.py, tests/integration/test_create_update.py, tests/integration/test_push_updates.py
TL;DR upstream bodhi.ensure_auth caches an auth cookie and this is
required for the auth to work properly
long story: since the upstream ensure_auth() was not run, bodhi_client
and bodhi_server did not treated us as authenticated, hence the error
message:
Unauthorized: new_update__POST failed permission check...
Therefore, after we login via kerberos, we need to complete the
authentication with upstream bodhi_client.ensure_auth to obtain the auth
cookie.
There is also no point in being smart about the auth process as bodhi
handles it completely.
TODO:
Fixes packit/packit-service#1681
Packit can now correctly authenticate with Bodhi 6 and therefore create Bodhi updates. 🚀
=> fix(bodhi): properly authenticate via kerberos with bodhi 6

packit/api.py, packit/cli/create_update.py, packit/cli/push_updates.py, packit/distgit.py
only use Kerberos when fas_user and kerberos_realm are set in user's
packit.yaml
In theory, we could check if kerberos session is active but let's keep
this strict in the meantime.
Blocks #1748
No release notes as this bug wasn't released to users.
N/A
=> fix(bodhi kerberos auth): use only when configured

packit/upstream.py, packit/utils/changelog_helper.py, tests/integration/test_changelog_helper.py, tests/integration/test_upstream.py, tests/unit/test_upstream.py
Fixes packit#1695
The actual behaviour table: https://gist.github.com/majamassarini/f2ebf6a78ca8af189208e77074a16dff
Version and revision are no more updated in  `SPEC` files when the `--no-bump` flag is specified and `None` revisions are no more created.
=> Fix release_suffix behaviour

packit/config/package_config.py, tests/unit/test_package_config.py
TODO:
yaml.safe_load returns None for files that are "empty", example:
The way we loaded a config from repo resulted passing None instead of a
Dict, which caused weird `"'NoneType' object has no attribute 'get'"`
errors.
This commit changes this behavior: None is changed into `{}` and Packit
now returns an error that specfile cannot be found if there is none in
the repo.
Thank you for your help here, @csomh!
Fixes #1768
When packit.yaml is present in the repo but is empty, Packit now produces a better error message instead of an internal Python exception.
=> Correctly process empty configs loaded remotely

packit/config/job_config.py, packit/schema.py, tests/unit/test_package_config.py, tests/unit/test_prepare_sources.py
This was the case before, but the latest revamp if the configuration schema and classes caused it to regress. Tests did not catch it because 'downstream_package_name' was set, which caused 'specfile_path' to be implicitly set.
Resolves #1767.
TODO:
Fixed a regression in configuration schema, which caused test-only job configs without a 'specfile_path' to be considered invalid.
=> fix: accept a missing 'specfile_path' in test-only jobs

README.md, packit/api.py
We support Python 3.9 and above now.
=> Remove Python 3.6 compatibility code from 'packit status'

packit/api.py, packit/base_git.py, packit/config/common_package_config.py, packit/distgit.py, packit/pkgtool.py, packit/upstream.py, packit/utils/changelog_helper.py, tests/data/upstream_git/beer.spec, tests/integration/conftest.py, tests/integration/test_update.py, tests/integration/test_upstream.py, tests/integration/test_using_cockpit.py
TODO:
The heuristic for detecting which Sources go to lookaside is insufficient. Some cases to consider are in https://docs.fedoraproject.org/en-US/packaging-guidelines/SourceURL/#_troublesome_urls  https://docs.fedoraproject.org/en-US/packaging-guidelines/SourceURL/#when-upstream-uses-prohibited-code (those two can be solved by specifying the problematic Source as `spec_source_id`, if it is not Source0 already) and in  https://docs.fedoraproject.org/en-US/packaging-guidelines/#_verifying_signatures . For implementing complicated rules like in the latter one will probably need another configuration option that will list sources that need to go to lookaside.
The change is mostly compatible, although packages that have other Sources than 0 (or spec_source_id) specified as URLs and don't …
=> Multi-source RPM support in propose-downstream

packit/api.py, packit/base_git.py, tests/integration/test_update.py
So that the method can be used by pull from upstream in service where it is possible that the upstream doesn't have any specfile.
TODO:
Related to packit/packit-service#1578
=> Add use_downstream_specfile for sync_release

.github/workflows/build-and-push.yml, .github/workflows/do_release.yml, .github/workflows/prepare-release.yml, .github/workflows/pypi-publish.yml, files/install-requirements-git.yaml, files/install-requirements-pip.yaml, files/install-requirements-rpms.yaml, files/local-tests-requirements.yaml, files/packit-testing-farm-prepare-session-recording.yaml, files/packit-testing-farm-prepare.yaml, files/tasks/project-dir.yaml, files/zuul-reverse-dep-packit-service.yaml, files/zuul-tests-session-recording.yaml, files/zuul-tests.yaml
Both, the [packit/prepare-release](https://github.com/peter-evans/create-pull-request#action-inputs) & [peter-evans/create-pull-request](https://github.com/packit/prepare-release#packitprepare-release) default to using (autogenerated) [secrets.GITHUB_TOKEN](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) if no token is provided.
That token should be enough because the steps are repo-scoped and [don't trigger any other workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow) since the PR which triggers the 'Create GitHub release' is manually merged by a user.
Seems to work OK - jpopelka/packit#1
=> Use github-actions bot to run prepare-release steps

files/tasks/packit-service-requirements.yaml
To match the version used in service tests
=> Use up-to-date version of flexmock from PyPI

packit/base_git.py, tests/unit/test_base_git.py
The changelog entry contains the release number, therefore we need to reset the Release before adding a new entry to the changelog to avoid inconsistencies.
@pcahyna sorry once again, this should fix your problem
TODO:
Related to #1801 
Packit now puts the correct release number into the changelog when the `Release` tag is reset during `propose-downstream`.
=> Reset Release before adding changelog entry

packit/api.py, packit/base_git.py, tests/integration/test_update.py, tests/unit/test_dg.py
Pull-from-upstream finally in action: https://src.fedoraproject.org/fork/packit-stg/rpms/python-specfile/c/580fddc01336518418cf98e5d202614249d62536?branch=0.11.1-f37-update-pull_from_upstream
But there were 2 issues: since we had already PRs from propose-downstream, the check for existing PR caused the PRs were not created (but the branches with `-pull_from_upstream` suffix were created and updated). 
The second issue was that the specfile was synced correctly only for the first branch run- runs for each next branch were using the previous specfile: e.g. https://src.fedoraproject.org/fork/packit-stg/rpms/python-specfile/c/937262afa09978a46936ad0c18e29639044462d0?branch=0.11.1-epel9-update-pull_from_upstream - therefore the duplicated most recent entries.
N/A
RELEASE …
=> Sync release -  improvements for pull

setup.cfg, setup.py
so the version is always higher when we build our packages in the stable
project
The problem:
$ rpmdev-vercmp 0.65.1.dev7+gbf5a556-1.20221219130111363621.stable.7.gbf5a556   0.65.1-1.20230102134429552639.stable.0.geda9ca7
0.65.1.dev7+gbf5a556-1.20221219130111363621.stable.7.gbf5a556 > 0.65.1-1.20230102134429552639.stable.0.geda9ca7
Even though the latter VR was built later, RPM treats it as older.
The solution:
$ rpmdev-vercmp 0.65.0.post1+g9c8cbdc.d20230105-1.20221219130111363621.stable.7.gbf5a556 0.65.1-1.20230102134429552639.stable.0.geda9ca7
0.65.0.post1+g9c8cbdc.d20230105-1.20221219130111363621.stable.7.gbf5a556 < 0.65.1-1.20230102134429552639.stable.0.geda9ca7
$ rpmdev-vercmp 0.65.1.post1+g9c8cbdc.d20230105-1.20221219130111363621.stable.7.gbf5a556 0.65.1.post2+... …
=> fix(setup.py): don't bump dev versions

packit/base_git.py
`Specfile.add_changelog_entry()` accepts a list of lines, so providing that rather than a string will ensure that the resulting changelog entry will always have the same line endings, no matter the source.
This should prevent unwanted diff chunks with mixed line endings in propose-downstream PRs, like here:
https://src.fedoraproject.org/rpms/python-specfile/pull-request/120#_6__20-21
Fixes: #1807
=> Sanitize newlines in changelog entries

packit/constants.py, packit/copr_helper.py, packit/schema.py, tests/unit/test_config.py, tests/unit/test_copr_helper.py
namely, all the `additional_*`
Detailed and well written ask from @evgeni:
https://github.com/packit/packit/issues/1429#issuecomment-1373209874
Fixes #1429
I thought about the design what exactly should we pass from p-s to `create_copr_project_if_not_exists`.
The problem is that job_config causes a circular dependency (aliases require copr_helper).
TODO:
Target-specific configuration for Copr builds can now be defined and Packit will set it for the appropriate Copr chroots.
=> feat(copr): enable configuring chroot-specific options

packit/constants.py, packit/copr_helper.py, packit/schema.py, tests/unit/test_config.py, tests/unit/test_copr_helper.py
not a list as the API used to imply
Related: https://github.com/fedora-copr/copr/pull/2465
The PR above fixes Copr's side
TODO:
When configuring Copr chroot (target in Packit terminology) specific configuration, make sure to specify additional_modules as a string: module names separated with a comma, example: "httpd:2.4,python:4".
=> fix(chroot-conf): utilize addtional_modules as a string

packit/api.py, packit/cli/builds/copr_build.py, packit/config/common_package_config.py, packit/copr_helper.py, packit/schema.py, tests/integration/test_copr_build.py, tests/unit/test_package_config.py, tests_recording/test_data/test_api/ProposeUpdate.test_changelog_sync.yaml, tests_recording/test_data/test_status/TestStatus.test_dowstream_pr.yaml
This allows upstreams who are packaged as a module to provide copr projects that can provide packages which are considered in modular context.
See https://dnf.readthedocs.io/en/latest/modularity.html#hotfix-repositories
TODO:
Fixes
Related to
Packit now supports setting `module_hotfixes` for Copr projects.
=> feat(copr): expose `module_hotfixes` project setting via packit

.zuul.yaml
This reverts commit 7748ba93a63b5a91af4063cca92d1fdeb55a5e27.
I'm a bit puzzled but from #1830 it looks like it actually works OK now.
=> Revert "Temporarily run packit-tests on f35"

tests/integration/test_changelog_helper.py
There is a `%_changelog_trimage` macro that limits the age of processed changelog entries and is defined to be 2 years in Fedora:
https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/rawhide/f/macros#_393
There is also a `%_changelog_trimtime` macro that also limits the age of processed changelog entries and is defined to be 2 years in EL 9:
https://gitlab.com/redhat/centos-stream/rpms/redhat-rpm-config/-/blob/f14ea70dac7c0aeab840cda017d2891c488d8e25/macros#L345
Redefine both of them to zero so that all entries are processed and the check can be enabled.
Related to #1841.
=> Enable the check for changelog entries count in test_update_distgit_unsafe_commit_messages

packit.spec, packit/api.py, packit/distgit.py, packit/utils/bodhi.py, setup.cfg, tests/integration/test_create_update.py, tests/integration/test_push_updates.py, tests/unit/test_login_with_kerberos.py, tests/unit/test_status.py
...over the one we had in Packit and contributed back. It's available as
of bodhi 7.0.0 release.
Fixes #1638
TODO:
Packit now requires bodhi in version 7.0.0 at minimum.
=> chore(bodhi): utilize upstream bodhi functionality

packit/cli/source_git_status.py, packit/cli/update_dist_git.py, packit/cli/update_source_git.py, packit/config/package_config.py, packit/constants.py, packit/exceptions.py, packit/schema.py, tests/integration/conftest.py, tests/unit/test_package_config.py
Instead of looping through the list of possible package-config file
names and trying to load them one by one, get the list of files in the
repo root and take one which matches one of the expected config file
names.
This way the number of API calls required to load a config file (or find
out that there is no such file) is reduced from
len(CONFIG_FILE_NAMES) to one.
TODO:
Related to packit/packit-service#1765
Packit does fewer API calls when searching for the package configuration file in remote repositories.
=> Improve searching for a package config in a remote repo

packit/upstream.py
Since packaging 22.0, `version.parse()` no longer accepts an empty string and throws an exception. Avoid that by failing early when the latest released version can't be determined.
Fixes #1855.
=> Do not try to parse empty version

packit/config/aliases.py
Fedora Linux 35 is EOL already. Fedora Linux 38 was branched.
Without this mapping being up to date, alias resolution can produce an incorrect result in case aliases cannot be resolved with the help of Bodhi. Even a network glitch can cause this.
Resolves #1860.
=> Update the alias mapping for Fedora Linux

packit/config/package_config.py
Previously it printed:
```
2023-02-23 16:23:13.305 package_config.py ERROR  Cannot load package config /tmp/fedora-upgrade/.packit.yaml.
2023-02-23 16:23:13.305 utils.py          ERROR  Cannot load package config: ScannerError('while scanning for the next token', None, "found character '\\t' that cannot start any token", <yaml.error.Mark object at 0x7f3310e2a190>).
```
Now it prints:
```
2023-02-23 17:25:59.950 package_config.py ERROR  Cannot load package config /tmp/fedora-upgrade/.packit.yaml.
2023-02-23 17:25:59.950 package_config.py ERROR    parser says
in "<unicode string>", line 12, column 1:
- fedora-stable
^
found character '\t' that cannot start any token while scanning for the next token
2023-02-23 17:25:59.950 utils.py          ERROR  Please correct data and retry.
```
TODO:
- …
=> better wording when packit cannot parse YAML file

packit/config/aliases.py, tests/unit/test_config_aliases.py
example for F38:
```
Munch({'name': 'F38', 'long_name': 'Fedora 38', 'version': '38', 'id_prefix':
'FEDORA', 'branch': 'f38', 'dist_tag': 'f38', 'stable_tag': 'f38',
'testing_tag': 'f38-updates-testing', 'candidate_tag': 'f38-updates-candid
ate', 'pending_signing_tag': 'f38-signing-pending', 'pending_testing_tag':
'f38-updates-testing-pending', 'pending_stable_tag': 'f38-updates-pending',
'override_tag': 'f38-override', 'mail_template': 'fedora_errata_template',
'state': 'frozen',
'compose d_by_bodhi': True, 'create_automatic_updates':
False, 'package_manager': 'unspecified', 'testing_repository': None, 'eol':
None})]
```
It seems that bodhi now sets state to 'frozen' for the upcoming release
(after beta?)
TODO:
Related: https://github.com/packit/packit/issues/1860 …
=> fix(aliases,bodhi): account for state frozen

packit/config/package_config.py
If the `package_config_path` **is not** specified as an argument of this function and there's no package config in the repo the `find_remote_package_config()` returns `None` and we return `None` as well.
But if the `package_config_path` **is** specified, and there's no package config in the repo the first time we realize that there's no such file is when we try to get its content.
Fixes: https://red-hat-it.sentry.io/issues/3966122790
=> Return None if package_config_path is not found in the repo/ref

packit/config/package_config_validator.py, tests/integration/test_validate_synced_files.py
TODO:
'packit validate-config' now correctly checks glob-patterns in 'files_to_sync'.
=> validation: Consider globs when validating the files to sync

tests/unit/test_api.py, tests_recording/test_api.py
A follow-up to #1858.
"some.version" is not a parseable version in packaging 22.0 and newer, replace it with zero that is effectively the same value.
=> Use parseable version in tests

.packit.yaml
Configure Packit to build and test in all Fedora versions in PRs, in order to be in line with how Packit is built in the main an stable branches.
=> Enable building and testing all Fedora versions in PRs

packit/base_git.py
When downloading sources from the remote, remote may have a protection against crawlers, etc. and deny generic user agent provided by the requests.
Specify explicitly user agent with a reference to the Packit.
Related to packit/packit-service#1948
TODO:
Related to packit/packit-service#1948
=> fix: specify User-Agent when downloading sources

packit/cli/source_git_status.py, packit/cli/types.py, packit/cli/update_dist_git.py, packit/cli/update_source_git.py, packit/distgit.py, packit/local_project.py, packit/upstream.py, tests/integration/conftest.py, tests/integration/test_base_git.py, tests/integration/test_get_api.py, tests/integration/test_upstream.py, tests/integration/test_using_cockpit.py, tests/integration/test_using_examples.py, tests/unit/conftest.py, tests/unit/test_api.py, tests/unit/test_base_git.py, tests/unit/test_dg.py, tests/unit/test_local_project.py, tests_recording/testbase.py
Opening a pull request even though the work is not completely done yet (though fairly close) to allow for some early feedback + see if the changes don't somehow break packit-service based on reverse-dep tests.
The plan is to transition gradually, so I haven't removed the old `LocalProject` construction just yet, once this PR is merged, I will update p-s and hardly to use the builder and only then drop the parsing/refreshing from `LocalProject`
TODO:
=> Implement LocalProjectBuilder class

packit/upstream.py
The [`get_current_version`](https://github.com/packit/packit/blob/f18369ebcfbf9207f771fb1e9ec8e6c4b4467318/packit/upstream.py#L263-L266) method is already using the user action as first step. I have done the same with the `get_version` method. 
Fixes packit/packit#1859
Now packit uses the `get_current_version` action defined by the user to retrieve version before updating the specfile %setup macro (if any).
=> Get version from action if defined

packit/upstream.py, tests/integration/test_upstream.py
With this it becomes possible to have earlier tags, which do not match the upstream tag template, ignored, and only the tags matching the pattern considered when determining the current version.
Resolves #1885.
TODO:
'upstream_tag_template' is now also used when looking for the latest version tag in Git. This allows upstream repositories to mix different tag-patterns in the same repository, but consider only one to tell the latest version.
=> Use '--match' when looking for the version tag in git

packit/api.py, tests/integration/conftest.py
The called `update_source_git()` expects the dist-git repo to be already switched to the branch we want to sync from.
Required for packit/hardly#92
=> PackitAPI.sync_push() checkouts dist-git branch as well

packit/base_git.py, tests/unit/test_base_git.py
Fixes #1879.
Packit now preserves `%autorelease` during `propose_downstream` and `pull_from_upstream`.
=> Support %autorelease in `set_specfile_content()`

packit/api.py, packit/cli/builds/copr_build.py, packit/cli/builds/in_image_builder.py, packit/cli/builds/koji_build.py, packit/cli/builds/local_build.py, packit/cli/builds/mock_build.py, packit/cli/create_update.py, packit/cli/prepare_sources.py, packit/cli/propose_downstream.py, packit/cli/source_git_status.py, packit/cli/srpm.py, packit/cli/status.py, packit/cli/sync_from_downstream.py, packit/cli/update_dist_git.py, packit/cli/update_source_git.py, packit/cli/utils.py, packit/config/__init__.py, packit/config/common_package_config.py, packit/config/job_config.py, packit/config/package_config.py, packit/config/package_config_validator.py, packit/constants.py, tests/unit/conftest.py, tests/unit/test_config/test_config.py, tests/unit/test_iterate_packages.py, tests/unit/test_koji_build.py
```yaml
packit_instances: ["stg"]
upstream_project_url: https://github.com/fedora-copr/copr.git
packages:
python:
downstream_package_name: python-copr
upstream_package_name: copr
paths: 
- ./python
specfile_path: python-copr.spec
files_to_sync: 
- python-copr.spec
cli:
downstream_package_name: copr-cli
upstream_package_name: copr-cli
paths: 
- ./cli
specfile_path: copr-cli.spec
files_to_sync: 
- copr-cli.spec
frontend:
downstream_package_name: copr-frontend
upstream_package_name: copr-frontend
paths: 
- ./frontend
specfile_path: copr-frontend.spec
files_to_sync: 
- copr-frontend.spec
jobs:
- job: copr_build
packages:
- cli
- python
trigger: pull_request
targets: fedora-37
owner: mmassari
project: knx-stack
- job: vm_image_build
packages:
- cli
trigger: pull_request
copr_chroot: …
```
=> Add monorepo support to all commands

packit/base_git.py
I have no clue why it was added in the first place.
Resolves #1933.
Removed adding the "Signed-off-by" tag to commits created by Packit.
=> Do not sign off commits

packit/cli/builds/koji_build.py, packit/cli/utils.py
`packit source-git` related commands can skip dist-git repos, where the git trailer is not found, when looking for the right dist-git dir where to work.
=> Fix source git trailer not exists

packit/base_git.py, tests/unit/test_base_git.py
Fixes #1932.
---
What happened with [noggin-messages](https://github.com/fedora-infra/noggin-messages):
- the spec file was downloaded in `post-upstream-clone` from the `main` branch of Fedora dist-git
- in `rawhide`, the VR was `1.0.2-5`
- in `f37`, the VR was `1.0.2-4`
- `propose_downstream` bumped the version to `1.0.3` (based on `get-current-version`) and:
- in `rawhide` reset the release, because release in upstream specfile was the same as release in dist-git specfile (because it was the same file)
- in `f37` didn't reset the release, because release in upstream specfile (taken from `rawhide`/`main`) was higher than release in dist-git specfile
- the resulting VR in `f37` was `1.0.3-5`, while in `rawhide` it was `1.0.3-1` => violation of Fedora versioning policies
---
RELEASE NOTES …
=> Reset release when version in upstream spec is not up-to-date

packit/upstream.py
In case `upstream_ref` contains a branch name (and thus it is supposed to start with `branches/`), then properly use `removeprefix()` to drop the `branches/` prefix.
`lstrip()` literally removes all the characters specified in the parameter string from the beginning of the string until any other character is found, so `upstream_ref=sample-*` will be turned into `upstream_ref=ample-*` (note the missing "s", as it is in `branches/`).
TODO:
Fixes
Related to
Packit now properly respects "upstream_ref" for tags that start with "a", "b", "c", "e", "n", "r", "s".
=> Fix removing "branches/" prefix from "upstream_ref"

packit/constants.py, packit/utils/source_script.py
When calling packit if working on a monorepo sub-package related job then use job_config.package
Related to packit-service monorepo fixes
Merge before packit/packit-service#2018
=> Work on a single package at time

packit/config/package_config.py
There are places in packit-service/hardly worker
- https://github.com/packit/packit-service/blob/63831f0a3a320498fd7037af1c83827a36c68c3f/packit_service/worker/jobs.py#L174
- https://github.com/packit/packit-service/blob/63831f0a3a320498fd7037af1c83827a36c68c3f/packit_service/worker/jobs.py#L185
- https://github.com/packit/hardly/blob/d3952bcb7d06cd63bd72ac66e95528085c30eed8/hardly/jobs.py#L51
where we call the [JobHandler.get_signature()](https://github.com/packit/packit-service/blob/63831f0a3a320498fd7037af1c83827a36c68c3f/packit_service/worker/handlers/abstract.py#L354) with the `job` argument being `None`. The `get_signature()` then passes it to the `PackageConfig.get_package_config_for()`, which fails when it tries to access the job.
With this change, it returns itself (if there's …
=> Make get_package_config_for() work with no job_config

files/local-tests-requirements.yaml, packit/base_git.py, plans/full.fmf, tests/unit/test_base_git.py
Fixes #1944.
Please see comments in the code and the added test cases to understand the logic, hopefully it makes sense.
Detection of `%autorelease` usage in dist-git spec file during `propose-downstream` and `pull-from-upstream` has been improved and Packit will always preserve it.
=> Always preserve `%autorelease` if it is used in dist-git

packit/api.py, packit/config/package_config.py, packit/config/package_config_validator.py, tests/functional/test_validate_config.py, tests/integration/test_validate_config.py, tests/integration/test_validate_synced_files.py
Previously, there was no simple flag/way how to know whether the validation failed or passed.
In both cases, we just returned a string
- in case of failed validation: with errors
- in case of successful validation: with a success string 
As a consequence, the return value of 'packit config-validation' was always 0.
With this change, the return value of 'packit config-validation' is 2 in case of failed validation.
TODO:
=> PackageConfigValidator now raises exception if validate() fails

packit/security.py, tests/unit/test_security.py
From what I remember pgp.mit.edu has always been slow and flaky.
I've added [pgp.surf.nl](https://en.wikipedia.org/wiki/Key_server_(cryptographic)#Keyserver_examples) instead.
The test for the non-existing key id has to ask all the key servers and if some of them is not responding it times out.
IMHO, we don't need to test this.
Related #1972
=> PGP: don't use pgp.mit.edu & don't test the non-existing key

packit/exceptions.py, packit/vm_image_build.py, tests/integration/test_using_examples.py, tests/unit/test_image_builder.py, tests_recording/test_data/test_image_builder/TestLocalProject.test_bad_request.yaml, tests_recording/test_image_builder.py
Fixes #1980
Before
```
$ packit build in-image-builder ttomecek-anaconda-installer-s3-1
2023-05-25 10:11:30.002 utils.py          ERROR  400 Client Error: Bad Request for url: https://console.redhat.com/api/image-builder/v1/compose
Unexpected exception occurred,
please fill an issue here:
https://github.com/packit/packit/issues
```
After:
```
$ packit build in-image-builder ttomecek-anaconda-installer-s3-1
2023-05-25 14:19:57.350 vm_image_build.py ERROR  Image Builder Errors: {"errors":[{"detail":"request body has an error: doesn't match schema 
#/components/schemas/ComposeRequest: Error at \"/distribution\": value \"fedora-rawhide\" is not one of the allowed values\nSchema:\n  {\n    \"enum\": [\n      
\"rhel-8\",\n      \"rhel-84\",\n      \"rhel-85\",\n      \"rhel-86\",\n …
```
=> fix(image-builder): print request errors

packit/config/job_config.py, packit/schema.py, tests/unit/test_config/test_package_config.py, tests/unit/test_prepare_sources.py
This PR adds new option `manual_trigger` into Packit schema to allow users to trigger Packit jobs manually.
Service integration done in https://github.com/packit/packit-service/pull/2069
Fixes https://github.com/packit/packit-service/issues/1806
Packit now supports automatic ordering of ☕ after all checks pass.
=> Add new option manual_trigger to packit schema

packit/sync.py, tests/unit/test_api.py, tests/unit/test_sync.py
It should be returning a complete copy
TODO:
This one needs a proper test probably around `PackitAPI.update_dist_git`, but not sure how to make the relevant test there.
Fixes #1975 
Fix files_to_sync filters not being applied properly
=> fix: SyncFilesItem.drop_src

packit/api.py
When creating a PR against the dist-git, include dist-git branch, so it is easier to filter through in the mail client.
TODO:
Fixes #1989
Packit now includes dist-git branch in the title of the PRs for `propose-downstream` and `pull-from-upstream`.
=> fix(dg): mention branch in the PR title

.packit.yaml
The Packit itself does not use Monorepo but we might want to use the new Packages syntax to test it.
=> Use packages syntax for packit itself for dogfooding

packit/api.py, tests/integration/test_update.py, tests/unit/test_api.py
TODO:
Packit now correctly reloads upstream specfile after running `pre-sync` action.
=> Reload specfile after pre-sync action

packit.spec
python-deepdiff is currently broken on rawhide, and since `%check` is not yet used, it is safe not to require test dependencies.
See: https://bugzilla.redhat.com/show_bug.cgi?id=2220058
=> Do not buildrequire test dependencies on rawhide

packit/api.py, packit/constants.py, tests/unit/conftest.py, tests/unit/test_api.py
=> Enable adding instructions on local checkout for sync release PRs

packit.spec
This reverts commit 22b8bfa7af810e8c75cfdab8edcfb208b1442d53.
python-deepdiff has been built in rawhide:
https://koji.fedoraproject.org/koji/buildinfo?buildID=2250764
=> Revert "Do not buildrequire test dependencies on rawhide"

packit/config/common_package_config.py, packit/schema.py, packit/upstream.py, packit/utils/changelog_helper.py, tests/integration/test_upstream.py, tests/unit/test_upstream.py
Introduce 2 configuration options, upstream_tag_include and upstream_tag_exclude to allow filtering the tags. This will be used in the service to allow filtering the propose_downstream runs.
Fixes packit/packit-service#2118
TODO:
2 new configuration options for filtering when getting latest upstream release tag were introduced: `upstream_tag_include` and `upstream_tag_exclude`. They should contain a Python regex that can be used as an argument in `re.match`.
=> Allow filtering tags via regex configuration options

packit/distgit.py, tests/unit/conftest.py, tests/unit/test_dg.py
This is an MVP solution for the issue with monorepo Packit config on the downstream.
GPG keys were probably forgotten during the monorepo refactoring, since there is actually not much reason to have monorepos configured on downstream.
SAFETY: Taking first package instead of specific package should be safe, since we have put a requirement on »one« ‹upstream_project_url› per Packit config, i.e. even if we're dealing with a monorepo, there is only »one« upstream. If there is one upstream, there is only one set of GPG keys that can be allowed.
TODO:
#2039
=> fix(dg): get allowed GPG keys from first package

packit/source_git.py, tests/unit/test_iterate_packages.py
There were 2 kinds of failing tests in f39/rawhide:
1. commit -  a real issue with new behaviour in rpmbuild
2. commit - just a flexmocking issue, probably caused by changed behaviour in newer version of Python
See commit messages for more details.
As for the 1. one, if you have suggestions for a better fix, I will be happy.
We have fixed a bug in `packit source-git init` caused by the changed behaviour in the newer version of rpmbuild.
=> Fix failures on f39/rawhide

files/tasks/rpm-test-deps.yaml, plans/full.fmf
See: https://github.com/seperman/deepdiff/issues/416
=> Temporarily lock deepdiff version to fix CI failures

packit/base_git.py, packit/cli/packit_base.py, packit/cli/propose_downstream.py, packit/distgit.py, tests/unit/test_cli.py
We need this option to be able to test
the pull-from-upstream workflow from the
command line.
Fixes packit#2052
Packit CLI now supports testing the `pull-from-upstream` workflow. 
Use the following command line: 
```
packit pull-from-upstream
```
=> use-downstream-specfile option

packit/config/common_package_config.py, packit/config/notifications.py, packit/schema.py, tests/unit/config/test_package_config.py
Related to packit/packit-service#1911
TODO:
I was also thinking about naming it only `failure_comment`, let me know WDYT.
N/A
=> Add failure_comment_message to notifications config

packit/config/notifications.py, packit/schema.py, tests/unit/config/test_package_config.py
Instead of having one value failure_comment_message, create a nested one failure_comment.message so that failure_comment can be extended in the future if needed. Related to packit/packit-service#1911
N/A
=> Change configuration schema for failure comment

files/tasks/rpm-test-deps.yaml, plans/full.fmf
This reverts commit d95db9fecdaf2c4b89b29cfc523b55b2be498042.
The deepdiff bug has been fixed: https://github.com/seperman/deepdiff/commit/410019e
=> Revert "Temporarily lock deepdiff version to fix CI failures"

packit/api.py, packit/base_git.py, tests/unit/test_dg.py
After introducing the commit action, we allow customizing of the beginning of the PR description (which includes the commit description). This conflicts with the pre-existing check for existing (pun not intended) PRs on dist-git.
Relaxing this condition to match the title, source & target branch with the user should be enough to not duplicate PRs.
TODO:
Fixes
Related to
Packit now supports automatic ordering of ☕ after all checks pass.
=> fix(dg): relax the requirements for existing PRs

packit/api.py, packit/config/common_package_config.py, packit/distgit.py, packit/pkgtool.py, packit/schema.py, tests/integration/conftest.py, tests/integration/test_update.py, tests/integration/test_using_cockpit.py
TODO:
Fixes #2082 
If you have concerns about Packit uploading new archives to lookaside cache before creating a pull request, you can newly set `upload_sources` to False to disable this.
=> Optional lookaside cache

packit/base_git.py, tests/unit/test_base_git.py
Fixes #2033
When updating the `Version` tag during `propose_downstream` or `pull_from_upstream`, Packit now tries to update referenced macros (if any) rather than overwriting the references.
=> Try to update referenced macros rather than replacing value of Version tag

files/tasks/packit-service-requirements.yaml, files/tasks/rpm-test-deps.yaml, plans/full.fmf, plans/session-recording.fmf, tests/full.fmf, tests_recording/main.fmf
[RHBZ#2120251](https://bugzilla.redhat.com/show_bug.cgi?id=2120251)
The reverse-dep tests probably need to merge packit/packit-service#2198 first.
=> Flexmock is now in EPEL 9

packit/api.py, packit/cli/propose_downstream.py, packit/constants.py, packit/utils/changelog_helper.py, tests/integration/test_changelog_helper.py, tests/unit/test_api.py, tests/unit/test_cli.py
Add an argument to sync_release that takes list of bugs. These will be then added to the changelog in the end as "- Resolves {bug}". In case of using autochangelog, these bugs will be referenced in the end of the commit message. Besides these default behaviours, Packit will provide the PACKIT_RESOLVED_BUGS env variable to commit-message and changelog-entry actions.
Related to #1920
TODO:
You can now specify bugs resolved by an update by `-b` or `--resolve-bug` option for `propose-downstream` and `pull-from-upstream` commands. The values will be added by default to the changelog (or commit if autochangelog is used) and provided in `commit-message` and `changelog-entry` actions as `PACKIT_RESOLVED_BUGS` env variable.
=> Be able to specify bugs resolved by an update

packit/api.py, tests/unit/test_api.py
Remove the condition of adding them only when %autochangelog is used, after discussion with @lachmanfrantisek we agreed this could be beneficial in general.
N/A
=> Always add bugs to commit message when syncing release

packit/upstream.py, packit/utils/changelog_helper.py, tests/integration/test_changelog_helper.py
Fixes packit#2076
Packit now exports `PACKIT_UPSTREAM_PACKAGE_NAME`, `PACKIT_DOWNSTREAM_PACKAGE_NAME` and `PACKIT_CONFIG_PACKAGE_NAME` also in the `changelog_entry` action.
=> Add package names to changelog_entry action

packit/distgit.py, tests/unit/test_dg.py
Use the same regex as Bodhi does for the automatic updates.
Related to #1920
Packit now also detects resolved bugs in the default update notes (created from changelog diff) and assigns these when submitting the Bodhi updates.
=> Detect bugs in changelog when submitting Bodhi update

packit/api.py, tests/full.fmf, tests/unit/test_api.py
Fixes packit/packit-service#2213
We have fixed an issue that prevented automated allowlisting in the Packit Service.
=> Fix allowlisting automation

packit/constants.py, tests/unit/test_dg.py
When introducing the dataclass for distgit instances, I've switched to constructing the hostname candidates from the said instances of dataclass instead of a fixed set of URLs.
This change introduces 2 problems though:
1. ‹itertools.chain› constructed a pair of hostnames ‹(hostname, alternative hostname)›
2. Even after switching to ‹itertools.chain.from_iterable› we need to filter out the ‹None› values, since ‹gitlab.com› doesn't have any alternative hostname
TODO:
Fixes #2116
We have fixed an issue that you could encounter when running the Packit from the CLI that caused misinterpretation of the repository to be an upstream repo instead of a downstream.
=> fix(dg): fix the hostname candidates to be a set

.pre-commit-config.yaml, packit/constants.py, tests/data/dist_git/.packit.json, tests/data/dist_git/.packit.yaml, tests/data/dist_git_with_autochangelog/.packit.json, tests/data/dist_git_with_autochangelog/.packit.yaml, tests/data/empty_changelog/.packit.json, tests/data/empty_changelog/.packit.yaml, tests/data/spec_not_in_root/upstream/.packit.json, tests/data/spec_not_in_root/upstream/.packit.yaml, tests/data/upstream_git/.packit.json, tests/data/upstream_git/.packit.yaml, tests/data/upstream_git_macro_in_source/.packit.json, tests/data/upstream_git_macro_in_source/.packit.yaml, tests/data/upstream_git_weird_sources/.packit.json, tests/data/upstream_git_weird_sources/.packit.yaml, tests/data/upstream_git_with_multiple_sources/.packit.json, tests/data/upstream_git_with_multiple_sources/.packit.yaml, tests/functional/test_srpm.py
- [N/A] Update or write new documentation in `packit/packit.dev`. (The docs doesn't mention `[.]packit.json` anywhere)
Fixes #1573 
Packit no longer accepts `packit.json` or `.packit.json` as a configuration file name.
=> Stop supporting [.]packit.json for the configuration

packit/api.py, tests/unit/conftest.py
By this, we will make sure the untracked files (that were e.g. for one branch gitignored) will not be committed when syncing other branch (without having that file gitignored).
Fixes https://github.com/packit/packit-service/issues/2181
TODO:
Packit now properly cleans up the branch after syncing the release which should prevent unwanted files (e.g.tarballs) being committed in dist-git.
=> Run git clean after syncing release in a branch

pyproject.toml
Building ogr no longer requires setuptools-scm-git-archive.
=> Remove unneeded dependency

packit/base_git.py, tests/unit/test_base_git.py
Fixes https://github.com/packit/packit/issues/2129.
Merge after https://github.com/packit/specfile/pull/295.
Packit no longer downloads sources excluded using spec file conditions.
=> Do not download sources excluded using spec file conditions

plans/full.fmf, plans/session-recording.fmf
But not when run on a dist-git PR, in that case we want to test with stable versions.
=> Make sure the latest builds of ogr and specfile are available for upstream test jobs

packit/utils/changelog_helper.py, tests/unit/test_upstream.py
Not sure if this is the most optimal place to put it
TODO:
Fixes #1978 
Enforce dist tag `%{?dist}` when updating release
=> Make sure release has a disttag

packit/upstream.py, packit/utils/__init__.py, tests/unit/test_utils.py
Following documentation at
https://github.com/rpm-software-management/rpm/blob/master/docs/manual/spec.md#version
Fixes #2101
Now Packit allows ~^+ (special characters) in a tag (used for building the version string). 
=> Fix sanitize version method

packit/upstream.py, tests/data/no_version_tag_in_spec/.packit.yaml, tests/data/no_version_tag_in_spec/beer.spec, tests/data/no_version_tag_in_spec/source, tests/integration/test_update.py, tests/integration/test_upstream.py, tests/spellbook.py
This way, if the specfile doesn't contain the version tag directly (but e.g. uses imports), get_specfile_version returned None. Fixes #2137
Packit is now able to get the version from specfile even if the `Version` tag is not present in the specfile directly, but e.g. imported from another file.
=> Modify get_specfile_version to not use expanded_version

packit/api.py, packit/config/common_package_config.py, packit/exceptions.py, packit/schema.py, tests/integration/test_using_cockpit.py, tests/unit/conftest.py, tests/unit/test_api.py
On stable branches we should avoid doing major updates releases.
Fixes #2130
Merge before packit/packit-service#2250
Now Packit can check,  using the `update_version_mask`,  that  the proposed version release and the actual package release for the target dist-git branch are compatible.
=> Check proposed and current version before release

.github/workflows/pypi-publish.yml
And let the workflow be manually re-run
Related to #2164
=> Let "github action checkout" fetch all tags

.github/workflows/pypi-publish.yml
With version [0.86.0](https://github.com/packit/packit/actions/runs/6901837024) the **pypi_bublish** action is failing.
The failing command is `python -m build` which is retrieving a *wrong version*.
If you clone the repo and you run `python -m build` you get the correct version. 
But if you run `python -m build` in this container, which is doing more or less what the github **checkout** action does, you get the wrong version.
```FROM ubuntu:latest
RUN apt-get update && apt-get install -y --no-install-recommends \
git \
python3 \
python3.10-venv \
python3-pip
RUN git config --global --add safe.directory /packit
RUN git config --global init.defaultBranch main
RUN git init /packit
WORKDIR /packit
RUN git remote add origin https://github.com/packit/packit
RUN git config --local gc.auto 0
RUN …
```
=> Fix pypi_publish action

packit/base_git.py, packit/config/common_package_config.py, packit/schema.py, tests/unit/test_base_git.py
There are two ways how to support pre-releases in a spec file.
The simpler way relies on the `%version_no_tilde` macro from `rust-srpm-macros` (not present on EL < 9) that converts a pre-release version with `~` back to upstream version. An optional argument defines upstream delimiter that defaults to `-`.
Here is an example of a spec file using this macro:
```specfile
Version:        3.28.0~rc3
...
Source0:        https://example.com/files/v%{version_no_tilde}/%{name}-%{version_no_tilde}.tar.gz
...
%prep
%autosetup -p1 -n %{name}-%{version_no_tilde}
```
If upstream version doesn't have a delimiter, for example `3.28.0b5`, you can use `%{version_no_tilde %{quote:%nil}}`.
The second, more complex way requires you to define a macro, typically called `prerelease` or `prerel`, and package …
=> Support pre-release versions in sync_release

packit/utils/changelog_helper.py, tests/integration/test_changelog_helper.py
When there is no specfile in dist-git during release syncing (e.g. first release), Packit copies the upstream one. This commit also additionally sets its content (version, changelog entry) after the upstream specfile is copied.
Packit now correctly sets the specfile content (e.g. changelog entry) even if it syncs the specfile from upstream the first time.
=> Set specfile content when there is no dist-git specfile

packit/api.py, packit/base_git.py
Previously we hit the issue of untracked files preventing switch to another branch. I was not able (yet) to find how/why are these files added, as we do git reset and clean always in the end of syncing. This should workaround the issue for now.
Fixes packit/packit-service#2234
N/A
=> Force switch the dist-git branch when syncing release

packit/api.py, packit/constants.py, packit/utils/repo.py, tests/integration/conftest.py, tests/integration/test_update.py, tests/unit/conftest.py, tests/unit/test_api.py, tests/unit/utils/test_repo.py, tests_recording/test_api.py
Link the upstream tag and commit (do
not use GitProject from ogr API here as in pull from upstream this might not be initialised).
If GitProject is initialised, also include link to the release.
Fixes #2152
The issue proposed linking the new version in Anitya backend (e.g. PyPI), but I was not able to find an easy way how to obtain this (it was not possible to get this e.g. using anityia API). But I am open to suggestions.
Packit now links the information related to upstream in PRs opened when syncing a release.
=> Implement linking of info in sync release PRs

packit/config/commands.py, packit/config/common_package_config.py, packit/schema.py, tests/unit/config/test_package_config.py
Introduce the default_labels and default_identifier nested config options in test_command, that will be used if /packit test service comment command is called without any arguments.
Needed for #2056
TODO:
N/A
=> Introduce test command config options

packit/utils/changelog_helper.py, tests/integration/test_changelog_helper.py
In case the changelog is None, e.g. release has no description, fallback to the default message.
Fixes packit/packit-service#2281
We have fixed a bug preventing the release from being synced downstream if the changelog to be set is empty.
=> Fallback to default changelog message if changelog is None

packit/api.py
This will be used by packit-service to be able to append additional content for the PR description.
N/A
=> Add pr_description_footer argument for sync_release

packit/upstream.py
Using the current release tag as a reference when listing available tags ensures that if a project uses release branches, only the correct tags will be listed. However, there are projects where release tags are standalone, not connected to any existing branch, and using a reference in such case leads to incorrect results at best. I think that avoiding using a reference is a better alternative, because projects with release branches can still use tag filtering to make things work correctly.
Fixes https://github.com/packit/packit/issues/2207.
=> Consider all tags when looking for the previous release

packit/api.py, packit/base_git.py, packit/cli/propose_downstream.py, packit/distgit.py, packit/upstream.py, tests/integration/test_using_cockpit.py, tests/unit/test_api.py, tests/unit/test_cli.py
This was mainly added for the service, so we will pass this argument from there and in CLI, by default not sync the ACLS. Fixes #2206
TODO: 
`pull-from-upstream` and `propose-downstream` commands now have the `--sync-acls` option that enables syncing the ACLs between dits-git repo and fork. The default behaviour was, however, changed to not sync the ACLs.
=> Don't sync ACLs by default during release syncing

packit/cli/prepare_sources.py, packit/utils/source_script.py
Related to https://github.com/packit/packit/issues/2184.
Should I add the option also to other CLI commands, namely `srpm` and probably all subcommands of `build`?
=> Add --merged-ref to prepare-sources

packit/base_git.py, packit/config/common_package_config.py, packit/schema.py, tests/unit/test_base_git.py
Fixes #2203.
There is a new global configuration option `parse_time_macros` that allows to configure macros to be explicitly defined or undefined at spec file parse time.
=> Add parse_time_macros option

packit/api.py, packit/cli/validate_config.py, packit/config/package_config_validator.py, packit/constants.py
Add 2 checks regarding monitoring of the package by Upstream Release Monitoring if pull-from-upstream job is present in the config.
Fixes #2224
`packit validate-config` now checks whether the Upstream Release Monitoring for the package is correctly configured if `pull_from_upstream` job is present in the configuration.
=> validate-config: Check monitoring for pull-from-upstream

packit/cli/dist_git.py, packit/cli/dist_git_init.py, packit/cli/init.py, packit/cli/packit_base.py, packit/cli/types.py, packit/cli/utils.py, tests/unit/test_dist_git_init.py
Create new command sub-group dist-git for dist-git related functionality and introduce the init command that initialises a dist-git repository config with jobs for release automation.
See packit dist-git init --help
Example PR created by `packit -d dist-git init --upstream-git-url https://github.com/easypost/syslog-rfc5424-formatter --actions-file ../actions.yaml --create-pr syslog` : https://src.fedoraproject.org/rpms/python-syslog-rfc5424-formatter/pull-request/1#request_diff
Fixes packit/packit-service#2301
TODO:
We have introduced new CLI command `packit dist-git init` that initializes Packit configuration for release automation in dist-git repository.
=> Introduce dist-git init command

packit/config/job_config.py, tests/unit/config/test_config.py
In some cases it could be valuable for users to create a job that is ignored by Packit (read: it's not executed). Typical use case is when users want to define a template job that could be used in real test jobs using the yaml format.
E.g.:
```
jobs:
- &my-abstract-job
job: tests
trigger: ignore
... other generic repeating values ...
- my-real-job
<<: *my-abstract-job
trigger: pull_request
...test specific values...
```
This is especially useful for projects with many similar jobs defined in the .packit.yaml configuration file. Using templates users can make their .packit.yaml config file much shorter, which reduces also maintainance burden.
The original problem was, that each job requires a defined trigger, so it was not possible to create a template that is not executed at all. For this …
=> Introduce new job trigger: "ignore"

.github/workflows/check-release-notes.yml, .pre-commit-config.yaml
It needs the ‹jobs› to be present, yet there's no f-ing linting… this is the future???
=> ci: fix the GH Action definition

packit/api.py, packit/base_git.py, packit/upstream.py, tests/unit/test_api.py, tests_recording/test_api.py
Compare the version to propose with version in the specfile of the particular branch.
Fixes #2208
Packit now checks the version to propose against the version in specfile and doesn't create downgrade PRs.
=> Don't sync the release for downgrades

packit/api.py, packit/local_project.py
=> Add log suggestions to use upstream_tag_template in sync_release

packit/config/package_config_validator.py
Fixes #2252
`packit validate-config` now checks whether `upstream_project_url` is set if `pull_from_upstream` job is configured.
=> validate-config: Check upstream_project_url for pull_from_upstream

packit/utils/changelog_helper.py, tests/integration/test_changelog_helper.py, tests/integration/test_update.py
TODO:
As discussed and agreed on in https://pagure.io/packaging-committee/issue/1339,
we changed the default behaviour for changelog entry generation to comply with the packaging guidelines. The default changelog entry will be `- Update to version <version>`.
Users can still configure the behaviour using custom commands in
`changelog-entry` action or using `copy_upstream_release_description` config option.
=> Change the default changelog entry for release sync

packit/api.py, packit/constants.py, tests/unit/test_api.py
Fixes: #2262
Packit previously put the "[packit]" string as a prefix in the subject of pull-from-upstream commits. Now the prefix is no longer there - this is made unnecessary noise in autochangelog. This affects the default. Custom action can still override this behavior.
=> remove [packit] prefix from pull-from-upstream dist-git commits

packit/api.py
Then the version that is being proposed during syncing the release.
This log message is shown in the dashboard (see e.g. https://dashboard.packit.dev/results/propose-downstream/7733)
N/A
=> Fix log message when downstream specfile version is higher

packit/config/package_config.py, tests/unit/config/test_package_config.py
Once the package config is loaded via PackageConfigSchema().load(dict), all the default values in all job configs are set. This is therefore needed so that in packit service we are able to store the package config in DB with reasonable size.
Needed for packit/packit-service#1940
=> Save original package config dict after setting defaults

packit/api.py
Fixes #2259
We have fixed Packit auto-referencing Upstream Release Monitoring bug for release syncing to CentOS Stream.
=> Don't reference Upstream Release monitoring bug for CentOS

packit/cli/dist_git_init.py
Fixes #2285
`packit dist-git init` now allows specifying `--version-update-mask` option and also any arbitrary top-level configuration options.
=> Dist-git init improvements

packit/base_git.py
This is specific only for Pagure, on GitLab, the members should be obtained directly and added as well.
Fixes #2296
We have fixed the syncing of ACLs during CentOS Stream release syncing.
=> Skip syncing of group ACLS if not working with Pagure

packit/api.py, packit/distgit.py, tests/integration/test_update.py, tests/unit/test_api.py
TODO:
Related to packit/packit-service#2314
Packit will now upload to lookaside cache sources that are not specified by URLs and are present in the dist-git repo during release sync. Additionally, all the actions ran during syncing release will provide the PACKIT_PROJECT_VERSION env var.
=> Upload local sources during sync release

packit.spec, packit/api.py, packit/cli/packit_base.py, packit/cli/scan_in_osh.py
... to perform a scan through OpenScanHub.
TODO:
Kerberos login would require `dns_canonicalize_hostname = false` in `/etc/krb5.conf`. Related link: https://fedoraproject.org/wiki/Infrastructure/Kerberos#Extra_info_for_Infrastructure_people
Instructions to install `osh-cli` are given in https://fedoraproject.org/wiki/OpenScanHub. 
Command to perform a full build: `packit scan-in-osh`
Command to perform a differential build: `packit scan-in-osh --base-srpm=<path_to_old_srpm`
Fixes
Related to
openscanhub/fedora-infra#54
There is a [review request](https://bugzilla.redhat.com/show_bug.cgi?id=2275304) to add `osh-cli` to the official Fedora repositories.
Add a `scan-in-osh` subcommand in the CLI to perform a scan through OpenScanHub. By default, it …
=> Add a `scan-in-osh` subcommand

packit/cli/dist_git_init.py
When running `dist-git init` command from CLI, you can pass a command to specify a git URL of the project.
=> Add a way to get upstream-git-url from a command via dist-git init

packit/distgit.py, packit/upstream.py
For GitLab, the maintainers should be able to push to the PR by default without the need to sync the ACLs.
Fixes packit/packit-service#2429
We have fixed the syncing of ACLs for `propose-downtream` for CentOS Stream.
=> Skip ACLs syncing for other forges than Pagure

packit/data/_packitpatch, packit/source_git.py, tests/data/cronie/SPECS/cronie.spec, tests/integration/test_source_git.py
RPM 4.20 (alpha version currently in rawhide) obsoleted `%patchN` macros and changed build directory structure. Make things work again.
=> Make adjustments for RPM 4.20

packit/api.py, packit/base_git.py, plans/full.fmf, tests/full.fmf, tests/unit/test_api.py
We have promised in docs to pass the same variables as in the release-synchronization environment, but we don't.
This has been discovered on pre-DevConf.cz 2024 workshop by @vashirov
TODO:
Can't come up with a reasonable name…
We have fixed a bug that caused inconsistency between the promised environment variables (from the docs) and the environment that has been actually provided. Now you should have access to `PACKIT_UPSTREAM_REPO` and `PACKIT_DOWNSTREAM_REPO`, if they have been cloned already, in the `post-upstream-clone` action.
=> fix(action): pass promised variables to ‹post-upstream-clone›

packit/config/notifications.py, packit/schema.py, tests/unit/config/test_package_config.py
Introduce new config option notifications.failure_issue.create that defaults to True.
Needed for packit/packit-service#2416
N/A
=> Introduce config option for disabling issue creation

packit/local_project.py
It can be used later on, so it should be passed and initialised.
Fixes #2340
=> Pass cache from LocalProjectBuilder to LocalProject

packit/schema.py, tests/unit/config/test_package_config.py
With this change, it is possible to have a config like this:
```yaml
downstream_package_name: B
jobs:
- job: koji_build
trigger: commit | koji_build
sidetag_group: AB
dependencies:
- A
dist_git_branches:
- fedora-all
```
that is equivalent to this:
```yaml
downstream_package_name: B
jobs:
- job: koji_build
trigger: commit
sidetag_group: AB
dependencies:
- A
dist_git_branches:
- fedora-all
- job: koji_build
trigger: koji_build
sidetag_group: AB
dependencies:
- A
dist_git_branches:
- fedora-all
```
Related to https://github.com/packit/packit-service/issues/2378.
Merge after https://github.com/packit/packit/pull/2350.
=> Add config syntax sugar for jobs with multiple triggers

packit/copr_helper.py
TODO:
Probably we should also suggest a change in copr client library to be able to access `error status codes` without accessing a private attribute, WDYT?
Fixes packit/packit-service#2459
=> Report Copr Internal Server Error to user

.packit.yaml, files/local-tests-requirements.yaml, files/tasks/centos-packager.yaml, packit/api.py, packit/config/common_package_config.py, packit/constants.py, packit/dist_git_instance.py, packit/distgit.py, packit/pkgtool.py, packit/schema.py, tests/unit/config/test_common_package.py, tests/unit/utils/test_dist_git_instance.py
tl;dr WIP support for CBS. What we really need there is `pull_from_upstream` though. 
- I've managed to successfully run `packit build in-koji` from cloned dist-git SIG repo, Koji builds from CLI seem to be functional
- I've added new config option `sig`, it is being injected into the packaging tool and dist-git instance, it is not very ideal design and also it may hit its limits, though it is not very easy to work around as the packaging tool is being passed around just as a string (SIG ⇒ additional parameter)
Related to #2305 
Merge with packit/packit.dev#906
We have implemented a CLI support for Koji builds against CBS Koji instance.
=> Add support for CBS Koji

packit/api.py, packit/cli/propose_downstream.py, packit/cli/utils.py, packit/command_handler.py, packit/constants.py, packit/status.py, packit/upstream.py, packit/utils/changelog_helper.py, tests/integration/conftest.py, tests/integration/test_get_api.py, tests/integration/test_source_git_synch_push.py, tests/integration/test_update.py, tests/integration/test_upstream.py, tests/unit/conftest.py, tests/unit/test_base_git.py, tests/unit/test_upstream.py, tests_recording/testbase.py
TODO: 
Fixes #2147 
`packit pull-from-upstream` now allows omitting `upstream_project_url` in the configuration in which case the interaction with the upstream repository is skipped during release syncing.
=> Allow pull-from-upstream for non-git upstreams

.packit.yaml
Bodhi updates for rawhide are not autocreated when the Koji build is tagged into a sidetag.
=> Create Bodhi updates also for rawhide

packit/utils/koji_helper.py, tests/unit/utils/test_koji_helper.py
This should fix changelog diff generation in Bodhi updates created from sidetags.
Related to https://github.com/packit/packit-service/issues/2379.
=> Make `KojiHelper.get_stable_tags()` work for sidetags

packit/distgit.py, packit/utils/koji_helper.py, tests/integration/test_create_update.py, tests/unit/utils/test_koji_helper.py
Bodhi updates from sidetags will be created also for rawhide, so it is no longer possible to construct candidate tag name based solely on branch name.
Related to https://github.com/packit/packit-service/issues/2379.
=> Implement getting candidate tag also for rawhide

packit/copr_helper.py
It's a long shot, but if the response actually contains some content, it could help with debugging the issue. At least it's better than the generic `Response is not in JSON format, there is probably a bug in the API code.` message from `CoprClient`.
=> Log response content in case of HTTP 500 error from Copr

packit/cli/dist_git_init.py
Related to packit/packit-service#2203
`dist-git init` command now allows `upstream-git-url` not to be specified.
=> Allow upstream-git-url in dist-git init to not be specified

.pre-commit-config.yaml
types-pkg-resources has been yanked.
They suggest to use types-setuptools instead.
=> Use types-setuptools in precommit checks

packit/config/common_package_config.py, tests/integration/conftest.py
Fixes https://github.com/packit/packit-service/issues/2172.
Merge before https://github.com/packit/packit-service/pull/2507.
=> Make it possible to directly get upstream_project_url with monorepo configs

packit/config/common_package_config.py, tests/integration/conftest.py
The property doesn't work because of the `__getattr__()` magic, special-case `upstream_project_url` in both `__getattr__()` and `__setattr__()` so it is writable as well.
Related to https://github.com/packit/packit/pull/2394.
=> Fix handling `upstream_project_url` with monorepo configs

packit/api.py, packit/cli/scan_in_osh.py, packit/config/common_package_config.py, packit/schema.py
... subcommand and `csmock_args` configuration option.
Related: https://github.com/packit/packit/issues/2391
TODO:
Test command:
`packit scan-in-osh --csmock-args="--cppcheck-add-flag=--enable=style"`
Fixes
Related to
https://github.com/packit/packit/issues/2391
Packit now supports passing custom arguments to various static analyzers through `--csmock-args` CLI option and `csmock_args` configuration.
EDIT: Added reference to `csmock_args` configuration option.
=> Add `--csmock-args` option to `scan-in-osh`

packit/api.py
Correctly escape the csmock args, so they cannot be abused.
Follow-up of #2402
=> fix(osh): escape the csmock args

packit/api.py, packit/base_git.py, packit/cli/propose_downstream.py, packit/config/aliases.py, packit/config/common_package_config.py, packit/config/package_config.py, packit/constants.py, packit/schema.py, tests/integration/conftest.py, tests/integration/test_update.py, tests/integration/test_validate_config.py, tests/unit/config/test_config_aliases.py, tests/unit/config/test_package_config.py, tests/unit/conftest.py
now, `dist_git_branches` can be
- or a list of strings:
```
["rawhide", "fedora-stable"]
```
- or a complex dictionary
```
{
"rawhide": {
"fast_forward_merge_into": ["f40"]
},
"fedora-stable": {}
}
```
Related with packit#1724
Should fix packit#2375
=> Allow dist_git_branches to be a dictionary

packit/config/package_config_validator.py
This is no longer required.
Check for `upstream_project_url` presence in the configuration when `pull_from_upstream` job is configured was removed from `validate-config`, as this is no longer required.
=> Remove upstream_project_url check in validate-config

packit/cli/init.py
TODO:
Fixes
Related to
`packit init` now adds working directories that are used in `packit prepare-sources` into the `.gitignore` file in the same directory where Packit config resides.
=> Gitignore issue

packit/cli/create_update.py, packit/cli/propose_downstream.py, tests/unit/test_cli.py
We used two different options for the same thing.
Unifing for better user experience.
Fixes #2258
Fixes #2281
TODO:
Fixes
Related to
Previously, the `--resolve-bugzillas` option has been used for `create-update` and the option `--resolve-bug` has been used for `propose-downstream`. They have been unifed to just `--resolve-bug` for better user experience.
If you used the option `--resolve-bugzillas` for command `create-update` you must use  the `--resolve-bug` now instead.
Previously, the `pull-from-upstream` option took the `--resolve-bug`  option from CLI.
While the `resolved-bugs` option has been used for retriggering an comment command in service. . They have been unifed to just `--resolve-bug` for better user experience.
If you used the option …
=> Replace the --resolve-bugzillas for --resolve-bug

packit/api.py, packit/vm_image_build.py
Fixes #1966
TODO:
Fixes
Related to
Merge before packit/packit.dev#945
Packit now allows building VM images via CLI without any Copr repository specified.
=> Allow VM image-build without Copr

packit/cli/create_update.py, packit/cli/propose_downstream.py
During the changes in #2428 we have incorrectly assumed the type of the bugs that are passed to the ‹-b› (or ‹--resolve-bug›) switch.
The previous assumption expected that the bugs are represented by simple number (integer) whereas they are represented in a bit more complex form, such as ‹rhbz#1234› (Bugzilla) or even ‹PROJECT-1234› (Jira).
Revert such assumption to accept plain strings as it makes the ‹-b› swich unusable with such precondition.
We have fixed an issue that was introduced during the unification of the interface for passing resolved Bugzillas / Jira tickets to the `sync-release` or `bodhi_update` jobs.
=> fix(cli): correctly type the resolved bugs

packit/distgit.py
There was an instance of failed Bodhi update with `Unable to create update.  argument of type 'NoneType' is not iterable`.
Logging all arguments passed to `BodhiClient.save()` could help identifying potential issue on our side (even though it could be a bug on Bodhi side as well).
=> Log all arguments passed to `BodhiClient.save()`

packit/cli/dist_git_init.py, tests/unit/test_dist_git_init.py
And also default to using it (rawhide to fedora-stable mapping). Fixes #2421
With the current implementation, for `koji_build` and `bodhi_update` job, we will use `--dist-git-branches` with default `rawhide` still, I was also thinking if we shouldn't be using all the branches present in `--dist-git-branches-mapping` rather, WDYT?
Packit now supports and defaults to `fast_forward_merge_into` syntax via `--dist-git-branches-mapping` in `dist-git init`.
=> Support fast_forward_merge_into in dist-git init

packit/constants.py
You can now define `with_opts` and `without_opts` in target-specific configuration of `copr_build` job to build with `--with` and `--without` rpmbuild options.
=> Allow configuring with_opts/without_opts chroot-specific options

packit/config/package_config.py
Users can use this placeholder to put anchors that would otherwise be invalid keys in the config file, e.g.
```yaml
_:
internal-test: &internal-test
job: tests
use_internal_tf: True
jobs:
- <<: *internal-test
targets: [ fedora-latest ]
tmt_plan: "/plans/core"
- <<: *internal-test
targets: [ epel-9 ]
require:
label:
present:
- full
```
Notice how in this example we cannot create a reusable anchor from either the fedora or the epel job because it would automatically inherit either `tmt_plan` or `require.*` values. Allowing a placeholder where one could define some definitions for later usage would make designing the yaml file a bit easier in some cases.
Feel free to propose any naming convention for this placeholder
TODO:
packit/packit.dev/pull/971
Fixes
Related to …
=> Add a yaml placeholder

packit/distgit.py
It seems there is a bug/feature in Bodhi and when editing an existing update and not supplying the `bugs` parameter, Bodhi returns a failure however the only non-updated property of the update is the list of bugs.
Always including the list of bugs, even if empty, should prevent this.
I've also opened https://github.com/fedora-infra/bodhi/issues/5800.
Fixes https://github.com/packit/packit/issues/2467 and similar.
=> Always include the list of bugs in `BodhiClient.save()` kwargs

packit/actions.py, packit/api.py, packit/upstream.py, tests/functional/test_srpm.py, tests/integration/test_update.py
Fixes https://github.com/packit/packit/issues/2416.
If you can think of a better name for the action, I'm all ears.
I was thinking that having upstream git repo as a working dir for this action doesn't make much sense during `sync_release`, but it would be probably non-trivial to change that and users still have `$PACKIT_DOWNSTREAM_REPO` available. At least now it is consistent with other actions. WDYT?
In the integration test case I wanted to test creating an additional source based on the primary source in the action, but `$PACKIT_DOWNSTREAM_REPO` is not set on the account of `dg._local_project` being `None`, so I eventually gave up. Do you think it's worth the effort?
There is a new action/hook, `post-modifications`, that is executed after all modifications to the …
=> Add `post-modifications` action

.github/workflows/obs-build-smoke-test.yml, packit/api.py, packit/cli/build.py, packit/cli/builds/obs_build.py, packit/config/aliases.py, packit/utils/obs_helper.py, pyproject.toml, tests/unit/config/test_config_aliases.py, tests/unit/conftest.py, tests/unit/test_obs_build.py, tests_recording/test_data/test_api/ProposeUpdate.test_changelog_sync.yaml
This is a very much WIP support for building rpms in the open build service. I have so far tested it only on packit via `packit build in-obs --targets fedora-rawhide-x86_64,fedora-rawhide-aarch64,opensuse-tumbleweed-x86_64,opensuse-tumbleweed-aarch64` which created this package: https://build.opensuse.org/package/show/home:dancermak:packit/packit ~~(it is unresolvable because my obs wrapper is not packaged)~~.
TODO:
Packit now supports building packages in the open build service
=> OBS build support

packit/api.py, packit/distgit.py, tests/integration/test_update.py, tests/integration/test_using_cockpit.py
Fixes https://github.com/packit/packit/issues/2460.
Packit doesn't attempt to upload git-tracked remote sources (for example a [GPG keyring](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_verifying_signatures)) to lookaside cache anymore when syncing release.
=> Do not upload git-tracked remote sources to lookaside cache

packit/utils/commands.py
Some environment variables passed to actions can be `None`, deal with that.
This is not an issue in Sandcastle, only when using CLI.
=> Sanitize environment before running actions locally

packit/copr_helper.py
The available chroots are cached for 12 hours, so I think logging the full set of chroots is unnecessary and leads to excessively large log entries (+ the intersection result will still be logged).
This is just a suggestion, let me know what you think.
=> Remove logging of Copr chroots to reduce logs

packit/config/aliases.py
`opensuse_distro_aliases.get_distro_aliases()` currently raises `IndexError`. I've opened a [PR fixing it upstream](https://github.com/rpm-software-management/opensuse-distro-aliases/pull/68), however once the aliases cache on workers expires (most likely during the deployment later today), it will blow up unless we merge this (or get a fixed version of `opensuse-distro-aliases` to Fedora 41 immediately, or install the package from PyPI/Copr).
=> Fall back to cached openSUSE distro aliases on any exception

pyproject.toml
After running ruff:
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
Therefore switch to those new options.
=> chore(ruff): do not use deprecated settings

.packit.yaml
No more supported due to pyforgejo.
And build in packit-stable and packit-releases just stable targets.
=> Remove epel9 from copr buids

.github/workflows/prepare-release.yml
Instead of using the default GITHUB_TOKEN, use the releasebot token to ensure workflows run on pull requests created by these PRs. Docs: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/triggering-a-workflow?utm_source=chatgpt.com#triggering-a-workflow-from-a-workflow
=> Use releasebot token for prepare-release PR creation to trigger workflows

packit/api.py, tests/integration/test_update.py
If there is no spec file in the target dist-git branch trying to reload it tracebacks. But it can be a valid scenario
(freshly created dist-git repo/branch) and the spec file would be later copied from upstream (if possible).
Fixes https://github.com/packit/packit/issues/2562.
Related to https://github.com/packit/specfile/issues/462.
=> Do not traceback on reloading downstream spec if it doesn't yet exist

packit/api.py, packit/cli/scan_in_osh.py
... API and CLI for OpenScanHub scans.
TODO:
Steps to test:
```
git clone git@github.com:util-linux/util-linux.git
cd util-linux
packit scan-in-osh --base-nvr=util-linux-2.40.2-4.fc41
```
The base nvr would be pulled in from Koji.
Example result https://openscanhub.fedoraproject.org/task/45316/
Fixes
Related to
Packit now supports `--base-nvr` option while submitting scans to OpenScanHub. The base nvr is pulled in from koji to perform a differential scan.
=> CLI: Add support for specifying base nvr in Packit

packit/api.py, tests/integration/test_update.py, tests/integration/test_using_cockpit.py
Related to packit/packit-service#2701
When using `fast_forward_merge_into`, `version_update_mask` is now correctly being taken into consideration.
=> Fixes for fast_forward_merge_into 

packit/base_git.py
Related to https://github.com/packit/packit-service/issues/2765.
Merge after https://github.com/packit/packit-service/pull/2769.
=> Ignore submodules when checking for repo dirtiness

packit/api.py, packit/config/__init__.py, packit/config/common_package_config.py, packit/schema.py
TODO:
Fixes #2391
Merge before packit/packit.dev#1024
We have implemented a set of options `osh_options` that allow you to customize OpenScanHub scans via config.
=> pass custom options to osh-cli from yaml config

packit/api.py, packit/cli/validate_config.py, tests/functional/test_validate_config.py
Fixes #2451
Fixes #2451
i added a `-c / --config` option to the `validate-config` command.  
```bash
packit validate-config
packit validate-config -c /home/mohamed/custom-packit.yaml 
pytest -v ./tests/functional/test_validate_config.py   
```
You can now validate a Packit config passed to the Packit CLI via a path, e.g., `packit config validate -c /tmp/my-custom-packit-config.yml`.
=> Add -c option to validate-config 

packit/copr_helper.py
It appears that logging failed cancellation of a Copr build results in spamming our Sentry, therefore turn it just into a warning.
Fixes #2600
=> fix(copr): do not log failed cancel of Copr build as error

packit/upstream.py, tests/unit/test_upstream.py
Fixes #2603
We have added a support for passing `upstream_package_name` to the `upstream_tag_template` option.
=> feat: pass upstream package name to tag template

packit/api.py
Context: https://redhat-internal.slack.com/archives/C07NHHR1W5T/p1747661088924529
Using shlex.quote() on arguments like --csmock-args caused incorrect command construction, e.g. "--gcc-analyze --timeout=180" resulted in the argument being quoted as a single string: '--gcc-analyze --timeout=180', which didn't work with argument parsing in osh-cli.
As suggested by @kdudka, the code should be still safe as the command
is passed to subprocess called with shell=False.
=> Remove unnecessary shlex.quote() when building osh-cli command

.packit.yaml, plans/full.fmf, plans/session-recording.fmf
We are still missing dependencies that we need to build Packit in the EL10, therefore disable testing in EL10 explicitly in the plans as it causes issue with reverse-dependency tests in ogr.
Related to the comment: https://github.com/packit/ogr/pull/935#issuecomment-3138839943
Merge before packit/ogr#935
=> ci(tmt): disable running full and requre in EL10

.gitattributes
As I was working on https://codeberg.org/forgejo/forgejo/pulls/8935, I noticed that it's possible to utilize `.gitattributes` to mark certain files in a repository as _generated_ and affect the git diffs and stats.
As requre responses are generated by requre, it makes sense to mark them as such.
- git docs: https://git-scm.com/docs/gitattributes
- GitHub lingust docs: https://github.com/github-linguist/linguist/blob/main/docs/overrides.md
- Inspired by: https://codeberg.org/forgejo/forgejo/src/commit/f6bc8f7cd7c1e013b54088ed4165c4bbe47c6268/.gitattributes#L6
=> chore(git): mark requre responses as generated

packit/api.py, packit/cli/packit_base.py, packit/cli/test.py, packit/utils/local_test_utils.py, tests/unit/test_local_test_utils.py
TODO:
Fixes
Related to #1911 
Packit now automatically invokes an rpm build in mock when no rpm test is passed before running local tests
=> Implementation to auto generate RPMs for easy local testing

packit/sync.py, tests/unit/test_sync.py
TODO:
Fixes #2539
Closes #2573 (superseeds)
Fix an issue where the upstream spec file was synchronized without applying packit's patches.
This happened when syncing a folder that contains the spefile, e.g.
```yaml
files_to_sync:
- src: distro/
dest: ./
specfile_path: distro/my_pkg.spec
```
=> Exclude upstream specfile from `files_to_sync`
